Added details on the application-level dapr.io/enable-metrics annotation
dapr/docs pull request #1331
Opened 2021-03-23 16:35 UTC by pkedy

## Description

Added details and example for using the application-level `dapr.io/enable-metrics` annotation.

## Issue reference

Resolves #1299

2021-03-23 23:02 UTC, orizohar requested changes

2021-03-23 23:02 UTC, orizohar commented on daprdocs/content/en/operations/monitoring/metrics/metrics-overview.md
> +        dapr.io/enable-metrics: "false"
Is there an annotation to set the metric port as well? if so, I think an example with the port annotation and enabled=true would be better.

2021-03-23 23:02 UTC, orizohar commented on daprdocs/content/en/operations/monitoring/metrics/metrics-overview.md
> +```yaml
This whole article has an implicit assumption that the hosting environment is Kubernetes. Even though this probably only makes sense today for k8s I think it is worth mentioning in the first sentence in the page. Possibly add "... in Kubernetes" in the description field

2021-03-23 23:25 UTC, pkedy commented on daprdocs/content/en/operations/monitoring/metrics/metrics-overview.md
> +        dapr.io/enable-metrics: "false"
The default is actually true and thus usually not specified in the examples to date...  but I see what you are saying. I'll make the change and we can always change it back later.

2021-03-24 21:56 UTC, orizohar approved these changes

2021-03-24 21:59 UTC, merged