feat: add shutdown docs
dapr/docs pull request #1332
Opened 2021-03-23 16:45 UTC by Hugome

- [X] [Read the contribution guide](https://docs.dapr.io/contributing/contributing-docs/)
- [X] Commands include options for Linux, MacOS, and Windows within codetabs
- [X] New file and folder names are globally unique
- [X] Page references use shortcodes instead of markdown or URL links
- [X] Images use HTML style and have alternative text
- [X] Places where multiple code/command options are given have codetabs

## Description

Add documentation for dapr/dapr#2828 (New Shutdown API for job)

2021-03-23 23:20 UTC, orizohar commented
@Hugome - When you write "jobs" are you referring to [Kubernetes jobs](https://kubernetes.io/docs/concepts/workloads/controllers/job/)? if this is a Kubernetes only feature it should go under `operations/hosting/kubernetes/`. I would also create more clarity in the title and linkTitle. For someone unfamiliar this can be confusing. 

Suggestion:
---
...
title: "Running Dapr with a Kubernetes Job"
linkTitle: "Kubernetes  Jobs"
...
---

Also, it would be good to link (as above) to the definition in the k8s docs in the article to set the context for people landing on this and not sure what "jobs" refers to.

2021-03-23 23:22 UTC, orizohar requested changes
Please see my comment on the location of this file and setting the context for readers

2021-03-23 23:22 UTC, orizohar commented on daprdocs/content/en/developing-applications/integrations/job.md
> +The Darp sidecar is designed to be a long running process, in the context of a job this behaviour can block your job completion.
"Darp" --> "Dapr"

2021-03-23 23:23 UTC, orizohar requested changes

2021-03-23 23:23 UTC, orizohar commented on daprdocs/content/en/developing-applications/integrations/job.md
> +You can also call the `Shutdown` from any of the Darp SDK
"Darp" --> "Dapr"

2021-03-23 23:51 UTC, Hugome commented
@orizohar Changes done, I was not sure where to create this page and if I a needed to be really specific about K8S, you have answered :)
And links added to the K8S Job docs

2021-03-24 21:54 UTC, orizohar approved these changes
Thanks for the quick response to feedback. And thanks for the docs contribution!

2021-03-24 21:55 UTC, orizohar commented
@yaron2 - can you take a look at this as well?

2021-03-25 17:28 UTC, orizohar approved these changes

2021-03-25 17:37 UTC, yaron2 approved these changes

2021-03-25 18:22 UTC, merged