Use POST verb for shutdown example
dapr/docs pull request #1366
Opened 2021-04-02 18:51 UTC by wcs1only

Thank you for helping make the Dapr documentation better!

**Please follow this checklist before submitting:**

- [ ] [Read the contribution guide](https://docs.dapr.io/contributing/contributing-docs/)
- [ ] Commands include options for Linux, MacOS, and Windows within codetabs
- [ ] New file and folder names are globally unique
- [ ] Page references use shortcodes instead of markdown or URL links
- [ ] Images use HTML style and have alternative text
- [ ] Places where multiple code/command options are given have codetabs

In addition, please fill out the following to help reviewers understand this pull request:

## Description

## Issue reference

2021-04-02 21:00 UTC, AaronCrawfis approved these changes

2021-04-03 01:44 UTC, artursouza approved these changes

2021-04-06 20:34 UTC, mukundansundar commented on daprdocs/content/en/getting-started/install-dapr-selfhost.md
> +CLI version: 1.1.1
this is still 1.1.0

2021-04-06 20:34 UTC, mukundansundar commented on daprdocs/content/en/operations/hosting/self-hosted/self-hosted-upgrade.md
> +   CLI version: 1.1.1
still 1.1.0

2021-04-06 20:45 UTC, mukundansundar approved these changes

2021-04-06 20:56 UTC, mukundansundar reviewed
Can you add the shutdown API to the API docs? https://github.com/dapr/docs/tree/v1.1/daprdocs/content/en/reference/api

2021-04-06 21:01 UTC, AaronCrawfis approved these changes

2021-04-06 21:10 UTC, wcs1only commented
> Can you add the shutdown API to the API docs? https://github.com/dapr/docs/tree/v1.1/daprdocs/content/en/reference/api

Created a separate issue for this: https://github.com/dapr/docs/issues/1386

2021-04-06 22:32 UTC, mukundansundar requested changes
update supported versions page

2021-04-06 23:48 UTC, mukundansundar approved these changes

2021-04-07 01:07 UTC, merged