Add Alibaba Cloud Nacos binding Doc
dapr/docs pull request #1401
Opened 2021-04-13 03:48 UTC by yanjianlong

Thank you for helping make the Dapr documentation better!

**Please follow this checklist before submitting:**

- [x] [Read the contribution guide](https://docs.dapr.io/contributing/contributing-docs/)
- [x] Commands include options for Linux, MacOS, and Windows within codetabs
- [x] New file and folder names are globally unique
- [x] Page references use shortcodes instead of markdown or URL links
- [x] Images use HTML style and have alternative text
- [x] Places where multiple code/command options are given have codetabs

In addition, please fill out the following to help reviewers understand this pull request:

## Description

Added docs for Alibaba Cloud Nacos binding

## Issue reference
#1400

2021-04-13 23:25 UTC, AaronCrawfis requested changes

2021-04-13 23:25 UTC, AaronCrawfis commented on daprdocs/content/en/reference/components-reference/supported-bindings/alicloud-nacos.md
> +- "/operations/components/setup-bindings/supported-bindings/alicloud-nacos/"
```suggestion
```

You can delete this as it's the first time this page is getting created and there wasn't a prior location.

2021-04-13 23:25 UTC, AaronCrawfis commented on daprdocs/content/en/reference/components-reference/supported-bindings/alicloud-nacos.md
> +Follow the instructions [here](https://help.aliyun.com/document_detail/85466.html) on setting up AliCloud nacos.
```suggestion
Follow [these instructions](https://www.alibabacloud.com/help/doc-detail/59963.htm) to setup AliCloud Nacos.
   - A Chinese (simplified) version can be found [here](https://help.aliyun.com/document_detail/85466.html)
```

Added suggestion for grammer. But curious why these links go to ACM. Shouldn't the Nacos link be https://nacos.io/en-us/docs/quick-start.html?

2021-04-13 23:25 UTC, AaronCrawfis commented on daprdocs/content/en/reference/components-reference/supported-bindings/alicloud-nacos.md
> +When invoking the nacos binding, its possible to provide an optional partition key by using the `metadata` section in the request body.
```suggestion
When invoking the Nacos binding, its possible to provide an optional partition key by using the `metadata` section in the request body.
```

2021-04-16 22:40 UTC, AaronCrawfis commented on daprdocs/content/en/reference/components-reference/supported-bindings/_index.md
> +| [Alibaba Cloud Nacos]({{< ref alicloud-nacos.md >}})           |  ✅ | ✅ | Alpha |  v1 | 1.0 |
```suggestion
| [Alibaba Cloud Nacos]({{< ref alicloud-nacos.md >}})           |  ✅ | ✅ | Alpha |  v1 | 1.2 |
```

2021-04-22 20:22 UTC, orizohar commented
Waiting for code PR https://github.com/dapr/components-contrib/pull/814

2021-05-17 12:26 UTC, AaronCrawfis approved these changes

2021-05-17 12:28 UTC, merged