Add Alibaba Cloud DingTalk Webhook binding doc
dapr/docs pull request #1407
Opened 2021-04-13 06:23 UTC by yanjianlong

Thank you for helping make the Dapr documentation better!

**Please follow this checklist before submitting:**

- [x] [Read the contribution guide](https://docs.dapr.io/contributing/contributing-docs/)
- [x] Commands include options for Linux, MacOS, and Windows within codetabs
- [x] New file and folder names are globally unique
- [x] Page references use shortcodes instead of markdown or URL links
- [x] Images use HTML style and have alternative text
- [x] Places where multiple code/command options are given have codetabs

In addition, please fill out the following to help reviewers understand this pull request:

## Description

Added docs for Alibaba Cloud DingTalk Webhook pubsub

## Issue reference

#1404

2021-04-13 23:32 UTC, AaronCrawfis requested changes

2021-04-13 23:32 UTC, AaronCrawfis commented on daprdocs/content/en/reference/components-reference/supported-bindings/alicloud-dingtalk.md
> +- "/operations/components/setup-bindings/supported-bindings/alicloud-dingtalk/"
```suggestion
```

2021-04-16 19:43 UTC, orizohar submitted a review, later dismissed

2021-04-16 19:43 UTC, orizohar commented on daprdocs/content/en/reference/components-reference/supported-bindings/_index.md
> +| [Alibaba Cloud DingTalk]({{< ref alicloud-dingtalk.md >}})           |  ✅ | ✅ | Alpha | v1 | 1.0 |
If this is merged to v1.2 "Since" should most likely say v1.2

2021-04-21 16:24 UTC, AaronCrawfis approved these changes

2021-04-21 16:24 UTC, AaronCrawfis commented
Waiting on https://github.com/dapr/components-contrib/issues/811 to merge

2021-05-17 12:43 UTC, merged