Aacrawfi/integrations
dapr/docs pull request #1419
Opened 2021-04-14 23:26 UTC by AaronCrawfis

Closes #1412

2021-04-16 19:11 UTC, orizohar requested changes
Looks good! one small comment

2021-04-16 19:11 UTC, orizohar commented on daprdocs/content/en/developing-applications/integrations/workflows.md
> +To enable developers to easily build workflow applications that use Dapr’s capabilities including diagnostics and multi-language support, you can use Dapr workflows. Dapr integrates with workflow eng
"Logic Apps" --> "Azure Logic Apps runtime"

2021-04-20 02:40 UTC, AaronCrawfis commented on daprdocs/content/en/developing-applications/integrations/workflows.md
> +To enable developers to easily build workflow applications that use Dapr’s capabilities including diagnostics and multi-language support, you can use Dapr workflows. Dapr integrates with workflow eng
Fixed

2021-04-22 20:26 UTC, orizohar approved these changes

2021-04-22 20:26 UTC, merged