Update docs on using Codespaces with Dapr repos
dapr/docs pull request #1522
Opened 2021-05-28 02:38 UTC by CodeMonkeyLeet

Thank you for helping make the Dapr documentation better!

**Please follow this checklist before submitting:**

- [x] [Read the contribution guide](https://docs.dapr.io/contributing/contributing-docs/)
- [x] Commands include options for Linux, MacOS, and Windows within codetabs
- [x] New file and folder names are globally unique
- [x] Page references use shortcodes instead of markdown or URL links
- [x] Images use HTML style and have alternative text
- [x] Places where multiple code/command options are given have codetabs

In addition, please fill out the following to help reviewers understand this pull request:

## Description

- Update codespaces.md to:
   - Change name and description of page to indicate the use of Codespaces as developing for Dapr, instead of developing apps with Dapr as is the case with other entries under the IDE Support section of the docs.
   - Include dapr and components-contrib repos as supporting Codespaces
   - Add notes for specific scenario of developing Dapr components using components-contrib Codespace.
- Update contributing-overview.md to link to codespaces.md in process for submitting a PR.

Needs to wait on code PRs for:
- [ ] https://github.com/dapr/dapr/pull/3230
- [ ] NYI: https://github.com/dapr/components-contrib/pull/????

## Issue reference

Resolves #1520

2021-05-28 17:14 UTC, AaronCrawfis requested changes

2021-05-28 17:14 UTC, AaronCrawfis commented on daprdocs/content/en/developing-applications/ides/codespaces.md
> +title: "Contributing with GitHub Codespaces"
Title change looks good. We should move this page into the Contributing section under Presentations

2021-05-28 22:22 UTC, CodeMonkeyLeet commented on daprdocs/content/en/developing-applications/ides/codespaces.md
> +title: "Contributing with GitHub Codespaces"
Done ... I also reduced the weight of the page so that it has a consistent position above the pages mounted from the SDK repos.

2021-06-03 00:23 UTC, AaronCrawfis commented on daprdocs/content/en/contributing/codespaces.md
> +---
```suggestion
aliases:
  - "/developing-applications/ides/codespaces/"
---
```

2021-06-03 00:24 UTC, AaronCrawfis approved these changes

2021-06-03 00:28 UTC, merged