Add info about accessing container images from private registries
dapr/docs pull request #1628
Opened 2021-07-09 05:32 UTC by dmitsh

Thank you for helping make the Dapr documentation better!

**Please follow this checklist before submitting:**

- [x] [Read the contribution guide](https://docs.dapr.io/contributing/contributing-docs/)
- [x] Commands include options for Linux, MacOS, and Windows within codetabs
- [ ] New file and folder names are globally unique
- [ ] Page references use shortcodes instead of markdown or URL links
- [ ] Images use HTML style and have alternative text
- [ ] Places where multiple code/command options are given have codetabs

In addition, please fill out the following to help reviewers understand this pull request:

## Description
Add info about accessing container images from private registries

## Issue reference

https://github.com/dapr/dapr/issues/3298

2021-07-09 05:37 UTC, dmitsh commented
@AaronCrawfis , @msfussell , please review style/wording.

2021-07-09 17:16 UTC, AaronCrawfis requested changes

2021-07-09 17:16 UTC, AaronCrawfis commented on daprdocs/content/en/operations/hosting/kubernetes/kubernetes-overview.md
> +#### Container images from private registries
```suggestion
## Pull container images from private registries

```

2021-07-09 17:16 UTC, AaronCrawfis commented on daprdocs/content/en/operations/hosting/kubernetes/kubernetes-overview.md
> +Dapr works seamlessly with any container image, regardless of its origin. For information about pulling images from a private registry read [Kubernetes documentation](https://kubernetes.io/docs/tasks
```suggestion
Dapr works seamlessly with any container image, regardless of its origin, if the cluster is configured to pull from the registry. For information about pulling images from a private registry, reference the [Kubernetes documentation](https://kubernetes.io/docs/tasks/configure-pod-container/pull-image-private-registry/). If you are using Azure Container Registry with Azure Kubernetes Service, reference the [AKS documentation](https://docs.microsoft.com/en-us/azure/aks/cluster-container-registry-integration).
```

2021-07-09 17:16 UTC, AaronCrawfis commented on daprdocs/content/en/operations/hosting/kubernetes/kubernetes-overview.md
> +
```suggestion
```

2021-07-09 19:03 UTC, AaronCrawfis requested changes
Clarified after revisiting context

2021-07-09 19:03 UTC, AaronCrawfis commented on daprdocs/content/en/operations/hosting/kubernetes/kubernetes-overview.md
> +Dapr works seamlessly with any container image, regardless of its origin, if the cluster is configured to pull from the registry. For information about pulling images from a private registry, referen
```suggestion
Dapr works seamlessly with any user application container image, regardless of its origin. Simply init Dapr and add the [Dapr annotations]({{< ref kubernetes-annotations >}}) to your Kubernetes definition to add the Dapr sidecar.

The Dapr control-plane and sidecar images come from the [daprio Docker Hub](https://hub.docker.com/u/daprio) container registry.

For information about pulling your application images from a private registry, reference the [Kubernetes documentation](https://kubernetes.io/docs/tasks/configure-pod-container/pull-image-private-registry/). If you are using Azure Container Registry with Azure Kubernetes Service, reference the [AKS documentation](https://docs.microsoft.com/en-us/azure/aks/cluster-container-registry-integration).
```

2021-07-09 20:03 UTC, AaronCrawfis approved these changes

2021-07-13 23:56 UTC, orizohar commented
@dmitsh I see this is opened for 1.3 but I see no reason why it couldn't have been PRd into 1.2 right? As we are pretty close to releasing 1.3 it doesn't matter much but in general better to push these into the current branch

2021-07-13 23:56 UTC, merged