Add information to create a database named 'daprStore' in case no dat…
dapr/docs pull request #1629
Opened 2021-07-09 08:11 UTC by kshitijcode

…abaseName is specified as Dapr Mongo Component defaults to `daprStore`

Add information to create a database named 'daprStore' in case no databaseName is specified as Dapr Mongo Component defaults to `daprStore`

Thank you for helping make the Dapr documentation better!

**Please follow this checklist before submitting:**

- [ ] [Read the contribution guide](https://docs.dapr.io/contributing/contributing-docs/)
- [ ] Commands include options for Linux, MacOS, and Windows within codetabs
- [ ] New file and folder names are globally unique
- [ ] Page references use shortcodes instead of markdown or URL links
- [ ] Images use HTML style and have alternative text
- [ ] Places where multiple code/command options are given have codetabs

In addition, please fill out the following to help reviewers understand this pull request:

## Description

## Issue reference

2021-07-09 17:24 UTC, AaronCrawfis requested changes
Thank you for your contribution! Small request, as alerts don't always render correctly inside of codetabs on some systems.

2021-07-09 17:24 UTC, AaronCrawfis commented on daprdocs/content/en/reference/components-reference/supported-state-stores/setup-mongodb.md
> +
```suggestion

You can then interact with the server using `localhost:27017`.

If you do not specify a `databaseName` value in your component definition, make sure to create a database named `daprStore`. 

```

2021-07-10 04:37 UTC, kshitijcode commented on daprdocs/content/en/reference/components-reference/supported-state-stores/setup-mongodb.md
> +
Sure, made the necessary change.

2021-07-13 23:53 UTC, orizohar approved these changes
Thanks for the added clarification!

2021-07-14 01:10 UTC, AaronCrawfis approved these changes

2021-07-15 17:01 UTC, merged