docs/jaeger: add jaeger production configuration
dapr/docs pull request #1664
Opened 2021-07-17 02:05 UTC by 1046102779

2021-07-17 02:11 UTC, 1046102779 commented
@orizohar please review this pr, thks.

2021-07-21 20:03 UTC, AaronCrawfis requested changes

2021-07-21 20:03 UTC, AaronCrawfis commented on daprdocs/content/en/operations/monitoring/tracing/supported-tracing-backends/jaeger.md
> +defaultly, allInOne uses memory as the backend storage. If you use the YAML configuration to deploy in production environment, it is dangerous!!!
```suggestion
By default, the allInOne Jaeger image uses memory as the backend storage and it is not recommended to use this in a production environment.
```

2021-07-21 20:03 UTC, AaronCrawfis commented on daprdocs/content/en/operations/monitoring/tracing/supported-tracing-backends/jaeger.md
> +#### development/test configuration
```suggestion
#### Development and test
```

2021-07-21 20:03 UTC, AaronCrawfis commented on daprdocs/content/en/operations/monitoring/tracing/supported-tracing-backends/jaeger.md
> +#### production configuration
```suggestion
#### Production
```

2021-07-21 20:03 UTC, AaronCrawfis commented on daprdocs/content/en/operations/monitoring/tracing/supported-tracing-backends/jaeger.md
> +jaeger uses elasticsearch as the backend storage, you maybe create jaeger-secret to access elasticsearch server. see [Configuring and Deploying Jaeger](https://docs.openshift.com/container-platform/4
Could you clarify this? Currently unclear.

2021-07-21 20:03 UTC, AaronCrawfis commented on daprdocs/content/en/operations/monitoring/tracing/supported-tracing-backends/jaeger.md
> +> kubectl create secret generic jaeger-secret --from-literal=ES_PASSWORD='xxx' --from-literal=ES_USERNAME='xxx' -n ${NAMESPACE}
Please use multi-line command block instead of note (```)

2021-07-21 21:51 UTC, orizohar requested changes
Please use upper case for start of sentence and names of technologies e.g. Jaeger Elasticsearch see [here](https://docs.dapr.io/contributing/contributing-docs/#style-and-tone) for guidance

2021-07-22 22:00 UTC, msfussell reviewed
Looks like you have forgotten to add the ![jaeger](/images/jaeger_ui.png) image file as part of this PR. Can you include this?

2021-07-23 05:17 UTC, 1046102779 commented
> n to a



> Looks like you have forgotten to add the ![jaeger](/images/jaeger_ui.png) image file as part of this PR. Can you include this?

ok.

2021-08-10 20:59 UTC, orizohar approved these changes

2021-08-10 21:01 UTC, AaronCrawfis approved these changes

2021-08-10 21:06 UTC, merged