updated binding smtp doc: added priority option
dapr/docs pull request #1666
Opened 2021-07-18 16:19 UTC by fjvela

Thank you for helping make the Dapr documentation better!

**Please follow this checklist before submitting:**

- [ ] [Read the contribution guide](https://docs.dapr.io/contributing/contributing-docs/)
- [ ] Commands include options for Linux, MacOS, and Windows within codetabs
- [ ] New file and folder names are globally unique
- [ ] Page references use shortcodes instead of markdown or URL links
- [ ] Images use HTML style and have alternative text
- [ ] Places where multiple code/command options are given have codetabs

In addition, please fill out the following to help reviewers understand this pull request:

## Description
Add priority option in SMTP binding in order to select the email priority (values: highest[1] to lowest[5])

https://www.chilkatsoft.com/p/p_471.asp
https://github.com/dapr/components-contrib/issues/1017

## Issue reference
Please reference the issue this PR will close: 
https://github.com/dapr/docs/issues/1665

2021-08-05 20:56 UTC, AaronCrawfis requested changes

2021-08-05 20:56 UTC, AaronCrawfis commented on daprdocs/content/en/reference/components-reference/supported-bindings/smtp.md
> +    value: "priority value (highest[1] to lowest[5])"
```suggestion
    value: "[value 1-5]"
```

2021-08-05 20:56 UTC, AaronCrawfis commented on daprdocs/content/en/reference/components-reference/supported-bindings/smtp.md
> +| priority | N | Output | If set, this specifies the priority (X-Priority) of the email message (default value: 3). See [also](#example-request) | `"1"` |
```suggestion
| priority | N | Output | If set, this specifies the priority (X-Priority) of the email message, from 1 (lowest) to 5 (highest) (default value: 3). See [also](#example-request) | `"1"` |
```

2021-08-10 21:11 UTC, orizohar approved these changes

2021-08-11 00:33 UTC, orizohar requested changes

2021-08-11 00:33 UTC, orizohar commented on daprdocs/content/en/reference/components-reference/supported-bindings/smtp.md
> +    "piority: "1"
```suggestion
    "priority: "1"
```

2021-08-11 15:58 UTC, orizohar approved these changes

2021-08-11 17:06 UTC, AaronCrawfis approved these changes

2021-08-11 17:08 UTC, merged