Confluent kafka
dapr/docs pull request #1669
Opened 2021-07-19 06:31 UTC by cshi0

Thank you for helping make the Dapr documentation better!

**Please follow this checklist before submitting:**

- [x] [Read the contribution guide](https://docs.dapr.io/contributing/contributing-docs/)
- [ ] Commands include options for Linux, MacOS, and Windows within codetabs
- [ ] New file and folder names are globally unique
- [ ] Page references use shortcodes instead of markdown or URL links
- [ ] Images use HTML style and have alternative text
- [ ] Places where multiple code/command options are given have codetabs

In addition, please fill out the following to help reviewers understand this pull request:

## Description

Added reference for confluent kafka

## Issue reference
#1582

2021-07-21 20:05 UTC, AaronCrawfis commented
Waiting on https://github.com/dapr/components-contrib/issues/968

2021-08-05 20:55 UTC, orizohar commented
Looks like this is a new feature, if so please make sure the PR is targeting the pre-release branch which is currently v1.4

2021-08-16 23:35 UTC, AaronCrawfis commented on daprdocs/content/en/reference/components-reference/supported-pubsub/setup-confluent-kafka.md
> +linkTitle: "Apache Kafka (confluent kafka)"
```suggestion
linkTitle: "Apache Kafka (Confluent)"
```
In the linkTitle it's best to be as concise as possible. Would shortening to this make sense?

2021-09-08 20:08 UTC, greenie-msft commented
@cshi0, As @orizohar mentioned, can you please target this PR to branch v1.4? This is implementing a new feature and will be available in the 1.4 release.

Thank you.

2021-09-08 22:18 UTC, greenie-msft commented
@artursouza Looks like the code PR is stale (closed) and not going in. Can we close this docs PR?

2022-01-21 19:23 UTC, hhunter-ms requested changes
Quick grammar/style review.

2022-01-21 19:23 UTC, hhunter-ms commented on daprdocs/content/en/reference/components-reference/supported-pubsub/setup-confluent-kafka.md
> +To setup Apache Kafka pubsub using confluent kafka sdk create a component of type `pubsub.confluentkafka`. See [this guide]({{< ref "howto-publish-subscribe.md#step-1-setup-the-pubsub-component" >}})
```suggestion
Set up Apache Kafka Pub/sub component using Confluent Kafka SDK. If you need a refresher, see our [How-To: Publish a message and subscribe to a topic guide]({{< ref "howto-publish-subscribe.md#step-1-setup-the-pubsub-component" >}}) to create and apply a Pub/sub configuration.

Create a Pub/sub component called `pubsub.confluentkafka.yaml` with the following example content:
```

2022-01-21 19:23 UTC, hhunter-ms commented on daprdocs/content/en/reference/components-reference/supported-pubsub/setup-confluent-kafka.md
> +The above example uses secrets. It is recommended to use a secret store for the secrets as described [here]({{< ref component-secrets.md >}}).
```suggestion
The above example uses secrets. We recommend using a [secret store for the secrets]({{< ref component-secrets.md >}}).
```

2022-01-21 19:23 UTC, hhunter-ms commented on daprdocs/content/en/reference/components-reference/supported-pubsub/setup-confluent-kafka.md
> +| configJson             | Y  | A json string consists of configurations of the sdk client. For more settings, see [confluent kafka configuration reference](https://docs.confluent.io/platform/current
```suggestion
| configJson             | Y  | A json string consists of configurations of the client SDK. For more settings, see the [Confluent Kafka configuration reference](https://docs.confluent.io/platform/current/installation/configuration/).  | 
```

2022-01-21 19:23 UTC, hhunter-ms commented on daprdocs/content/en/reference/components-reference/supported-pubsub/setup-confluent-kafka.md
> +When invoking the Kafka pub/sub, it's possible to provide an optional partition section by using the `metadata` query param in the request url.
```suggestion
Provide an optional partition section with the `metadata` query parameter in the request URL.
```

2022-01-21 19:23 UTC, hhunter-ms commented on daprdocs/content/en/reference/components-reference/supported-pubsub/setup-confluent-kafka.md
> +It's also possible to pass in an optional key for the message.
```suggestion
Pass in an optional key for the message.
```

2022-01-21 19:23 UTC, hhunter-ms commented on daprdocs/content/en/reference/components-reference/supported-pubsub/setup-confluent-kafka.md
> +### headers
```suggestion
### Headers
```

2022-01-21 19:23 UTC, hhunter-ms commented on daprdocs/content/en/reference/components-reference/supported-pubsub/setup-confluent-kafka.md
> +
```suggestion
When invoking the Kafka Pub/sub component, you can pass in several optional metadata parameters.
```

2022-01-21 19:23 UTC, hhunter-ms commented on daprdocs/content/en/reference/components-reference/supported-pubsub/setup-confluent-kafka.md
> +Unlimited number of headers can also be passed in.
```suggestion
Pass in an unlimited number of headers.
```

2022-01-21 19:23 UTC, hhunter-ms commented on daprdocs/content/en/reference/components-reference/supported-pubsub/setup-confluent-kafka.md
> +The param name is begin with `header.`.
```suggestion
The parameter name begins with `header.`.
```

2022-01-21 19:23 UTC, hhunter-ms commented on daprdocs/content/en/reference/components-reference/supported-pubsub/setup-confluent-kafka.md
> +The param name is `partition`.
```suggestion
The parameter name is `partition`.
```

2022-01-21 19:23 UTC, hhunter-ms commented on daprdocs/content/en/reference/components-reference/supported-pubsub/setup-confluent-kafka.md
> +The param name is `key`.
```suggestion
The parameter name is `key`.
```

2022-01-21 19:23 UTC, hhunter-ms commented on daprdocs/content/en/reference/components-reference/supported-pubsub/setup-confluent-kafka.md
> +You can run Kafka locally using [this](https://github.com/wurstmeister/kafka-docker) Docker image.
```suggestion
Run Kafka locally using [this Docker image](https://github.com/wurstmeister/kafka-docker). To run without Docker, see the [Apache Kafka getting started guide](https://kafka.apache.org/quickstart).
```

2022-01-21 19:23 UTC, hhunter-ms commented on daprdocs/content/en/reference/components-reference/supported-pubsub/setup-confluent-kafka.md
> +To run without Docker, see the getting started guide [here](https://kafka.apache.org/quickstart).
```suggestion

```

2022-01-21 19:23 UTC, hhunter-ms commented on daprdocs/content/en/reference/components-reference/supported-pubsub/setup-confluent-kafka.md
> +To run Kafka on Kubernetes, you can use any Kafka operator, such as [Strimzi](https://strimzi.io/docs/operators/latest/quickstart.html#ref-install-prerequisites-str).
```suggestion
You can run Kafka on Kubernetes using any Kafka operator, such as [Strimzi](https://strimzi.io/docs/operators/latest/quickstart.html#ref-install-prerequisites-str).
```

2022-01-21 19:23 UTC, hhunter-ms commented on daprdocs/content/en/reference/components-reference/supported-pubsub/setup-confluent-kafka.md
> +- Read [this guide]({{< ref "howto-publish-subscribe.md##step-1-setup-the-pubsub-component" >}}) for instructions on configuring pub/sub components
```suggestion
- [Create and configure Pub/sub components]({{< ref "howto-publish-subscribe.md##step-1-setup-the-pubsub-component" >}}).
```

2022-09-01 21:48 UTC, berndverst commented
Please close this PR. This will not be merged.

2022-09-01 21:49 UTC, berndverst commented
FYI @greenie-msft

2022-09-20 20:50 UTC, closed without merging