Mentioning multi-valued secret support for local file secret store
dapr/docs pull request #1734
Opened 2021-08-20 16:41 UTC by pkedy

## Description

Adding the documentation/setting for multi-valued secrets in the local file secret store.

Merged PR dapr/components-contrib#1089

## Issue reference

Closes #1733

/cc @artursouza

2021-08-20 18:47 UTC, artursouza requested changes

2021-08-20 18:47 UTC, artursouza commented on daprdocs/content/en/reference/components-reference/supported-secret-stores/file-secret-store.md
> +If `multiValued` is `"true"`, you would instead use the top level key. In this example, `connectionStrings` would return the following map:
Please, also mention how the subtrees are flat here as well and appended with the separator. It was the main difference between your approach and the one I had in mind. I actually think your approach is better and should be documented here for user's benefit.

2021-08-25 18:15 UTC, pkedy commented on daprdocs/content/en/reference/components-reference/supported-secret-stores/file-secret-store.md
> +If `multiValued` is `"true"`, you would instead use the top level key. In this example, `connectionStrings` would return the following map:
@artursouza See new content below

2021-08-25 18:49 UTC, artursouza approved these changes

2021-08-25 21:34 UTC, orizohar approved these changes

2021-08-25 21:34 UTC, merged