actions
dapr/docs pull request #1744
Opened 2021-08-25 16:31 UTC by DarqueWarrior

Thank you for helping make the Dapr documentation better!

**Please follow this checklist before submitting:**

- [x] [Read the contribution guide](https://docs.dapr.io/contributing/contributing-docs/)
- [x] Commands include options for Linux, MacOS, and Windows within codetabs
- [x] New file and folder names are globally unique
- [x] Page references use shortcodes instead of markdown or URL links
- [x] Images use HTML style and have alternative text
- [x] Places where multiple code/command options are given have codetabs

In addition, please fill out the following to help reviewers understand this pull request:

## Description

I was asked by Aaron to add GitHub Action integration page.

## Issue reference

#1634

2021-08-25 17:18 UTC, AaronCrawfis requested changes

2021-08-25 17:18 UTC, AaronCrawfis commented on daprdocs/content/en/developing-applications/integrations/github-actions.md
> +title: "GitHub Actions"
```suggestion
title: "Use the Dapr CLI in a GitHub Actions workflow"
```

2021-08-25 17:18 UTC, AaronCrawfis commented on daprdocs/content/en/developing-applications/integrations/github-actions.md
> +description: "Deploy your application with GitHub Actions"
```suggestion
description: "Learn how to add the Dapr CLI to your GitHub Actions to deploy and manage Dapr in your environments."
```

2021-08-25 17:18 UTC, AaronCrawfis commented on daprdocs/content/en/developing-applications/integrations/github-actions.md
> +Dapr can be integrated with GitHub Actions via the [Dapr tool installer](https://github.com/marketplace/actions/dapr-tool-installer) available in the GitHub Marketplace.
```suggestion
Dapr can be integrated with GitHub Actions via the [Dapr tool installer](https://github.com/marketplace/actions/dapr-tool-installer) available in the GitHub Marketplace. This installer adds the Dapr CLI to your workflow, allowing you to deploy, manage, and upgrade Dapr across your environments.
```

2021-08-25 17:18 UTC, AaronCrawfis commented on daprdocs/content/en/developing-applications/integrations/github-actions.md
> +Before Dapr can be used in your Action Workflow you must install the Dapr CLI on the runner. Using the Dapr tool installer action will install the specified version of the Dapr CLI on macOS, Linux an
```suggestion
The `dapr/setup-dapr` action will install the specified version of the Dapr CLI on macOS, Linux and Windows runners. Once installed, you can run any [Dapr CLI command]({{< ref cli >}}) to manage your Dapr environments.
```

2021-08-25 17:18 UTC, AaronCrawfis commented on daprdocs/content/en/developing-applications/integrations/github-actions.md
> +Before Dapr can be used in your Action Workflow you must install the Dapr CLI on the runner. Using the Dapr tool installer action will install the specified version of the Dapr CLI on macOS, Linux an
Also add in the example you have from https://github.com/marketplace/actions/dapr-tool-installer to show the syntax with optional parameters.

2021-08-25 17:18 UTC, AaronCrawfis commented on daprdocs/content/en/developing-applications/integrations/github-actions.md
> +  uses: dapr/setup-dapr@v1
```suggestion
  uses: dapr/setup-dapr@v1
  with:
    version: '1.3.0'
```

2021-08-25 21:54 UTC, greenie-msft commented on .github/workflows/website-v1-4.yml
> -      - v1.3
@DarqueWarrior Should these workflow and config files be included in your changes?

2021-08-27 15:59 UTC, orizohar commented
@DarqueWarrior looks like this PR includes unrelated changes, most likely due to a need to rebase (was your branch based on v1.4 and now merging into v1.3?). Can you please make sure only the new content is included?

2021-08-30 17:58 UTC, DarqueWarrior commented
I tried to rebase this off of 1.3 after @AaronCrawfis  mentioned it. It should be corrected I think.

2021-08-30 18:00 UTC, DarqueWarrior commented
Let me see if I can get this fixed up. I still see to many changes in this branch.

2021-09-08 20:30 UTC, greenie-msft commented
@DarqueWarrior, another option is to create a new branch/PR from latest v1.3 branch and copy your changes over. Might be easier than trying to troubleshoot the current PR.

2021-09-09 17:26 UTC, greenie-msft commented
I'm taking this PR over. Closing this PR and creating a new one.

2021-09-09 17:26 UTC, closed without merging