Add documentation about actor's timer/reminder scheduling configuration
dapr/docs pull request #1748
Opened 2021-08-26 18:55 UTC by dmitsh

Thank you for helping make the Dapr documentation better!

**Please follow this checklist before submitting:**

- [x] [Read the contribution guide](https://docs.dapr.io/contributing/contributing-docs/)
- [x] Commands include options for Linux, MacOS, and Windows within codetabs
- [ ] New file and folder names are globally unique
- [x] Page references use shortcodes instead of markdown or URL links
- [ ] Images use HTML style and have alternative text
- [ ] Places where multiple code/command options are given have codetabs

In addition, please fill out the following to help reviewers understand this pull request:

## Description

Added documentation about actor's timer/reminder scheduling configuration

## Issue reference

#1701

2021-08-31 22:48 UTC, willtsai requested changes
overall LGTM -- the only substantial suggestions I have are to consistently reference the SDK docs in Dapr Docs instead of their GH repos.

2021-08-31 22:48 UTC, willtsai commented on daprdocs/content/en/developing-applications/building-blocks/actors/actors-overview.md
> +Another, and perhaps more convenient way of interacting with actors is via SDKs. Dapr currently supports actors SDKs in [.NET]({{< ref "dotnet-actors" >}}), [Java](https://github.com/dapr/java-sdk/tr
```suggestion
Another, and perhaps more convenient way of interacting with actors, is via SDKs. Dapr currently supports actors SDKs in [.NET]({{< ref "dotnet-actors" >}}), [Java]({{< ref "java#actors" >}}), and [Python]({{< ref "python-actor" >}}).
```

2021-08-31 22:48 UTC, willtsai commented on daprdocs/content/en/developing-applications/building-blocks/actors/actors-overview.md
> +Another, and perhaps more convenient way of interacting with actors is via SDKs. Dapr currently supports actors SDKs in [.NET]({{< ref "dotnet-actors" >}}), [Java](https://github.com/dapr/java-sdk/tr
Grammar nit: need another comma in first sentence

References should point to other Dapr Docs pages for actors instead of GitHub repo. The GH repos are subsequently linked from each SDK's Dapr Docs page(s).

2021-08-31 22:48 UTC, willtsai commented on daprdocs/content/en/developing-applications/building-blocks/actors/howto-actors.md
> +Alternatively, you can use Dapr SDK in [.NET]({{< ref "dotnet-actors" >}}), [Java](https://github.com/dapr/java-sdk/tree/master/examples/src/main/java/io/dapr/examples/actors), or [Python](https://gi
```suggestion
Alternatively, you can use the Dapr SDK in [.NET]({{< ref "dotnet-actors" >}}), [Java]({{< ref "java#actors" >}}), or [Python]({{< ref "python-actor" >}}).
```

2021-08-31 22:48 UTC, willtsai commented on daprdocs/content/en/developing-applications/building-blocks/actors/howto-actors.md
> +Alternatively, you can use Dapr SDK in [.NET]({{< ref "dotnet-actors" >}}), [Java](https://github.com/dapr/java-sdk/tree/master/examples/src/main/java/io/dapr/examples/actors), or [Python](https://gi
References should point to other Dapr Docs pages for actors instead of GitHub repo. The GH repos are subsequently linked from each SDK's Dapr Docs page(s).

2021-09-01 17:20 UTC, willtsai approved these changes
Two more minor nitpicking changes, otherwise LGTM. I built the docs locally and confirmed that SDK reference links work as expected.

2021-09-01 17:20 UTC, willtsai commented on daprdocs/content/en/developing-applications/building-blocks/actors/actors-overview.md
> +Another, and perhaps more convenient way of interacting with actors, is via SDKs. Dapr currently supports actors SDKs in [.NET]({{< ref "dotnet-actors" >}}), [Java]({{< ref "java#actors" >}}), and [P
```suggestion
Another, and perhaps more convenient, way of interacting with actors is via SDKs. Dapr currently supports actors SDKs in [.NET]({{< ref "dotnet-actors" >}}), [Java]({{< ref "java#actors" >}}), and [Python]({{< ref "python-actor" >}}).
```

2021-09-01 17:20 UTC, willtsai commented on daprdocs/content/en/developing-applications/building-blocks/actors/actors-overview.md
> +Another, and perhaps more convenient way of interacting with actors, is via SDKs. Dapr currently supports actors SDKs in [.NET]({{< ref "dotnet-actors" >}}), [Java]({{< ref "java#actors" >}}), and [P
nit on my previous grammar nit: correcting my prior grammatical suggestion, the comma needs to be after 'convenient'. sorry for the roundtrip!

2021-09-01 17:20 UTC, willtsai commented on daprdocs/content/en/developing-applications/building-blocks/actors/howto-actors.md
> +* time.Duration format. Example: `2h30m`
```suggestion
* RFC3339 date format, e.g. `2020-10-02T15:00:00Z`
* time.Duration format, e.g. `2h30m`
```

2021-09-01 17:20 UTC, willtsai commented on daprdocs/content/en/developing-applications/building-blocks/actors/howto-actors.md
> +* time.Duration format. Example: `2h30m`
Nit: edits to align more with with previous examples.

2021-09-01 17:33 UTC, dmitsh commented
@willtsai , thank you for reviewing!

2021-09-02 20:59 UTC, orizohar approved these changes

2021-09-02 21:00 UTC, orizohar commented
@dmitsh - is there an associated code change for this doc change? can you point to the code PR?

2021-09-02 21:02 UTC, orizohar commented
> @dmitsh - is there an associated code change for this doc change? can you point to the code PR?

Is this the PR? https://github.com/dapr/dapr/pull/3437

2021-09-02 22:49 UTC, dmitsh commented
> > @dmitsh - is there an associated code change for this doc change? can you point to the code PR?
> 
> Is this the PR? [dapr/dapr#3437](https://github.com/dapr/dapr/pull/3437)

There are several PRs addressing this issue.
The main two are:
https://github.com/dapr/dapr/pull/3437
https://github.com/dapr/dapr/pull/3479

and two additional:
https://github.com/dapr/dapr/pull/3547
https://github.com/dapr/dapr/pull/3541

2021-09-08 20:31 UTC, greenie-msft approved these changes

2021-09-08 20:31 UTC, greenie-msft approved these changes

2021-09-08 22:31 UTC, merged