gcp bucket update
dapr/docs pull request #1792
Opened 2021-09-15 19:13 UTC by fjvela

Thank you for helping make the Dapr documentation better!

**Please follow this checklist before submitting:**

- [ ] [Read the contribution guide](https://docs.dapr.io/contributing/contributing-docs/)
- [ ] Commands include options for Linux, MacOS, and Windows within codetabs
- [ ] New file and folder names are globally unique
- [ ] Page references use shortcodes instead of markdown or URL links
- [ ] Images use HTML style and have alternative text
- [ ] Places where multiple code/command options are given have codetabs

In addition, please fill out the following to help reviewers understand this pull request:

## Description
Update GCP Storage Bucket binding:

- update create operation: support upload files in base64 (https://docs.dapr.io/reference/components-reference/supported-bindings/gcpbucket/#upload-a-file doesn't work), return object url to download
- add get operation
- add delete operation
- add list operation
- create operation replace field name with field key (field name backward compatibility), now you can use blob storage, s3 or gcp bucket without change metadata request

## Issue reference

https://github.com/dapr/docs/issues/1790

2021-09-30 20:51 UTC, orizohar requested changes

2021-09-30 20:51 UTC, orizohar commented on daprdocs/content/en/reference/components-reference/supported-bindings/gcpbucket.md
> +To perform a get file operation, invoke the AWS S3 binding with a `POST` method and the following JSON body:
This refers to AWS S3. Should this be GCP bucket?

2021-09-30 20:51 UTC, greenie-msft commented
@fjvela please see @orizohar's comment. 

@yaron2, would you like to review this as well?

2021-10-06 22:22 UTC, msfussell approved these changes
LGTM

2021-10-06 22:26 UTC, orizohar approved these changes

2021-10-08 21:14 UTC, merged