azure blog storage add publicAccessLevel param
dapr/docs pull request #1842
Opened 2021-10-07 18:03 UTC by fjvela

Thank you for helping make the Dapr documentation better!

**Please follow this checklist before submitting:**

- [ ] [Read the contribution guide](https://docs.dapr.io/contributing/contributing-docs/)
- [ ] Commands include options for Linux, MacOS, and Windows within codetabs
- [ ] New file and folder names are globally unique
- [ ] Page references use shortcodes instead of markdown or URL links
- [ ] Images use HTML style and have alternative text
- [ ] Places where multiple code/command options are given have codetabs

In addition, please fill out the following to help reviewers understand this pull request:

## Description

## Issue reference

2021-10-08 21:37 UTC, greenie-msft requested changes

2021-10-08 21:37 UTC, greenie-msft commented on daprdocs/content/en/reference/components-reference/supported-bindings/blobstorage.md
> +| publicAccessLevel | N | Output | Specifies whether data in the container may be accessed publicly and the level of access (only it's used if the container is created by dapr). Defaults to `none` |
```suggestion
| publicAccessLevel | N | Output | Specifies whether data in the container may be accessed publicly and the level of access (only used if the container is created by Dapr). Defaults to `none` | `blob`, `container`, `none` 
```

2021-10-27 19:50 UTC, willtsai approved these changes
LGTM. Reference for confirmation:
- https://docs.microsoft.com/en-us/azure/storage/blobs/anonymous-read-access-configure?tabs=azure-cli
- https://github.com/dapr/components-contrib/blob/master/bindings/azure/blobstorage/blobstorage.go#L160-L162

2021-10-28 21:44 UTC, greenie-msft approved these changes

2021-10-28 21:50 UTC, merged