Update cosmosDB state `partitionkey` usage
dapr/docs pull request #1846
Opened 2021-10-08 20:44 UTC by CodeMonkeyLeet

Thank you for helping make the Dapr documentation better!

**Please follow this checklist before submitting:**

- [x] [Read the contribution guide](https://docs.dapr.io/contributing/contributing-docs/)
- [ ] Commands include options for Linux, MacOS, and Windows within codetabs
- [ ] New file and folder names are globally unique
- [x] Page references use shortcodes instead of markdown or URL links
- [ ] Images use HTML style and have alternative text
- [ ] Places where multiple code/command options are given have codetabs

In addition, please fill out the following to help reviewers understand this pull request:

## Description

- Increase emphasis of default `/paritionKey` partition key for CosmosDB collections for use with Dapr state stores.
- Add example of using `partitionKey` metadata with CosmosDB collection using custom partition keys.
- Add `keyPrefix` configuration documentation to state_api.md.

## Issue reference

Fixes #1845

2021-10-11 23:06 UTC, CodeMonkeyLeet commented
@artursouza @berndverst to review for technical accuracy. The behaviors documented are empirically determined, but it's unclear to me whether all of it is intended.

2021-10-27 18:26 UTC, artursouza commented on daprdocs/content/en/reference/api/state_api.md
> -### Key scheme
Keep the title.

2021-10-27 18:30 UTC, artursouza requested changes
The Dapr state store API is an opinionated implementation and does not offer a "bring your own schema" functionality. For that, we plan to support a new API for databases, where apps will be able to bring their own schemas and key structure.

https://github.com/dapr/dapr/issues/3354

2021-10-28 20:51 UTC, CodeMonkeyLeet commented on daprdocs/content/en/reference/api/state_api.md
> -### Key scheme
@artursouza FYI, the key scheme section under Optional Behaviors is redundant as there is a top level `## Key Scheme` section on line 37 that repeats the same info. Given that the key scheme isn't really an optional behavior, it should probably be removed.

2021-11-03 19:17 UTC, closed without merging