(v1.5)feature/pubsub: add delay queue params for pulsar
dapr/docs pull request #1856
Opened 2021-10-15 01:27 UTC by 1046102779

https://github.com/dapr/docs/pull/1759

2021-10-15 01:28 UTC, 1046102779 commented
@greenie-msft @msfussell @willtsai done.

2021-10-15 17:56 UTC, willtsai commented
Thank you @1046102779 - referencing the previous PR here as well: https://github.com/dapr/docs/pull/1759

Maintainers will review this PR now.

2021-10-27 18:53 UTC, willtsai requested changes

2021-10-27 18:53 UTC, willtsai commented on daprdocs/content/en/reference/components-reference/supported-pubsub/setup-pulsar.md
> +| deliverAfter | N | delay queue configuration param. Default is empty | `"4h5m3s"`|
Making some suggestions here to make it clear that these parameters are not a part of the metadata fields for the Dapr component spec.

```suggestion
When invoking the Pulsar pub/sub, it's possible to provide an optional delay queue by using the `metadata` query parameters in the request url.

These optional parameter names are `metadata.deliverAt` or `metadata.deliverAfter`:
- `deliverAt`: Delay message to deliver at a specified time (RFC3339 format), e.g. `"2021-09-01T10:00:00Z"`
- `deliverAfter`: Delay message to deliver after a specified amount of time, e.g.`"4h5m3s"`
```

2021-10-27 18:53 UTC, willtsai commented on daprdocs/content/en/reference/components-reference/supported-pubsub/setup-pulsar.md
> +Example:
```suggestion
Examples:
```

2021-10-30 00:25 UTC, 1046102779 commented on daprdocs/content/en/reference/components-reference/supported-pubsub/setup-pulsar.md
> +Example:
@willtsai Help me and check if it's OK？ Thanks.

2021-11-01 20:07 UTC, willtsai commented on daprdocs/content/en/reference/components-reference/supported-pubsub/setup-pulsar.md
> +Example:
@1046102779 - take a look at my comments above where I suggest in-line changes that you may just add to your commits if you agree with my suggestions. Does this make sense?

2021-11-05 15:50 UTC, 1046102779 commented on daprdocs/content/en/reference/components-reference/supported-pubsub/setup-pulsar.md
> +Example:
fixed.

2021-11-05 15:50 UTC, 1046102779 commented on daprdocs/content/en/reference/components-reference/supported-pubsub/setup-pulsar.md
> +Example:
fixed.

2021-11-05 16:22 UTC, willtsai commented on daprdocs/content/en/reference/components-reference/supported-pubsub/setup-pulsar.md
> +Example:
thanks, but please see other suggestions above.

2021-11-05 16:23 UTC, willtsai commented on daprdocs/content/en/reference/components-reference/supported-pubsub/setup-pulsar.md
> +| deliverAfter | N | delay queue configuration param. Default is empty | `"4h5m3s"`|
@1046102779 - here are more suggestions for edits, can you please incorporate these as well if you agree with them?

2021-11-05 16:33 UTC, 1046102779 commented on daprdocs/content/en/reference/components-reference/supported-pubsub/setup-pulsar.md
> +| deliverAfter | N | delay queue configuration param. Default is empty | `"4h5m3s"`|
fixed.

2021-11-05 17:15 UTC, willtsai requested changes

2021-11-05 17:15 UTC, willtsai commented on daprdocs/content/en/reference/components-reference/supported-pubsub/setup-pulsar.md
> +
Please remove this table.

2021-11-10 18:43 UTC, willtsai approved these changes
LGTM - thank you for incorporating my feedback!

2021-11-10 22:35 UTC, greenie-msft approved these changes

2021-11-10 22:35 UTC, merged