Adding instructions to update CRDs prior to upgrading via Helm
dapr/docs pull request #1865
Opened 2021-10-18 22:22 UTC by pkedy

Closes #1864

2021-10-21 20:59 UTC, greenie-msft requested changes
Looks good @pkedy. A few minor changes

2021-10-21 20:59 UTC, greenie-msft commented on daprdocs/content/en/operations/hosting/kubernetes/kubernetes-upgrade.md
> +   ***Note**: The Dapr version is included in the commands below*
```suggestion
> Note: The Dapr version is included in the commands below.
```

2021-10-21 20:59 UTC, greenie-msft commented on daprdocs/content/en/operations/hosting/kubernetes/kubernetes-upgrade.md
> +   *Helm does not handle upgrading CRDs, so you will need to perform that manually. CRDs are backward-compatible and should only be installed forward.*
```suggestion
   *Helm does not handle upgrading CRDs, so you need to perform that manually. CRDs are backward-compatible and should only be installed forward.*
```

2021-10-26 22:36 UTC, greenie-msft approved these changes

2021-10-26 23:13 UTC, orizohar approved these changes

2021-10-26 23:14 UTC, merged