New GA criteria. Rename GA to Stable.
dapr/docs pull request #1880
Opened 2021-10-22 21:19 UTC by artursouza

Thank you for helping make the Dapr documentation better!

**Please follow this checklist before submitting:**

- [ ] [Read the contribution guide](https://docs.dapr.io/contributing/contributing-docs/)
- [ ] Commands include options for Linux, MacOS, and Windows within codetabs
- [ ] New file and folder names are globally unique
- [ ] Page references use shortcodes instead of markdown or URL links
- [ ] Images use HTML style and have alternative text
- [ ] Places where multiple code/command options are given have codetabs

In addition, please fill out the following to help reviewers understand this pull request:

## Description

New GA criteria. Rename GA to Stable.

## Issue reference

#1879

2021-10-22 21:20 UTC, dmitsh approved these changes

2021-10-22 23:55 UTC, greenie-msft approved these changes

2021-10-25 18:34 UTC, dmitsh requested changes
The following files have reference to "GA":
daprdocs/content/en/operations/configuration/configuration-overview.md
daprdocs/content/en/operations/monitoring/tracing/open-telemetry-collector.md

The following files have reference to "certification-lifecycle.md#general-availability-ga" (should be "certification-lifecycle.md#stable"):
daprdocs/content/en/reference/components-reference/supported-bindings/_index.md
daprdocs/content/en/reference/components-reference/supported-name-resolution/_index.md
daprdocs/content/en/reference/components-reference/supported-pubsub/_index.md
daprdocs/content/en/reference/components-reference/supported-secret-stores/_index.md
daprdocs/content/en/reference/components-reference/supported-state-stores/_index.md

2021-10-25 22:54 UTC, greenie-msft requested changes

2021-10-25 22:54 UTC, greenie-msft commented on daprdocs/content/en/operations/components/certification-lifecycle.md
> +- The tests should validate the functional behavior and robustness of component based on the component specification, reflecting the scenarios from the test plan
```suggestion
- The tests should validate the functional behavior and robustness of the component based on the component specification, reflecting the scenarios from the test plan
```

2021-10-25 22:54 UTC, greenie-msft commented on daprdocs/content/en/operations/components/certification-lifecycle.md
> +- A maintainer will address component security, core functionality and test issues according to the Dapr support policy and issue a patch release of Dapr that includes the patched stable component
```suggestion
- A maintainer will address component security, core functionality and test issues according to the Dapr support policy and issue a patch release that includes the patched stable component
```

2021-10-25 22:54 UTC, greenie-msft commented on daprdocs/content/en/operations/components/certification-lifecycle.md
> +Any component that was previously certified as GA is now grandfathered into Stable even if the new requirements are not met yet.
```suggestion
Any component that was previously certified as GA is now grandfathered into Stable even if the new requirements are not met yet.
```
```suggestion
Any component that was previously certified as GA is now grandfathered into Stable even if the new requirements are not met yet.
```
```suggestion
Any component that was previously certified as GA is now grandfathered into Stable even if the new requirements are not met.
```

2021-10-25 22:54 UTC, greenie-msft commented on daprdocs/content/en/operations/components/certification-lifecycle.md
> +- Client reconnection: in case the client library cannot connect to the service for a moment, Dapr sidecar should not require to be restarted once the service is back online.
```suggestion
- Client reconnection: in case the client library cannot connect to the service for a moment, Dapr sidecar should not require a restart once the service is back online.
```

2021-10-25 22:54 UTC, greenie-msft commented on daprdocs/content/en/operations/components/certification-lifecycle.md
> +- The tests must run successfully as part of the continuous integration of `components-contrib` repository
```suggestion
- The tests must run successfully as part of the continuous integration of the `components-contrib` repository
```

2021-10-25 22:54 UTC, greenie-msft commented on daprdocs/content/en/operations/components/certification-lifecycle.md
> +For a component to be certified tests are run in an environment maintained by the Dapr team.
```suggestion
In order for a component to be certified, tests are run in an environment maintained by the Dapr project.
```

2021-10-25 22:54 UTC, greenie-msft commented on daprdocs/content/en/operations/components/certification-lifecycle.md
> +- Requestor creates an issue in `components-contrib` repository for certification of the component with the current and the new certification levels
```suggestion
- Requestor creates an issue in the `components-contrib` repository for certification of the component with the current and the new certification levels
```

2021-10-25 22:54 UTC, greenie-msft commented on daprdocs/content/en/operations/components/certification-lifecycle.md
> +- Requestor submits a PR for integrating the component to run with the defined conformance test suite, if not included already
```suggestion
- Requestor submits a PR to integrate the component with the defined conformance test suite, if not already included
```

2021-10-25 22:54 UTC, greenie-msft commented on daprdocs/content/en/operations/components/certification-lifecycle.md
> +    - The user details the environment setup in the issue created, so that a Dapr maintainer can setup the service in a managed environment
```suggestion
    - The user details the environment setup in the issue created, so a Dapr maintainer can setup the service in a managed environment
```

2021-10-25 22:54 UTC, greenie-msft commented on daprdocs/content/en/operations/components/certification-lifecycle.md
> +- Requestor submits a PR in `docs` repository, updating the component's certification level
```suggestion
- Requestor submits a PR in the `docs` repository, updating the component's certification level
```

2021-10-25 22:54 UTC, greenie-msft commented on daprdocs/content/en/operations/components/certification-lifecycle.md
> +- Requestor creates an issue in `components-contrib` repository for certification of the component with the current and the new certification levels
```suggestion
- Requestor creates an issue in the `components-contrib` repository for certification of the component with the current and the new certification levels
```

2021-10-25 22:54 UTC, greenie-msft commented on daprdocs/content/en/operations/components/certification-lifecycle.md
> +    - A Dapr maintainer reviews the test plan, giving feedback or approving it and merge the PR
```suggestion
    - A Dapr maintainer reviews the test plan, giving feedback or approving it and merges the PR
```

2021-10-25 22:54 UTC, greenie-msft commented on daprdocs/content/en/operations/components/certification-lifecycle.md
> +- Requestor submits a PR in `docs` repository, updating the component's certification level
```suggestion
- Requestor submits a PR in the `docs` repository, updating the component's certification level
```

2021-10-27 03:27 UTC, msfussell commented on daprdocs/content/en/operations/components/certification-lifecycle.md
> +For a component to be certified tests are run in an environment maintained by the Dapr team.
There is no Dapr team i.e. this "by the Dapr team". 

Change to 
"In order for a component to be certified, tests are run in an environment maintained by the Dapr project."

2021-10-27 03:29 UTC, msfussell commented on daprdocs/content/en/operations/components/certification-lifecycle.md
> +- Client reconnection: in case the client library cannot connect to the service for a moment, Dapr sidecar should not require to be restarted once the service is back online.
Note: There is no Dapr team only Dapr project

2021-10-29 21:45 UTC, berndverst commented on daprdocs/content/en/operations/components/certification-lifecycle.md
> +### Previous General Available (GA) components
Either `Generally Available` or `General Availability`

2021-11-02 22:50 UTC, artursouza commented on daprdocs/content/en/operations/components/certification-lifecycle.md
> +### Previous General Available (GA) components
Done.

2021-11-02 22:53 UTC, greenie-msft approved these changes

2021-11-02 23:24 UTC, willtsai requested changes
some minor suggestions and also adding links to referenced repositories

2021-11-02 23:24 UTC, willtsai commented on daprdocs/content/en/operations/components/certification-lifecycle.md
> +Any component that was previously certified as GA is now grandfathered into Stable even if the new requirements are not met.
Adjusting for more inclusive term.

```suggestion
Any component that was previously certified as GA is now allowed into Stable even if the new requirements are not met.
```

2021-11-02 23:24 UTC, willtsai commented on daprdocs/content/en/operations/components/certification-lifecycle.md
> +    - The user details the test environment requirements in the PR created, including any manual steps or credentials needed
```suggestion
    - The requestor details the test environment requirements in the created PR, including any manual steps or credentials needed
```

2021-11-02 23:24 UTC, willtsai commented on daprdocs/content/en/operations/components/certification-lifecycle.md
> +    - A Dapr maintainer reviews the test plan, giving feedback or approving it and merges the PR
```suggestion
    - A Dapr maintainer reviews the test plan, provides feedback or approves it, and eventually merges the PR
```

2021-11-02 23:24 UTC, willtsai commented on daprdocs/content/en/operations/components/certification-lifecycle.md
> +- Requestor submits a PR in the `docs` repository, updating the component's certification level
```suggestion
- Requestor submits a PR in the [docs](https://github.com/dapr/docs) repository, updating the component's certification level
```

2021-11-02 23:24 UTC, willtsai commented on daprdocs/content/en/operations/components/certification-lifecycle.md
> +- The tests must run successfully as part of the continuous integration of the `components-contrib` repository
```suggestion
- The tests must run successfully as part of the continuous integration of the [components-contrib](https://github.com/dapr/components-contrib) repository
```

2021-11-02 23:24 UTC, willtsai commented on daprdocs/content/en/operations/components/certification-lifecycle.md
> +- Requestor creates an issue in the `components-contrib` repository for certification of the component with the current and the new certification levels
```suggestion
- Requestor creates an issue in the [components-contrib](https://github.com/dapr/components-contrib) repository for certification of the component with the current and the new certification levels
```

2021-11-02 23:24 UTC, willtsai commented on daprdocs/content/en/operations/components/certification-lifecycle.md
> +- Requestor creates an issue in the `components-contrib` repository for certification of the component with the current and the new certification levels
```suggestion
- Requestor creates an issue in the [components-contrib](https://github.com/dapr/components-contrib) repository for certification of the component with the current and the new certification levels
```

2021-11-02 23:24 UTC, willtsai commented on daprdocs/content/en/operations/components/certification-lifecycle.md
> +- Requestor submits a PR in the `docs` repository, updating the component's certification level
```suggestion
- Requestor submits a PR in the [docs](https://github.com/dapr/docs) repository, updating the component's certification level
```

2021-11-03 01:36 UTC, willtsai approved these changes
LGTM, thanks for incorporating my suggestions

2021-11-03 01:39 UTC, merged