feature/middleware: add routerchecker middleware
dapr/docs pull request #1893
Opened 2021-10-30 00:01 UTC by 1046102779

Thank you for helping make the Dapr documentation better!

**Please follow this checklist before submitting:**

- [ ] [Read the contribution guide](https://docs.dapr.io/contributing/contributing-docs/)
- [ ] Commands include options for Linux, MacOS, and Windows within codetabs
- [ ] New file and folder names are globally unique
- [ ] Page references use shortcodes instead of markdown or URL links
- [ ] Images use HTML style and have alternative text
- [ ] Places where multiple code/command options are given have codetabs

In addition, please fill out the following to help reviewers understand this pull request:

## Description

## Issue reference

2021-10-30 00:02 UTC, 1046102779 commented
https://github.com/dapr/components-contrib/pull/1155

2021-11-19 01:11 UTC, willtsai requested changes
@1046102779 - added some inline suggestions. Please also change the base branch for this PR to v1.6 as that is the target branch for this feature. Thanks!

2021-11-19 01:11 UTC, willtsai commented on daprdocs/content/en/reference/components-reference/supported-middleware/_index.md
> +| [RouterChecker]({{< ref middleware-routerchecker.md >}})                               | Check the legitimacy of http request routing by regexp
I believe this should be in the `Alpha` stage given the `apiVersion: dapr.io/v1alpha1` specified?

```suggestion
| [RouterChecker]({{< ref middleware-routerchecker.md >}})                               | Validates HTTP requests using regexp and filters out invalid requests                                                                        | Alpha | v1|
```

2021-11-19 01:11 UTC, willtsai commented on daprdocs/content/en/reference/components-reference/supported-middleware/middleware-routerchecker.md
> +The routerchecker [HTTP middleware]({{< ref middleware.md >}}) checks the legitimacy of http request routing, that prevents illegal routers from entering dapr cluster, and at the same time prevents a
```suggestion
The RouterChecker HTTP [middleware]({{< ref middleware.md >}}) component leverages regexp to check the validity of HTTP request routing to prevent invalid routers from entering the Dapr cluster. In turn, filtering out bad requests reduces noise in the telemetry and logs data.
```

2021-11-19 01:11 UTC, willtsai commented on daprdocs/content/en/reference/components-reference/supported-middleware/middleware-routerchecker.md
> +In the following definition,  the http request router is set to  `^[A-Za-z0-9/._-]+$`.
```suggestion
In the following definition,  the HTTP request RouterChecker is set to validate against `^[A-Za-z0-9/._-]+$`:
```

2021-11-19 01:11 UTC, willtsai commented on daprdocs/content/en/reference/components-reference/supported-middleware/middleware-routerchecker.md
> +For example:
```suggestion
As an example, the above definition would result in the following PASS/FAIL cases:
```

2021-11-19 01:11 UTC, willtsai commented on daprdocs/content/en/reference/components-reference/supported-middleware/middleware-routerchecker.md
> +| rule | http request routing regexp | `^[A-Za-z0-9/._-]+$`|
```suggestion
| rule | the regexp expression to be used by the HTTP request RouterChecker | `^[A-Za-z0-9/._-]+$`|
```

2021-12-02 00:05 UTC, closed without merging