Provide consistent examples of pub-sub for all SDKs
dapr/docs pull request #2018
Opened 2021-12-02 10:46 UTC by amulyavarote

Thank you for helping make the Dapr documentation better!

**Please follow this checklist before submitting:**

- [ ] [Read the contribution guide](https://docs.dapr.io/contributing/contributing-docs/)
- [ ] Commands include options for Linux, MacOS, and Windows within codetabs
- [ ] New file and folder names are globally unique
- [ ] Page references use shortcodes instead of markdown or URL links
- [ ] Images use HTML style and have alternative text
- [ ] Places where multiple code/command options are given have codetabs

In addition, please fill out the following to help reviewers understand this pull request:

## Description

Modified pub sub documentation page (under building blocks) for dapr.io

## Issue reference

This partially fulfills: #1969

2021-12-02 18:17 UTC, greenie-msft commented on daprdocs/content/en/developing-applications/building-blocks/pubsub/howto-publish-subscribe.md
> +The below code examples loosely describes an application that processes orders. In the examples, there are two services - an order processing service and a checkout service. Both services have Dapr s
```suggestion
The below code examples loosely describes an application that processes orders. In the examples, there are two services - an order processing service and a checkout service. Both services have Dapr sidecars. The order processing service uses Dapr to publish a message and the checkout service subscribes to the message in Rabbit mq.
```

2021-12-02 18:19 UTC, greenie-msft commented on daprdocs/content/en/developing-applications/building-blocks/pubsub/howto-publish-subscribe.md
> +In this example, rabbit mq is used for publish and subscribe. Replace pubsub.yaml file contents with the below contents.
```suggestion
In this example, Rabbit MQ is used for publish and subscribe. Replace pubsub.yaml file contents with the below contents.
```

2021-12-02 22:04 UTC, greenie-msft commented on daprdocs/content/en/developing-applications/building-blocks/pubsub/howto-publish-subscribe.md
> +The below code examples loosely describes an application that processes orders. In the examples, there are two services - an order processing service and a checkout service. Both services have Dapr s
```suggestion
The below code example loosely describes an application that processes orders. In the example, there are two services - an order processing service and a checkout service. Both services have Dapr sidecars. The order processing service uses Dapr to publish a message to RabbitMQ and the checkout service subscribes to the topic.
```

2021-12-02 22:05 UTC, greenie-msft commented on daprdocs/content/en/developing-applications/building-blocks/pubsub/howto-publish-subscribe.md
> +pubsub.yaml is created by default on a local machine when running `dapr init`. Verify by opening your components file under `%UserProfile%\.dapr\components\pubsub.yaml` on Windows or `~/.dapr/compone
```suggestion
The pubsub.yaml is created by default on your local machine when running `dapr init`. Verify by opening your components file under `%UserProfile%\.dapr\components\pubsub.yaml` on Windows or `~/.dapr/components/pubsub.yaml` on Linux/MacOS.
```

2021-12-03 19:02 UTC, willtsai requested changes

2021-12-03 19:02 UTC, willtsai commented on daprdocs/content/en/developing-applications/building-blocks/pubsub/howto-publish-subscribe.md
> +<img src="/images/building-block-pub-sub-example.png" width=1000 alt="Diagram showing state management of example service">
@greenie-msft pointed this out to me when we viewed the rendered page - there is a grey line on the right hand side of the picture that needs to be cropped out.

2021-12-03 19:02 UTC, willtsai commented on daprdocs/content/en/developing-applications/building-blocks/pubsub/howto-publish-subscribe.md
> +In this example, RabbitMQ is used for publish and subscribe. Replace pubsub.yaml file contents with the below contents.
nitpick:
```suggestion
In this example, RabbitMQ is used for publish and subscribe. Replace `pubsub.yaml` file contents with the below contents.
```

2021-12-03 19:02 UTC, willtsai commented on daprdocs/content/en/developing-applications/building-blocks/pubsub/howto-publish-subscribe.md
> +In order to tell Dapr that a message was processed successfully, return a `200 OK` response. If Dapr receives any other return status code than `200`, or if your app crashes, Dapr will attempt to red
```suggestion
In order to tell Dapr that a message was processed successfully, return a `200 OK` response. If Dapr receives any other return status code than `200`, or if your app crashes, Dapr will attempt to redeliver the message following at-least-once semantics.
```

2021-12-03 19:33 UTC, amulyavarote commented on daprdocs/content/en/developing-applications/building-blocks/pubsub/howto-publish-subscribe.md
> +<img src="/images/building-block-pub-sub-example.png" width=1000 alt="Diagram showing state management of example service">
I removed it.

2021-12-03 20:02 UTC, willtsai approved these changes

2021-12-03 21:35 UTC, greenie-msft approved these changes

2021-12-03 21:35 UTC, merged