add docs for querying Redis state store
dapr/docs pull request #2216
Opened 2022-02-26 00:19 UTC by dmitsh

Thank you for helping make the Dapr documentation better!

**Please follow this checklist before submitting:**
- [x] Commits are signed with Developer Certificate of Origin (DCO - [learn more](https://docs.dapr.io/contributing/contributing-overview/#developer-certificate-of-origin-signing-your-work))
- [x] [Read the contribution guide](https://docs.dapr.io/contributing/contributing-docs/)
- [ ] Commands include options for Linux, MacOS, and Windows within codetabs
- [ ] New file and folder names are globally unique
- [x] Page references use shortcodes instead of markdown or URL links
- [ ] Images use HTML style and have alternative text
- [ ] Places where multiple code/command options are given have codetabs

In addition, please fill out the following to help reviewers understand this pull request:

## Description

add docs for querying Redis state store

## Issue reference

#2187

2022-03-01 00:37 UTC, msfussell commented on daprdocs/content/en/reference/api/state_api.md
> +## Query State
Headings are lower case for following words
```suggestion
## Query state
```

2022-03-01 01:40 UTC, msfussell commented
@dmitsh - It is important here to help people understand how they can set up Redis correctly for querying with some common Redis stores and hence update https://docs.dapr.io/reference/components-reference/supported-state-stores/setup-redis/#setup-redis section

- For Selfhosted what Redis CLI commands can you run to deploy these the Redis modules yourself after Dapr init. Being able to easily do this locally is a great example. Please add the commands here.
-  Same for K8s, Redis CLI commands
- Under Azure can you put a note" Note: Azure currently [does not support the RedisJson](https://docs.microsoft.com/en-us/answers/questions/333933/does-azure-cache-for-redis-support-any-of-the-redi.html) module and cannot be used with query.
-  Under AWS can you put - "Note: For query support you need to enable RediSearch and RedisJson."
-  Under GCP can you put a note" Note: Memory Store does not modules and cannot be used with query."
- Can you also add new Tab for Redis Enterprise Cloud with this link https://docs.redis.com/latest/rc/ as another option. 
- Can you also add new Tab Alibaba Cloud with this link https://www.alibabacloud.com/product/apsaradb-for-redis as another option

2022-03-01 01:56 UTC, msfussell requested changes

2022-03-01 01:56 UTC, msfussell commented on daprdocs/content/en/reference/components-reference/supported-state-stores/setup-redis.md
> +| queryIndexes       | N         | Query indexing schemas for querying JSON objects |
Can you provide an example here in the last column

2022-03-01 01:56 UTC, msfussell commented on daprdocs/content/en/reference/components-reference/supported-state-stores/setup-redis.md
> +Redis state store supports querying JSON objects. To enable this feature, the following steps are required:
```suggestion
The Redis state store supports querying of JSON objects. To enable this feature, the following steps are required:
```

2022-03-01 01:56 UTC, msfussell commented on daprdocs/content/en/reference/components-reference/supported-state-stores/setup-redis.md
> +1. Load [redisearch](https://oss.redis.com/redisearch/) and [rejson](https://oss.redis.com/redisjson/) modules when deploying redis service.
```suggestion
1. The Redis store must support Redis modules and specifically both Redisearch and RedisJson. If you are deploying and running Redis then load [redisearch](https://oss.redis.com/redisearch/) and [redisjson](https://oss.redis.com/redisjson/) modules when deploying the Redis service.
``

2022-03-01 02:08 UTC, msfussell commented
I would like to make sure that this and the query API topic https://docs.dapr.io/developing-applications/building-blocks/state-management/howto-state-query-api/ article are better aligned. Could you show the Redis queries using the employees dataset (have a link to this in this Redis component topic) and using query from Example 1, In other words, this

curl -X POST http://localhost:3500/v1.0/state/statestore/query?metadata.contentType=application/json&metadata.queryIndexName=orgIndx -d @query-api-examples/query1.json -H "Content-Type: application/json

Can you also add a link in the "Related Links" section to this Redis Component Query section? 
[Query Redis State Store](link)

2022-03-02 05:04 UTC, msfussell commented
These changes look great! Would still like to address what Redis service can be used due to the Redis Modules dependency.
These ones.

> * Under Azure can you put a note" Note: Azure currently [does not support the RedisJson](https://docs.microsoft.com/en-us/answers/questions/333933/does-azure-cache-for-redis-support-any-of-the-redi.html) module and cannot be used with query.
> * Under AWS can you put - "Note: For query support you need to enable RediSearch and RedisJson."
> * Under GCP can you put a note" Note: Memory Store does not modules and cannot be used with query."
> * Can you also add new Tab for Redis Enterprise Cloud with this link https://docs.redis.com/latest/rc/ as another option.
> * Can you also add new Tab Alibaba Cloud with this link https://www.alibabacloud.com/product/apsaradb-for-redis as another option

2022-03-02 05:12 UTC, dmitsh commented
> These changes look great! Would still like to address what Redis service can be used due to the Redis Modules dependency. These ones.
> 
> > * Under Azure can you put a note" Note: Azure currently [does not support the RedisJson](https://docs.microsoft.com/en-us/answers/questions/333933/does-azure-cache-for-redis-support-any-of-the-redi.html) module and cannot be used with query.
> > * Under AWS can you put - "Note: For query support you need to enable RediSearch and RedisJson."
> > * Under GCP can you put a note" Note: Memory Store does not modules and cannot be used with query."
> > * Can you also add new Tab for Redis Enterprise Cloud with this link https://docs.redis.com/latest/rc/ as another option.
> > * Can you also add new Tab Alibaba Cloud with this link https://www.alibabacloud.com/product/apsaradb-for-redis as another option

I would prefer not to mention that in the doc because:
 - things can change, and this information may become inaccurate
 - you can still deploy Redis with modules in Azure, for example. I did that in e2e tests with AKS

2022-03-02 22:34 UTC, msfussell commented
Let's at least then be inclusive of other Redis hosted services and add tabs to reference Redis Cloud and Alibaba Cloud

> * Can you also add new Tab for Redis Enterprise Cloud with this link https://docs.redis.com/latest/rc/ 
> * Can you also add new Tab Alibaba Cloud with this link https://www.alibabacloud.com/product/apsaradb-for-redis

2022-03-03 05:29 UTC, msfussell approved these changes
Fantastic!

2022-03-03 05:30 UTC, merged