Improving the Security concepts overviews
dapr/docs pull request #2224
Opened 2022-03-03 06:25 UTC by msfussell

This PR address the following issues
- https://github.com/dapr/docs/issues/1832
- https://github.com/dapr/docs/issues/2088
- https://github.com/dapr/docs/issues/1927

It also reworks the overall structure of the security concepts overview, adding new diagrams and providing a comprehensive set of links to all the security features in Dapr, organized under different headings.

2022-03-03 19:20 UTC, greenie-msft commented on daprdocs/content/en/developing-applications/building-blocks/service-invocation/service-invocation-namespaces.md
> +This article describes how you can call between services deployed to different namespaces. By default, you can invoke services within the *same* namespaces by simply referencing the app ID (`nodeapp`
```suggestion
This article describes how you can call between services deployed to different namespaces. By default, you can invoke services within the *same* namespace by simply referencing the app ID (`nodeapp`):
```

2022-03-03 19:20 UTC, greenie-msft commented on daprdocs/content/en/developing-applications/building-blocks/service-invocation/service-invocation-namespaces.md
> +Service invocation also supports calls across namespaces. On all supported hosting platforms, Dapr app IDs conform to a valid FQDN format that includes the target namespace. You can therefore specify
```suggestion
Service invocation also supports calls across namespaces. On all supported hosting platforms, Dapr app IDs conform to a valid FQDN format that includes the target namespace. You can therefore specify both the app ID (`nodeapp`) in addition to the namespace the app runs in (`production`). For example to call the `neworder` method on the `nodeapp`, in the `production` namespace would look like this:
```

2022-03-03 19:21 UTC, greenie-msft commented on daprdocs/content/en/developing-applications/building-blocks/service-invocation/service-invocation-namespaces.md
> +When using service invocation to call an application in a namespace you  qualify it with the namespace. This is especially useful in cross namespace calls in a Kubernetes cluster. As another example,
```suggestion
When using service invocation to call an application in a namespace you qualify it with the namespace. This is especially useful in cross namespace calls in a Kubernetes cluster. As another example, calling the `ping` method on `myapp` which is scoped to the `production` namespace would look like this:
```

2022-03-03 19:22 UTC, greenie-msft commented on daprdocs/content/en/developing-applications/building-blocks/service-invocation/service-invocation-namespaces.md
> +And calling the same `ping` method using a curl command from an external DNS address, in this case `api.demo.dapr.team` and supplying the Dapr API token for authentication would be like this;
```suggestion
And calling the same `ping` method using a curl command from an external DNS address, in this case `api.demo.dapr.team` and supplying the Dapr API token for authentication would look like this:
```

2022-03-03 21:54 UTC, hhunter-ms requested changes
grammar/style pass

2022-03-03 21:54 UTC, hhunter-ms commented on daprdocs/content/en/developing-applications/building-blocks/service-invocation/service-invocation-namespaces.md
> +This article describes how you can call between services deployed to different namespaces. By default, you can invoke services within the *same* namespaces by simply referencing the app ID (`nodeapp`
```suggestion
In this article, you'll learn how you can call between services deployed to different namespaces. By default, service invocation supports invoking services within the *same* namespace by simply referencing the app ID (`nodeapp`):
```

2022-03-03 21:54 UTC, hhunter-ms commented on daprdocs/content/en/developing-applications/building-blocks/service-invocation/service-invocation-namespaces.md
> +Service invocation also supports calls across namespaces. On all supported hosting platforms, Dapr app IDs conform to a valid FQDN format that includes the target namespace. You can therefore specify
```suggestion
Service invocation also supports calls across namespaces. On all supported hosting platforms, Dapr app IDs conform to a valid FQDN format that includes the target namespace. You can specify both:

- The app ID (`nodeapp`), and
- The namespace the app runs in (`production`). 

**Example 1**

Call the `neworder` method on the `nodeapp` in the `production` namespace:
```

2022-03-03 21:54 UTC, hhunter-ms commented on daprdocs/content/en/developing-applications/building-blocks/service-invocation/service-invocation-namespaces.md
> +When using service invocation to call an application in a namespace you  qualify it with the namespace. This is especially useful in cross namespace calls in a Kubernetes cluster. As another example,
```suggestion
When calling an application in a namespace using service invocation, you qualify it with the namespace. This proves useful in cross-namespace calls in a Kubernetes cluster.

**Example 2**

Call the `ping` method on `myapp` scoped to the `production` namespace:
```

2022-03-03 21:54 UTC, hhunter-ms commented on daprdocs/content/en/developing-applications/building-blocks/service-invocation/service-invocation-namespaces.md
> +And calling the same `ping` method using a curl command from an external DNS address, in this case `api.demo.dapr.team` and supplying the Dapr API token for authentication would be like this;
```suggestion
**Example 3**

Call the same `ping` method as example 2 using a curl command from an external DNS address (in this case, `api.demo.dapr.team`) and supply the Dapr API token for authentication:
```

2022-03-03 21:54 UTC, hhunter-ms commented on daprdocs/content/en/developing-applications/building-blocks/service-invocation/service-invocation-overview.md
> +Applications can be scoped to namespaces for deployment and security and you can call between services deployed to different namespaces. For more information read the [Service invocation across names
```suggestion
Applications can be scoped to namespaces for deployment and security, and you can call between services deployed to different namespaces. For more information, read the [Service invocation across namespaces]({{< ref "service-invocation-namespaces.md" >}}) article.
```

2022-03-03 21:54 UTC, hhunter-ms commented on daprdocs/content/en/operations/components/component-scopes.md
> +Note: It is possible to have the component YAML applied to namespace "A" *reference* the implementation in namespace "B". For example, a component YAML for Redis in namespace "production-A" can set t
```suggestion
{{% alert title="Note" color="primary" %}}
The component YAML applied to namespace "A" can *reference* the implementation in namespace "B". For example, a component YAML for Redis in namespace "production-A" can point the Redis host address to the Redis instance deployed in namespace "production-B". 

See [Configure Pub/Sub components with multiple namespaces]({{< ref "pubsub-namespaces.md" >}}) for an example.
{{% /alert %}}
```

2022-03-03 21:54 UTC, hhunter-ms commented on daprdocs/content/en/operations/components/component-scopes.md
>  To achieve this, Dapr allows you to specify `scopes` on the component YAML. Application scopes added to a component limit only the applications with specific IDs to be able to use the component.
```suggestion
To achieve this, Dapr allows you to specify `scopes` on the component YAML. Application scopes added to a component limit only the applications with specific IDs from using the component.
```

2022-03-03 21:54 UTC, hhunter-ms commented on daprdocs/content/en/operations/components/component-scopes.md
>  Developers and operators might want to limit access for one database to a certain application, or a specific set of applications.
```suggestion
Developers and operators might want to limit access to one database from a certain application, or a specific set of applications.
```

2022-03-04 01:27 UTC, greenie-msft approved these changes

2022-03-04 02:03 UTC, merged