Removed documentation for preview features - Actor Reentrancy and State Encryption
dapr/docs pull request #2232
Opened 2022-03-04 18:23 UTC by amulyavarote

Signed-off-by: Amulya Varote <amulyavarote@Amulyas-MacBook-Pro.local>

Thank you for helping make the Dapr documentation better!

**Please follow this checklist before submitting:**
- [ ] Commits are signed with Developer Certificate of Origin (DCO - [learn more](https://docs.dapr.io/contributing/contributing-overview/#developer-certificate-of-origin-signing-your-work))
- [ ] [Read the contribution guide](https://docs.dapr.io/contributing/contributing-docs/)
- [ ] Commands include options for Linux, MacOS, and Windows within codetabs
- [ ] New file and folder names are globally unique
- [ ] Page references use shortcodes instead of markdown or URL links
- [ ] Images use HTML style and have alternative text
- [ ] Places where multiple code/command options are given have codetabs

In addition, please fill out the following to help reviewers understand this pull request:

## Description

## Issue reference

https://github.com/dapr/dapr/issues/4260
https://github.com/dapr/dapr/issues/3811

2022-03-04 18:33 UTC, halspang requested changes
Please also remove them from here: https://docs.dapr.io/operations/support/support-preview-features/

2022-03-04 18:33 UTC, halspang commented on daprdocs/content/en/developing-applications/building-blocks/actors/actor-reentrancy.md
>  ### Actor runtime configuration
Instead of having a header with just the one line in it, I'd have just one header like `Enable Actor Reentrancy with Actor Configuration`.

2022-03-04 20:57 UTC, msfussell commented
Quite a few more changes needed here across the docs at @halspang  please verify

1) Update the Actor "Get Registered Actors" API docs https://docs.dapr.io/reference/api/actors_api/#get-registered-actors to reflect the changes in the actor settings structure describe here https://github.com/dapr/dapr/issues/2901#issuecomment-845437926

2) We should explain and show how to set the "maxStackDepth": 32 setting in the docs

3) At the end add a link to this video https://youtu.be/QADHQ5v-gww?list=PLcip_LgkYwzuF-OV6zKRADoiBvUvGhkao&t=674
Copy this .MD snippet

>>>
## Community call video on actor reentrancy
Watch this video on how to use actor reentrancy

<iframe width="1280" height="720" src="https://youtu.be/QADHQ5v-gww?list=PLcip_LgkYwzuF-OV6zKRADoiBvUvGhkao&t=674" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>
>>>

4) Let's transcribe the words from video on the practical example of reentrancy. I will draw a better diagram of this for you and provide the scenario example. 
![image](https://user-images.githubusercontent.com/11199644/156840261-2c16d354-6422-4c46-9b2b-ed192f8be12e.png)

5) Can we add at least one other language to the example, other than just Go. Java or .NET

6) This is no longer true "Currently, no SDK supports actor reentrancy. In the future, the method for handling the reentrancy id may be different based on the SDK that is being used." Since the .NET SDK supports this. See https://github.com/dapr/dotnet-sdk/commit/16321d3cb70f20d449b7e3cc5a828bb4d64e4e78. 

I suggest explaining the consequence of this, which (correct me here Hal) means that I do not have to copy the reentrancy header ID. It is important to say here what (if any) are the responsibilities of the developer when using an SDK, which I presume to be none. If so, then this makes the coding example for .NET above not required, but we should say which SDKs now support reentrancy.

2022-03-04 21:07 UTC, msfussell commented
On the encrypted state store article, please add these links back in at the end

## Related links
 - [Security overview]({{< ref "security-concept.md" >}})
 - [State store components]({{< ref "supported-state-stores.md" >}})

2022-03-17 21:52 UTC, msfussell commented on daprdocs/content/en/developing-applications/building-blocks/actors/actor-reentrancy.md
>  A core tenet of the virtual actor pattern is the single-threaded nature of actor execution. Before reentrancy, this caused the Dapr runtime to lock an actor on any given request. A second request cou
```suggestion
A core tenet of the virtual actor pattern is the single-threaded nature of actor execution. Without reentrancy, the the Dapr runtime locks on all actor requests, even those that are in the same call chain. A second request could not start until the first had completed. This means an actor cannot call itself, or have another actor call into it even if it is part of the same chain. Reentrancy solves this by allowing requests from the same chain, or context, to re-enter into an already locked actor. This is especially useful in scenarios where an actor wants to call a method on itself or when actors are used in workflows where other actors are used to perform work, and they then call back onto the coordinating actor. Examples of chains that reentrancy allows can be seen below:
```

2022-03-17 21:53 UTC, msfussell commented on daprdocs/content/en/developing-applications/building-blocks/actors/actor-reentrancy.md
> +The `maxStackDepth` parameter gets a value that controls how many reentrant calls be made to the same actor.
```suggestion
The `maxStackDepth` parameter sets a value that controls how many reentrant calls be made to the same actor. By default this is set to 32, which is more than sufficient in most cases. 
```

2022-03-18 00:09 UTC, msfussell commented on daprdocs/content/en/developing-applications/building-blocks/actors/actor-reentrancy.md
> +The actor that will be reentrant must provide the appropriate configuration to use reentrancy. This is done by the actor's endpoint for `GET /dapr/config`, similar to other actor configuration elemen
```suggestion
The actor that will be reentrant must provide configuration to use reentrancy. This is done by the actor's endpoint for `GET /dapr/config`, similar to other actor configuration elements. 
```

2022-03-18 00:11 UTC, msfussell commented on daprdocs/content/en/developing-applications/building-blocks/actors/actor-reentrancy.md
>  type daprConfig struct {
```suggestion
Here is a snippet of an actor written in Golang providing the reentrancy configuration via the HTTP API. Reentrancy has not yet been included into the Go SDK.

type daprConfig struct {
```

2022-03-18 00:14 UTC, msfussell commented on daprdocs/content/en/developing-applications/building-blocks/actors/actor-reentrancy.md
> +{{< tabs Go Dotnet Python JavaScript >}}
```suggestion
{{< tabs Dotnet Java Python Go JavaScript >}}
```
Put the code into this order please and also add a blank entry for Java, with a sentence saying "Reentrancy has not yet been included into the Java SDK"

2022-03-18 00:22 UTC, msfussell commented on daprdocs/content/en/reference/api/actors_api.md
> +reentrancy | A configuration object that holds the options for Actor Reentrancy
```suggestion
reentrancy | A configuration object that holds the options for actor reentrancy
```

2022-03-18 00:30 UTC, msfussell commented on daprdocs/content/en/reference/api/actors_api.md
> +enabled | A flag that is needed to enable the reentrancy.
```suggestion
enabled | A flag in the reentrancy configuration that is needed to enable reentrancy.
```

2022-03-18 00:31 UTC, msfussell commented on daprdocs/content/en/reference/api/actors_api.md
> +maxStackDepth | A value that controls how many reentrant calls be made to the same actor.
```suggestion
maxStackDepth | A value in the reentrancy configuration that controls how many reentrant calls be made to the same actor.
```

2022-03-18 22:15 UTC, msfussell commented
could you add this diagram into the docs. 
![actors_reentrancy](https://user-images.githubusercontent.com/11199644/159091438-4229fc5d-7ae0-45f0-a9ac-272a3d2b7492.png)

<img src="/images/actors-reentrancy.png" width=1000 height=500 alt="Diagram showing reentrancy for a coordinator workflow actor calling worker actors or an actor calling an method on itself">

Put this after the text at the start of article

2022-03-22 02:55 UTC, msfussell commented on daprdocs/content/en/developing-applications/building-blocks/actors/actor-reentrancy.md
> +A core tenet of the virtual actor pattern is the single-threaded nature of actor execution. Without reentrancy, the the Dapr runtime locks on all actor requests, even those that are in the same call
```suggestion
A core tenet of the virtual actor pattern is the single-threaded nature of actor execution. Without reentrancy, the Dapr runtime locks on all actor requests, even those that are in the same call chain. A second request could not start until the first had completed. This means an actor cannot call itself, or have another actor call into it even if it is part of the same chain. Reentrancy solves this by allowing requests from the same chain, or context, to re-enter into an already locked actor. This is especially useful in scenarios where an actor wants to call a method on itself or when actors are used in workflows where other actors are used to perform work, and they then call back onto the coordinating actor. Examples of chains that reentrancy allows are shown below:
```

2022-03-22 03:02 UTC, msfussell commented on daprdocs/content/en/developing-applications/building-blocks/actors/actor-reentrancy.md
> +A core tenet of the virtual actor pattern is the single-threaded nature of actor execution. Without reentrancy, the the Dapr runtime locks on all actor requests, even those that are in the same call
@amulyavarote - Looks good. One small typo above.

2022-03-22 05:20 UTC, msfussell approved these changes
LGTM

2022-03-22 18:26 UTC, greenie-msft approved these changes

2022-03-22 18:26 UTC, merged