Add state management quickstart
dapr/docs pull request #2320
Opened 2022-04-01 16:52 UTC by nirmash

Thank you for helping make the Dapr documentation better!

**Please follow this checklist before submitting:**
- [ ] Commits are signed with Developer Certificate of Origin (DCO - [learn more](https://docs.dapr.io/contributing/contributing-overview/#developer-certificate-of-origin-signing-your-work))
- [ ] [Read the contribution guide](https://docs.dapr.io/contributing/contributing-docs/)
- [ ] Commands include options for Linux, MacOS, and Windows within codetabs
- [ ] New file and folder names are globally unique
- [ ] Page references use shortcodes instead of markdown or URL links
- [ ] Images use HTML style and have alternative text
- [ ] Places where multiple code/command options are given have codetabs

In addition, please fill out the following to help reviewers understand this pull request:

## Description

## Issue reference

2022-04-01 17:06 UTC, paulyuk commented
Wow, thank you for this contribution @nirmash !!  I'm adding @greenie-msft, @amulyavarote  and @hhunter-ms to review.

2022-04-01 17:07 UTC, paulyuk requested changes, later dismissed
One quick thing I see is the tests/checks are failing on docker.com/*.  I see that oftentimes with rate limiting, because so many tests run anonymously on github and they get rate limited.

There are a couple solutions.
- mitigate temporarily by removing the links
- work with @amulyavarote to make sure this check is first doing a docker login so we're no longer anonymous

2022-04-01 17:11 UTC, paulyuk reviewed
Just a few comments but LGTM

2022-04-01 17:11 UTC, paulyuk commented on daprdocs/content/en/getting-started/quickstarts/statemanagement-quickstart.md
> +git clone https://github.com/dapr/quickstarts.git
One small ask.  Can we add a note under here or on line 33 with a link pointing to the github repo itself?  I think it's inconvenient that all of our quickstarts only let you see code if you first clone it.

2022-04-01 17:25 UTC, hhunter-ms commented on daprdocs/content/en/getting-started/quickstarts/statemanagement-quickstart.md
> +Dapr provides state management capabilities that include consistency and concurrency options. In this guide we’ll start of with the basics: Using the key/value state API to allow an application to sa
```suggestion
Dapr provides state management capabilities that include consistency and concurrency options. In this quickstart, you'll use the basic key/value state API to allow an application to save, get, and delete state. 
```

2022-04-01 17:35 UTC, amulyavarote commented
Hi! Thanks for the contribution. We already have README files in the respective folders. I want to understand how different is this README file?

2022-04-01 17:39 UTC, hhunter-ms commented on daprdocs/content/en/getting-started/quickstarts/statemanagement-quickstart.md
> +Let's take a look at Dapr's [State Management building block]({{< ref state-management >}}). In this quickstart, you will learn how to store and query data as key/value pairs in the [supported state
```suggestion
Let's take a look at Dapr's [State Management building block]({{< ref state-management >}}).  You can use Dapr's state management consistency and concurrency capabilities to:
* Maintain and test different databases and libraries.
* Handle retries and faults.
```

2022-04-01 17:39 UTC, hhunter-ms commented on daprdocs/content/en/getting-started/quickstarts/statemanagement-quickstart.md
> +State management is one of the most common needs of any application: new or legacy, monolith or microservice. Dealing with different databases libraries, testing them, handling retries and faults can
```suggestion

```

2022-04-01 17:39 UTC, hhunter-ms commented on daprdocs/content/en/getting-started/quickstarts/statemanagement-quickstart.md
> +Dapr provides state management capabilities that include consistency and concurrency options. In this guide we’ll start of with the basics: Using the key/value state API to allow an application to sa
```suggestion
In this quickstart, you use the key/value pairs in the [supported state stores]({{< ref supported-state-stores.md >}}) and allow an application to save, get, and delete state.
```

2022-04-01 17:40 UTC, hhunter-ms commented on daprdocs/content/en/getting-started/quickstarts/statemanagement-quickstart.md
> +Clone the sample we've provided.
```suggestion
Clone the [sample we've provided in our quickstarts repo](https://github.com/dapr/quickstarts/tree/master/state_management).
```

2022-04-01 17:45 UTC, hhunter-ms commented on daprdocs/content/en/getting-started/quickstarts/statemanagement-quickstart.md
> +In the `order-processor` service, we're writing, reading and deleting an orderId key \ value pair to the Redis instance called `statestore` [(as defined in the `statestore.yaml` component)]({{< ref "
```suggestion
The `order-processor` service writes, reads, and deletes an `orderId` key\value pair to the `statestore` instance [defined in the `statestore.yaml` component]({{< ref "#statestoreyaml-component-file" >}}). As soon as the service starts, it performs a loop:
```

2022-04-01 17:47 UTC, hhunter-ms commented on daprdocs/content/en/getting-started/quickstarts/statemanagement-quickstart.md
> +Notice, as specified in the code above, the code saves application state in the Dapr stat store, reads it and then deletes it.
```suggestion
Notice, as specified in the code above, the `order-processor` service saves, receives, and deletes a numbered message to the Dapr state store.
```

2022-04-01 18:18 UTC, amulyavarote approved these changes

2022-04-01 18:19 UTC, amulyavarote requested changes
Please fix the validation errors and the PR comments

2022-04-06 14:28 UTC, hhunter-ms requested changes
As mentioned earlier, add changes from the Python section to the rest of the languages for consistency.

2022-04-06 14:28 UTC, hhunter-ms commented on daprdocs/content/en/getting-started/quickstarts/statemanagement-quickstart.md
> +Clone the sample we've set up:
```suggestion
Clone the [sample we've provided in our quickstarts repo](https://github.com/dapr/quickstarts/tree/master/state_management).
```

2022-04-06 14:28 UTC, hhunter-ms commented on daprdocs/content/en/getting-started/quickstarts/statemanagement-quickstart.md
> +In the `order-processor` service, we're writing, reading and deleting an orderId key \ value pair to the Redis instance called `statestore` [(as defined in the `statestore.yaml` component)]({{< ref "
```suggestion
The `order-processor` service writes, reads, and deletes an `orderId` key\value pair to the `statestore` instance [defined in the `statestore.yaml` component]({{< ref "#statestoreyaml-component-file" >}}). As soon as the service starts, it performs a loop:
```

2022-04-06 14:28 UTC, hhunter-ms commented on daprdocs/content/en/getting-started/quickstarts/statemanagement-quickstart.md
> +Notice, as specified in the code above, the code saves application state in the Dapr state store, reads it, then deletes it.
```suggestion
Notice, as specified in the code above, the code saves application state in the Dapr state store, reads it, then deletes it.
```

2022-04-06 14:28 UTC, hhunter-ms commented on daprdocs/content/en/getting-started/quickstarts/statemanagement-quickstart.md
> +Notice, as specified in the code above, the code saves application state in the Dapr stat store, reads it and then deletes it.
```suggestion
Notice, as specified in the code above, the code saves application state in the Dapr state store, reads it, then deletes it.
```

2022-04-06 14:28 UTC, hhunter-ms commented on daprdocs/content/en/getting-started/quickstarts/statemanagement-quickstart.md
> +Notice, as specified in the code above, the code saves application state in the Dapr stat store, reads it and then deletes it.
```suggestion
Notice, as specified in the code above, the code saves application state in the Dapr state store, reads it, then deletes it.
```

2022-04-06 14:28 UTC, hhunter-ms commented on daprdocs/content/en/getting-started/quickstarts/statemanagement-quickstart.md
> +Notice, as specified in the code above, the code saves application state in the Dapr stat store, reads it and then deletes it.
```suggestion
Notice, as specified in the code above, the code saves application state in the Dapr state store, reads it, then deletes it.
```

2022-04-06 14:28 UTC, hhunter-ms commented on daprdocs/content/en/getting-started/quickstarts/statemanagement-quickstart.md
> +In the `order-processor` service, we're writing, reading and deleting an orderId key \ value pair to the Redis instance called `statestore` [(as defined in the `statestore.yaml` component)]({{< ref "
```suggestion
The `order-processor` service writes, reads, and deletes an `orderId` key\value pair to the `statestore` instance [defined in the `statestore.yaml` component]({{< ref "#statestoreyaml-component-file" >}}). As soon as the service starts, it performs a loop:
```

2022-04-06 14:28 UTC, hhunter-ms commented on daprdocs/content/en/getting-started/quickstarts/statemanagement-quickstart.md
> +In the `order-processor` service, we're writing, reading and deleting an orderId key \ value pair to the Redis instance called `statestore` [(as defined in the `statestore.yaml` component)]({{< ref "
```suggestion
The `order-processor` service writes, reads, and deletes an `orderId` key\value pair to the `statestore` instance [defined in the `statestore.yaml` component]({{< ref "#statestoreyaml-component-file" >}}). As soon as the service starts, it performs a loop:
```

2022-04-06 14:28 UTC, hhunter-ms commented on daprdocs/content/en/getting-started/quickstarts/statemanagement-quickstart.md
> +In the `order-processor` service, we're writing, reading and deleting an orderId key \ value pair to the Redis instance called `statestore` [(as defined in the `statestore.yaml` component)]({{< ref "
```suggestion
The `order-processor` service writes, reads, and deletes an `orderId` key\value pair to the `statestore` instance [defined in the `statestore.yaml` component]({{< ref "#statestoreyaml-component-file" >}}). As soon as the service starts, it performs a loop:
```

2022-04-06 14:28 UTC, hhunter-ms commented on daprdocs/content/en/getting-started/quickstarts/statemanagement-quickstart.md
> +Clone the sample we've set up:
```suggestion
Clone the [sample we've provided in our quickstarts repo](https://github.com/dapr/quickstarts/tree/master/state_management).
```

2022-04-06 14:28 UTC, hhunter-ms commented on daprdocs/content/en/getting-started/quickstarts/statemanagement-quickstart.md
> +Clone the sample we've provided.
```suggestion
Clone the [sample we've provided in our quickstarts repo](https://github.com/dapr/quickstarts/tree/master/state_management).
```

2022-04-06 14:28 UTC, hhunter-ms commented on daprdocs/content/en/getting-started/quickstarts/statemanagement-quickstart.md
> +Clone the sample we've provided.
```suggestion
Clone the [sample we've provided in our quickstarts repo](https://github.com/dapr/quickstarts/tree/master/state_management).
```

2022-04-06 21:27 UTC, amulyavarote approved these changes

2022-04-07 17:56 UTC, hhunter-ms requested changes
just a few more changes - thank you!

2022-04-07 17:56 UTC, hhunter-ms commented on daprdocs/content/en/getting-started/quickstarts/statemanagement-quickstart.md
> +The `order-processor` service writes, reads, and deletes an `orderId` key\value pair to the `statestore` instance [defined in the `statestore.yaml` component]({{< ref "#statestoreyaml-component-file"
```suggestion
The `order-processor` service writes, reads, and deletes an `orderId` key/value pair to the `statestore` instance [defined in the `statestore.yaml` component]({{< ref "#statestoreyaml-component-file" >}}). As soon as the service starts, it performs a loop.
```

2022-04-07 17:56 UTC, hhunter-ms commented on daprdocs/content/en/getting-started/quickstarts/statemanagement-quickstart.md
> +The `order-processor` service writes, reads, and deletes an `orderId` key\value pair to the `statestore` instance [defined in the `statestore.yaml` component]({{< ref "#statestoreyaml-component-file"
```suggestion
The `order-processor` service writes, reads, and deletes an `orderId` key/value pair to the `statestore` instance [defined in the `statestore.yaml` component]({{< ref "#statestoreyaml-component-file" >}}). As soon as the service starts, it performs a loop.
```

2022-04-07 17:56 UTC, hhunter-ms commented on daprdocs/content/en/getting-started/quickstarts/statemanagement-quickstart.md
> +The `order-processor` service writes, reads, and deletes an `orderId` key\value pair to the `statestore` instance [defined in the `statestore.yaml` component]({{< ref "#statestoreyaml-component-file"
```suggestion
The `order-processor` service writes, reads, and deletes an `orderId` key/value pair to the `statestore` instance [defined in the `statestore.yaml` component]({{< ref "#statestoreyaml-component-file" >}}). As soon as the service starts, it performs a loop.
```

2022-04-07 17:56 UTC, hhunter-ms commented on daprdocs/content/en/getting-started/quickstarts/statemanagement-quickstart.md
> +The `order-processor` service writes, reads, and deletes an `orderId` key\value pair to the `statestore` instance [defined in the `statestore.yaml` component]({{< ref "#statestoreyaml-component-file"
```suggestion
The `order-processor` service writes, reads, and deletes an `orderId` key/value pair to the `statestore` instance [defined in the `statestore.yaml` component]({{< ref "#statestoreyaml-component-file" >}}). As soon as the service starts, it performs a loop.
```

2022-04-07 17:56 UTC, hhunter-ms commented on daprdocs/content/en/getting-started/quickstarts/statemanagement-quickstart.md
> +The `order-processor` service writes, reads, and deletes an `orderId` key\value pair to the `statestore` instance [defined in the `statestore.yaml` component]({{< ref "#statestoreyaml-component-file"
```suggestion
The `order-processor` service writes, reads, and deletes an `orderId` key/value pair to the `statestore` instance [defined in the `statestore.yaml` component]({{< ref "#statestoreyaml-component-file" >}}). As soon as the service starts, it performs a loop.
```

2022-04-07 17:56 UTC, hhunter-ms commented on daprdocs/content/en/getting-started/quickstarts/statemanagement-quickstart.md
> +  // Save state into the state store
```suggestion
client, err := dapr.NewClient()

  // Save state into the state store
```

2022-04-07 17:56 UTC, hhunter-ms commented on daprdocs/content/en/getting-started/quickstarts/statemanagement-quickstart.md
> +// Save state into the state store
```suggestion
var client = new DaprClientBuilder().Build();

// Save state into the state store
```

2022-04-07 17:56 UTC, hhunter-ms commented on daprdocs/content/en/getting-started/quickstarts/statemanagement-quickstart.md
> +// Save state into the state store
```suggestion
const client = new DaprClient(DAPR_HOST, DAPR_HTTP_PORT);

// Save state into the state store
```

2022-04-07 17:56 UTC, hhunter-ms commented on daprdocs/content/en/getting-started/quickstarts/statemanagement-quickstart.md
> +<img src="/images/state-management-overview.png" width=800 style="padding-bottom:15px;">
Use updated diagram from @greenie-msft

2022-04-07 18:19 UTC, hhunter-ms commented on daprdocs/content/en/getting-started/quickstarts/statemanagement-quickstart.md
> +In this quickstart, you use the key/value pairs in the [supported state stores]({{< ref supported-state-stores.md >}}) and allow an application to save, get, and delete state. Our example below uses
Also - could you please capitalize "Quickstarts" throughout the doc? thanks!

2022-04-07 23:46 UTC, msfussell commented on daprdocs/content/en/getting-started/quickstarts/_index.md
> +| [State Management]({{< ref statemanagement-quickstart.md >}}) | Create a microservice to demonstrate Dapr's state management API. |
```suggestion
| [State Management]({{< ref statemanagement-quickstart.md >}}) | Create stateful applications using the state management API. |
```

2022-04-07 23:47 UTC, msfussell commented on daprdocs/content/en/getting-started/quickstarts/_index.md
>  | [Publish and Subscribe]({{< ref pubsub-quickstart.md >}}) | Get started with Dapr's Publish and Subscribe building block. |
```suggestion
| [Publish and Subscribe]({{< ref pubsub-quickstart.md >}}) | Send and receive messages using the publish and subscribe API. |
```

2022-04-07 23:49 UTC, msfussell commented on daprdocs/content/en/getting-started/quickstarts/_index.md
>  | [Service Invocation]({{< ref serviceinvocation-quickstart.md >}}) | Invoke a method using HTTP proxying with Dapr's Service Invocation building block. |
```suggestion
| [Service Invocation]({{< ref serviceinvocation-quickstart.md >}}) |  Call a method on another service using the service invocation API. |
```

2022-04-07 23:49 UTC, msfussell approved these changes

2022-04-07 23:58 UTC, merged