Add an example of binding multiple routingKeys
dapr/docs pull request #2465
Opened 2022-05-27 02:26 UTC by saber-wang

Thank you for helping make the Dapr documentation better!

**Please follow this checklist before submitting:**
- [√] Commits are signed with Developer Certificate of Origin (DCO - [learn more](https://docs.dapr.io/contributing/contributing-overview/#developer-certificate-of-origin-signing-your-work))
- [√] [Read the contribution guide](https://docs.dapr.io/contributing/contributing-docs/)
- [√] Commands include options for Linux, MacOS, and Windows within codetabs
- [√] New file and folder names are globally unique
- [√] Page references use shortcodes instead of markdown or URL links
- [√] Images use HTML style and have alternative text
- [√] Places where multiple code/command options are given have codetabs

In addition, please fill out the following to help reviewers understand this pull request:

2022-05-27 02:39 UTC, msfussell commented
Need to review if https://github.com/dapr/components-contrib/issues/1741 a valid approach for this component

2022-06-23 19:35 UTC, hhunter-ms requested changes

2022-06-23 19:35 UTC, hhunter-ms commented on daprdocs/content/en/reference/components-reference/supported-pubsub/setup-rabbitmq.md
> +Multiple routing Keys can be separated by commas.
```suggestion
Multiple routing keys can be separated by commas.  
```

2022-06-23 19:35 UTC, hhunter-ms commented on daprdocs/content/en/reference/components-reference/supported-pubsub/setup-rabbitmq.md
> +In the example, three "routingkey" including `keyA`, `keyB` and `""` will be bind.
```suggestion
The example below binds three `routingKey`: `keyA`, `keyB`, and `""`. Note the binding method of empty keys.
```

2022-06-23 19:35 UTC, hhunter-ms commented on daprdocs/content/en/reference/components-reference/supported-pubsub/setup-rabbitmq.md
> +Note:the binding method of empty keys
```suggestion
```

2022-06-24 23:33 UTC, berndverst approved these changes

2022-06-27 14:38 UTC, hhunter-ms approved these changes

2022-06-27 22:45 UTC, greenie-msft approved these changes

2022-06-27 22:45 UTC, merged