Binding quickstart - Cron input PostgreSQL output quickstart doc
dapr/docs pull request #2471
Opened 2022-05-27 19:38 UTC by nirmash

Signed-off-by: Nir Mashkowski <nimashkowski@microsoft.com>

Thank you for helping make the Dapr documentation better!

**Please follow this checklist before submitting:**
- [X] Commits are signed with Developer Certificate of Origin (DCO - [learn more](https://docs.dapr.io/contributing/contributing-overview/#developer-certificate-of-origin-signing-your-work))
- [X] [Read the contribution guide](https://docs.dapr.io/contributing/contributing-docs/)
- [X] Commands include options for Linux, MacOS, and Windows within codetabs
- [X] New file and folder names are globally unique
- [X] Page references use shortcodes instead of markdown or URL links
- [X] Images use HTML style and have alternative text
- [X] Places where multiple code/command options are given have codetabs

In addition, please fill out the following to help reviewers understand this pull request:

## Description

Doc for new Bindings Quickstart

## Issue reference

2022-05-31 14:35 UTC, hhunter-ms commented on daprdocs/content/en/getting-started/quickstarts/_index.md
> +| [Bindings]({{< ref bindings-quickstart.md >}}) | Use Dapr's input and output bindings to schedule a database insert job. |
```suggestion
| [Bindings]({{< ref bindings-quickstart.md >}}) | Schedule a database insert job using the input and output bindings API. |
```

To match the sentence structure of the other quickstart descriptions.

2022-05-31 16:23 UTC, hhunter-ms requested changes, later dismissed
Just a few grammar and consistency updates. I ran through the quickstart and all the languages worked for me!

2022-05-31 16:23 UTC, hhunter-ms commented on daprdocs/content/en/getting-started/quickstarts/bindings-quickstart.md
> +linkTitle: "Dapr Bindings"
```suggestion
linkTitle: "Bindings"
```

2022-05-31 16:23 UTC, hhunter-ms commented on daprdocs/content/en/getting-started/quickstarts/bindings-quickstart.md
> +Using bindings, you can trigger your app with events coming in from external systems, or interface with external systems. Bindings provide several benefits for you and your code:
```suggestion
Using bindings, you can:

- Trigger your app with events coming in from external systems.
- Interface with external systems. 
```

To keep the quickstart streamlined and get people straight into the example, let's leave the following list out. We link to the bindings overview, where they can find this list of benefits.

2022-05-31 16:23 UTC, hhunter-ms commented on daprdocs/content/en/getting-started/quickstarts/bindings-quickstart.md
> + - Build portable applications where environment-specific bindings are set-up and no code changes are required.
Per comment above, remove lines 12 - 17.

2022-05-31 16:23 UTC, hhunter-ms commented on daprdocs/content/en/getting-started/quickstarts/bindings-quickstart.md
> +For a specific example, bindings would allow your microservice to respond to incoming Twilio/SMS messages without adding or configuring a third-party Twilio SDK, worrying about polling from Twilio (o
I'd remove this as well - it doesn't really speak to this specific quickstart example, and it's already in the bindings overview.

2022-05-31 16:23 UTC, hhunter-ms commented on daprdocs/content/en/getting-started/quickstarts/bindings-quickstart.md
> +In a terminal window, navigate to the `sdk` directory.
```suggestion
In a new terminal window, navigate to the `sdk` directory.
```

2022-05-31 16:23 UTC, hhunter-ms commented on daprdocs/content/en/getting-started/quickstarts/bindings-quickstart.md
> +The `python-quickstart-binding-sdk` uses the PostgreSQL Output Binding defined in the [`bindings.yaml`]({{< ref "#bindingsyaml-component-file" >}}) component to insert the `OrderId`, `Customer` and `
```suggestion
The `python-quickstart-binding-sdk` uses the PostgreSQL Output Binding defined in the [`bindings.yaml`]({{< ref "#bindingsyaml-component-file" >}}) component to insert the `OrderId`, `Customer`, and `Price` records into the `orders` table. This code is executed every 10 seconds (defined in [`cron.yaml`]({{< ref "#cronyaml-component-file" >}}) in the `components` directory).
```

2022-05-31 16:23 UTC, hhunter-ms commented on daprdocs/content/en/getting-started/quickstarts/bindings-quickstart.md
> +Notice, as specified above, the code invokes the Output Binding with the `OrderId`, `Customer` and `Price` as a payload.
```suggestion
Notice, as specified above, the code invokes the Output Binding with the `OrderId`, `Customer`, and `Price` as a payload.
```

2022-05-31 16:23 UTC, hhunter-ms commented on daprdocs/content/en/getting-started/quickstarts/bindings-quickstart.md
> +The `python-quickstart-binding-sdk` uses the Cron Input Binding defined in the [`cron.yaml`]({{< ref "#cronyaml-component-file" >}}) component to process a json file containing order information.
```suggestion
The `python-quickstart-binding-sdk` uses the Cron Input Binding defined in the [`cron.yaml`]({{< ref "#cronyaml-component-file" >}}) component to process a JSON file containing order information.
```

2022-05-31 16:23 UTC, hhunter-ms commented on daprdocs/content/en/getting-started/quickstarts/bindings-quickstart.md
> +Let's take a look at Dapr's [Binding building block]({{< ref bindings >}}). In this Quickstart, you will schedule a script to run every 10 seconds using an input [Cron](https://docs.dapr.io/reference
```suggestion
Let's take a look at Dapr's [Binding building block]({{< ref bindings >}}). In this Quickstart, you will schedule a script to run every 10 seconds using an input [Cron](https://docs.dapr.io/reference/components-reference/supported-bindings/cron/) binding. The script will process a JSON file and output data to a SQL database using the [PostgreSQL](https://docs.dapr.io/reference/components-reference/supported-bindings/postgres) Dapr binding.
```

2022-05-31 16:23 UTC, hhunter-ms commented on daprdocs/content/en/getting-started/quickstarts/bindings-quickstart.md
> +In order to run the PostgreSQL bindings quickstart locally, you will run the [PostgreSQL instance](https://www.postgresql.org/) in a docker container on your machine.
```suggestion
Run the [PostgreSQL instance](https://www.postgresql.org/) in a Docker container on your machine.
```

2022-05-31 16:23 UTC, hhunter-ms commented on daprdocs/content/en/getting-started/quickstarts/bindings-quickstart.md
> +In order to run the PostgreSQL bindings quickstart locally, you will run the [PostgreSQL instance](https://www.postgresql.org/) in a docker container on your machine.
```suggestion
Run the [PostgreSQL instance](https://www.postgresql.org/) in a Docker container on your machine.
```

2022-05-31 16:23 UTC, hhunter-ms commented on daprdocs/content/en/getting-started/quickstarts/bindings-quickstart.md
> +To run the container locally, run:
```suggestion
```

2022-05-31 16:23 UTC, hhunter-ms commented on daprdocs/content/en/getting-started/quickstarts/bindings-quickstart.md
> +To run the container locally, run:
```suggestion
```

2022-05-31 16:23 UTC, hhunter-ms commented on daprdocs/content/en/getting-started/quickstarts/bindings-quickstart.md
> +In a terminal window, navigate to the `sdk` directory.
```suggestion
In a new terminal window, navigate to the `sdk` directory.
```

2022-05-31 16:23 UTC, hhunter-ms commented on daprdocs/content/en/getting-started/quickstarts/bindings-quickstart.md
> +The `javascript-quickstart-binding-sdk` uses the PostgreSQL Output Binding defined in the [`bindings.yaml`]({{< ref "#bindingsyaml-component-file" >}}) component to insert the `OrderId`, `Customer` a
```suggestion
The `javascript-quickstart-binding-sdk` uses the PostgreSQL Output Binding defined in the [`bindings.yaml`]({{< ref "#bindingsyaml-component-file" >}}) component to insert the `OrderId`, `Customer`, and `Price` records into the `orders` table. This code is executed every 10 seconds (defined in [`cron.yaml`]({{< ref "#cronyaml-component-file" >}}) in the `components` directory).
```

2022-05-31 16:23 UTC, hhunter-ms commented on daprdocs/content/en/getting-started/quickstarts/bindings-quickstart.md
> +Notice, as specified above, the code invokes the Output Binding with the `OrderId`, `Customer` and `Price` as a payload.
```suggestion
Notice, as specified above, the code invokes the Output Binding with the `OrderId`, `Customer`, and `Price` as a payload.
```

2022-05-31 16:23 UTC, hhunter-ms commented on daprdocs/content/en/getting-started/quickstarts/bindings-quickstart.md
> +The `javascript-quickstart-binding-sdk` uses the Cron Input Binding defined in the [`cron.yaml`]({{< ref "#cronyaml-component-file" >}}) component to process a json file containing order information.
```suggestion
The `javascript-quickstart-binding-sdk` uses the Cron Input Binding defined in the [`cron.yaml`]({{< ref "#cronyaml-component-file" >}}) component to process a JSON file containing order information.
```

2022-05-31 16:23 UTC, hhunter-ms commented on daprdocs/content/en/getting-started/quickstarts/bindings-quickstart.md
> +In order to run the PostgreSQL bindings quickstart locally, you will run the [PostgreSQL instance](https://www.postgresql.org/) in a docker container on your machine.
```suggestion
Run the [PostgreSQL instance](https://www.postgresql.org/) in a Docker container on your machine.
```

2022-05-31 16:23 UTC, hhunter-ms commented on daprdocs/content/en/getting-started/quickstarts/bindings-quickstart.md
> +To run the container locally, run:
```suggestion
```

2022-05-31 16:23 UTC, hhunter-ms commented on daprdocs/content/en/getting-started/quickstarts/bindings-quickstart.md
> +In a terminal window, navigate to the `sdk` directory.
```suggestion
In a new terminal window, navigate to the `sdk` directory.
```

2022-05-31 16:23 UTC, hhunter-ms commented on daprdocs/content/en/getting-started/quickstarts/bindings-quickstart.md
> +The `csharp-quickstart-binding-sdk` uses the PostgreSQL Output Binding defined in the [`bindings.yaml`]({{< ref "#bindingsyaml-component-file" >}}) component to insert the `OrderId`, `Customer` and `
```suggestion
The `csharp-quickstart-binding-sdk` uses the PostgreSQL Output Binding defined in the [`bindings.yaml`]({{< ref "#bindingsyaml-component-file" >}}) component to insert the `OrderId`, `Customer`, and `Price` records into the `orders` table. This code is executed every 10 seconds (defined in [`cron.yaml`]({{< ref "#cronyaml-component-file" >}}) in the `components` directory).
```

2022-05-31 16:23 UTC, hhunter-ms commented on daprdocs/content/en/getting-started/quickstarts/bindings-quickstart.md
> +Notice, as specified above, the code invokes the Output Binding with the `OrderId`, `Customer` and `Price` as a payload.
```suggestion
Notice, as specified above, the code invokes the Output Binding with the `OrderId`, `Customer`, and `Price` as a payload.
```

2022-05-31 16:23 UTC, hhunter-ms commented on daprdocs/content/en/getting-started/quickstarts/bindings-quickstart.md
> +The `csharp-quickstart-binding-sdk` uses the Cron Input Binding defined in the [`cron.yaml`]({{< ref "#cronyaml-component-file" >}}) component to process a json file containing order information.
```suggestion
The `csharp-quickstart-binding-sdk` uses the Cron Input Binding defined in the [`cron.yaml`]({{< ref "#cronyaml-component-file" >}}) component to process a JSON file containing order information.
```

2022-05-31 16:23 UTC, hhunter-ms commented on daprdocs/content/en/getting-started/quickstarts/bindings-quickstart.md
> +In order to run the PostgreSQL bindings quickstart locally, you will run the [PostgreSQL instance](https://www.postgresql.org/) in a docker container on your machine.
```suggestion
Run the [PostgreSQL instance](https://www.postgresql.org/) in a Docker container on your machine.
```

2022-05-31 16:23 UTC, hhunter-ms commented on daprdocs/content/en/getting-started/quickstarts/bindings-quickstart.md
> +In a terminal window, navigate to the `sdk` directory.
```suggestion
In a new terminal window, navigate to the `sdk` directory.
```

2022-05-31 16:23 UTC, hhunter-ms commented on daprdocs/content/en/getting-started/quickstarts/bindings-quickstart.md
> +The `go-input-binding-sdk` uses the PostgreSQL Output Binding defined in the [`bindings.yaml`]({{< ref "#bindingsyaml-component-file" >}}) component to insert the `OrderId`, `Customer` and `Price` re
```suggestion
The `go-input-binding-sdk` uses the PostgreSQL Output Binding defined in the [`bindings.yaml`]({{< ref "#bindingsyaml-component-file" >}}) component to insert the `OrderId`, `Customer`, and `Price` records into the `orders` table. This code is executed every 10 seconds (defined in [`cron.yaml`]({{< ref "#cronyaml-component-file" >}}) in the `components` directory).
```

2022-05-31 16:23 UTC, hhunter-ms commented on daprdocs/content/en/getting-started/quickstarts/bindings-quickstart.md
> +Notice, as specified above, the code invokes the Output Binding with the `OrderId`, `Customer` and `Price` as a payload.
```suggestion
Notice, as specified above, the code invokes the Output Binding with the `OrderId`, `Customer`, and `Price` as a payload.
```

2022-05-31 16:23 UTC, hhunter-ms commented on daprdocs/content/en/getting-started/quickstarts/bindings-quickstart.md
> +The `go-input-binding-sdk` uses the Cron Input Binding defined in the [`cron.yaml`]({{< ref "#cronyaml-component-file" >}}) component to process a json file containing order information.
```suggestion
The `go-input-binding-sdk` uses the Cron Input Binding defined in the [`cron.yaml`]({{< ref "#cronyaml-component-file" >}}) component to process a JSON file containing order information.
```

2022-05-31 17:01 UTC, hhunter-ms commented
Issue #2477

2022-06-17 02:35 UTC, msfussell commented on daprdocs/content/en/getting-started/quickstarts/bindings-quickstart.md
> +In this Quickstart, you will schedule a batch script to run every 10 seconds using an input [Cron](https://docs.dapr.io/reference/components-reference/supported-bindings/cron/) binding. The script wi
```suggestion
In this Quickstart, you will schedule a batch script to run every 10 seconds using an input [Cron](https://docs.dapr.io/reference/components-reference/supported-bindings/cron/) binding. The script processes a JSON file and outputs data to a SQL database using the [PostgreSQL](https://docs.dapr.io/reference/components-reference/supported-bindings/postgres) Dapr binding.
```

2022-06-17 02:47 UTC, msfussell commented on daprdocs/content/en/getting-started/quickstarts/bindings-quickstart.md
> +Clone the [sample we've provided in our Quickstarts repo](https://github.com/dapr/quickstarts/tree/master/bindings).
```suggestion
Clone the [sample provided in the Quickstarts repo](https://github.com/dapr/quickstarts/tree/master/bindings).
```

2022-06-17 02:48 UTC, msfussell commented on daprdocs/content/en/getting-started/quickstarts/bindings-quickstart.md
> +You will run the [PostgreSQL instance](https://www.postgresql.org/) locally in a Docker container on your machine. The Quickstart sample includes a Docker Compose file to locally customize, build, ru
```suggestion
You run the [PostgreSQL instance](https://www.postgresql.org/) locally in a Docker container on your machine. The Quickstart sample includes a Docker Compose file to locally customize, build, run, and initialize the `postgres` container with a default `orders` table.
```

2022-06-17 02:48 UTC, msfussell commented on daprdocs/content/en/getting-started/quickstarts/bindings-quickstart.md
> +In a terminal window, from the root of the Quickstarts clone directory, navigate to the `bindings\db` directory.
```suggestion
In a terminal window, from the root of the Quickstarts clone directory, navigate to the `bindings/db` directory.
```

2022-06-17 02:50 UTC, msfussell commented on daprdocs/content/en/getting-started/quickstarts/bindings-quickstart.md
> +Notice, as specified above, the code invokes the Output Binding with the `OrderId`, `Customer`, and `Price` as a payload.
```suggestion
Notice, as specified above, the code invokes the output binding with the `OrderId`, `Customer`, and `Price` as a payload.
```

2022-06-17 02:50 UTC, msfussell commented on daprdocs/content/en/getting-started/quickstarts/bindings-quickstart.md
> +- Initiates the Cron [Binding building block]({{< ref bindings >}})
```suggestion
- Initiates the Cron [binding building block]({{< ref bindings >}})
```

2022-06-17 02:51 UTC, msfussell commented on daprdocs/content/en/getting-started/quickstarts/bindings-quickstart.md
> +**Note:** The `metadata` section of `binding-cron.yaml` contains a [Cron expression](/reference/components-reference/supported-bindings/cron/) that specifies how often the binding will be invoked.
```suggestion
**Note:** The `metadata` section of `binding-cron.yaml` contains a [Cron expression](/reference/components-reference/supported-bindings/cron/) that specifies how often the binding is invoked.
```

2022-06-17 02:52 UTC, msfussell commented on daprdocs/content/en/getting-started/quickstarts/bindings-quickstart.md
> +- Initiates the PostgreSQL [Binding building block]({{< ref /reference/components-reference/supported-bindings/postgres.md >}})
```suggestion
- Initiates the PostgreSQL [binding building block]({{< ref /reference/components-reference/supported-bindings/postgres.md >}})
```

2022-06-17 02:52 UTC, msfussell commented on daprdocs/content/en/getting-started/quickstarts/bindings-quickstart.md
> +Clone the [sample we've provided in our Quickstarts repo](https://github.com/dapr/quickstarts/tree/master/bindings).
```suggestion
Clone the [sample provided in the Quickstarts repo](https://github.com/dapr/quickstarts/tree/master/bindings).
```

2022-06-17 02:54 UTC, msfussell commented
@hhunter-ms - I reviewed the first python code section and hopefully you can apply those suggestion to the other languages in the QS

2022-06-21 18:32 UTC, greenie-msft commented
@nirmash, does running this branch locally work for you? When I try, I get the error: 

/bindings-quickstart.md:391:62": failed to extract shortcode: shortcode "reference" has no .Inner, yet a closing tag was provided

2022-06-23 17:10 UTC, greenie-msft commented on daprdocs/content/en/getting-started/quickstarts/bindings-quickstart.md
> +**Note:** The `metadata` section of `binding-cron.yaml` contains a [Cron expression]({{ ref cron.md }}) that specifies how often the binding is invoked.
I think this link is missing the "<" ">"

2022-06-24 05:01 UTC, msfussell commented
@greenie-msft @hhunter-ms  - Are these PPT image files checked in somewhere?

2022-06-24 20:25 UTC, greenie-msft commented
> @greenie-msft @hhunter-ms - Are these PPT image files checked in somewhere?

I don't think they are but we can check them into the diagrams ppt?

2022-06-24 20:25 UTC, greenie-msft approved these changes

2022-06-24 22:01 UTC, msfussell approved these changes
Fantastic to see this complete!

2022-06-24 22:34 UTC, merged