Add docs for using Mariner-based images
dapr/docs pull request #2549
Opened 2022-06-21 17:53 UTC by ItalyPaleAle

Fixes #2514

2022-06-23 16:55 UTC, hhunter-ms requested changes

2022-06-23 16:55 UTC, hhunter-ms commented on daprdocs/content/en/operations/hosting/kubernetes/kubernetes-deploy.md
> +When deploying Dapr, on Kubernetes but also in Docker self-hosted, the default container images that are pulled are based on [*distroless*](https://github.com/GoogleContainerTools/distroless).
```suggestion
When deploying Dapr, whether on Kubernetes or in Docker self-hosted, the default container images that are pulled are based on [*distroless*](https://github.com/GoogleContainerTools/distroless).
```

2022-06-23 16:55 UTC, hhunter-ms commented on daprdocs/content/en/operations/hosting/kubernetes/kubernetes-deploy.md
> +As an alternative option, you can use Dapr container images based on Mariner 2 (minimal distroless). [Mariner](https://github.com/microsoft/CBL-Mariner/), officially known as CBL-Mariner, is a free a
```suggestion
Alternatively, you can use Dapr container images based on Mariner 2 (minimal distroless). [Mariner](https://github.com/microsoft/CBL-Mariner/), officially known as CBL-Mariner, is a free and open-source Linux distribution and container base image maintained by Microsoft. For some Dapr users, leveraging container images based on Mariner can help them meet compliance requirements.
```

2022-06-23 16:55 UTC, hhunter-ms commented on daprdocs/content/en/operations/hosting/kubernetes/kubernetes-deploy.md
> +To use Mariner-based images for Dapr, you need to add `-mariner` to your Docker tags. For example, while `ghcr.io/dapr/dapr:latest` is the Docker image based on *distroless*, `ghcr.io/dapr/dapr:lates
```suggestion
To use Mariner-based images for Dapr, you need to add `-mariner` to your Docker tags. For example, while `ghcr.io/dapr/dapr:latest` is the Docker image based on *distroless*, `ghcr.io/dapr/dapr:latest-mariner` is based on Mariner. Tags pinned to a specific version are also available, such as `{{% dapr-latest-version short="true" %}}-mariner`.
```

2022-06-23 18:27 UTC, ItalyPaleAle commented on daprdocs/content/en/operations/hosting/kubernetes/kubernetes-deploy.md
> +As an alternative option, you can use Dapr container images based on Mariner 2 (minimal distroless). [Mariner](https://github.com/microsoft/CBL-Mariner/), officially known as CBL-Mariner, is a free a
How about "help you meet"?

2022-06-23 18:27 UTC, ItalyPaleAle commented
Thanks for the review @hhunter-ms :)

2022-06-23 19:12 UTC, hhunter-ms commented on daprdocs/content/en/operations/hosting/kubernetes/kubernetes-deploy.md
> +As an alternative option, you can use Dapr container images based on Mariner 2 (minimal distroless). [Mariner](https://github.com/microsoft/CBL-Mariner/), officially known as CBL-Mariner, is a free a
That works for me too!

2022-06-27 20:57 UTC, hhunter-ms approved these changes

2022-07-06 18:27 UTC, merged