[quickstarts] Small updates and cross-linking
dapr/docs pull request #2574
Opened 2022-06-27 20:30 UTC by hhunter-ms

Signed-off-by: Hannah Hunter <hannahhunter@microsoft.com>

## Description

- Update descriptions on quickstarts/_index.md
- Update C# and Go code snippets for Bindings
- Link to quickstarts from Service Invo and Secrets how-tos

## Issue reference

#2573

2022-06-27 22:04 UTC, paulyuk requested changes
Hi - like the spirit of the changes.  Might have trunc'ed a little too much of the code.  but like how it's simplified!

2022-06-27 22:04 UTC, paulyuk commented on daprdocs/content/en/getting-started/quickstarts/_index.md
> +| [Publish and Subscribe]({{< ref pubsub-quickstart.md >}}) |  Asynchronous communication between two services using messaging. |
Like!

2022-06-27 22:04 UTC, paulyuk commented on daprdocs/content/en/getting-started/quickstarts/bindings-quickstart.md
> +    resp = d.invoke_binding(binding_name=sql_binding, operation='exec',
I like it that you've shortened.  however I think the line with `With DaprClient as d:` is still needed to make sense of the `d.invoke_binding` line.  Also for bindings the metadata/payload is vital, so I think you need all the lines from d's declaration to the invoke_binding, inclusive of the SQL command and the payload..

2022-06-27 22:04 UTC, paulyuk commented on daprdocs/content/en/getting-started/quickstarts/bindings-quickstart.md
> +		Metadata:  map[string]string{"sql": sqlCmd},
Per above I think you might need to show dapr being declared as well as the sqlcmd.

2022-06-27 22:25 UTC, paulyuk requested changes

2022-06-27 22:25 UTC, paulyuk commented on daprdocs/content/en/getting-started/quickstarts/bindings-quickstart.md
> +    Console.WriteLine("Processing batch..");
I think in this small section we're trying to explain the cron binding, so I would remove all this file processing stuff.

2022-06-27 22:25 UTC, paulyuk commented on daprdocs/content/en/getting-started/quickstarts/bindings-quickstart.md
> +await client.InvokeBindingAsync(bindingName: sqlBindingName, operation: "exec", data: "", metadata: command);
Right above HERE is where I suggest showing how the Client object is created, the sql command and the metadata command gets set.  This makes full sense of calling the output binding on line 520

2022-06-27 22:25 UTC, paulyuk commented on daprdocs/content/en/getting-started/quickstarts/bindings-quickstart.md
> +await client.InvokeBindingAsync(bindingName: sqlBindingName, operation: "exec", data: "", metadata: command);
What you did for Go below looks right.  I would replicate for C# equiv

2022-06-27 22:37 UTC, paulyuk approved these changes
LGTM!

2022-06-30 18:00 UTC, greenie-msft approved these changes

2022-06-30 20:39 UTC, merged