docs: fix typesetting
dapr/docs pull request #2722
Opened 2022-08-15 01:43 UTC by 1046102779

https://docs.dapr.io/operations/hosting/kubernetes/kubernetes-deploy/#install-dapr-a-private-dapr-helm-chart

<img width="1182" alt="image" src="https://user-images.githubusercontent.com/20457624/184564172-f23352e2-a18d-4f34-a2db-33e4710e41bf.png">

2022-08-15 17:51 UTC, hhunter-ms requested changes
quick edit for clarity, otherwise lgtm

2022-08-15 17:51 UTC, hhunter-ms commented on daprdocs/content/en/operations/hosting/kubernetes/kubernetes-deploy.md
Encasing lines 67-71 in a code block.

```suggestion
```bash
```

2022-08-15 17:51 UTC, hhunter-ms commented on daprdocs/content/en/operations/hosting/kubernetes/kubernetes-deploy.md
Per comment above, add ``` here to close out code block.

2022-08-29 03:41 UTC, msfussell approved these changes
LGTM

2022-09-06 00:09 UTC, closed without merging