[Multi-tenancy/namespace consumer group] Create howto and add to overview
dapr/docs pull request #2864
Opened 2022-10-06 00:07 UTC by hhunter-ms

## Description

- Add namespace consumer groups to overview
- Create howto doc for using namespace value

## Issue reference

PR will close: #2769

2022-10-06 00:44 UTC, yaron2 requested changes

2022-10-06 00:44 UTC, yaron2 commented on daprdocs/content/en/developing-applications/building-blocks/pubsub/howto-namespace.md
> +By calling `consumerID` with the `{namespace}` value, you'll be able to use the same `app-id` with the same topics from different namespaces.
Maybe change `calling` to `configuring`?

2022-10-06 00:44 UTC, yaron2 commented on daprdocs/content/en/developing-applications/building-blocks/pubsub/howto-namespace.md
> +In the diagram above, you have two namespaces, each with applications of the same `app-id`, publishing and subscribing to the same centralized message bus `orders. This time, however, Dapr has create
typo: insert missing ` after orders.

2022-10-06 05:10 UTC, yaron2 approved these changes
LGTM

2022-10-06 22:02 UTC, msfussell commented on daprdocs/content/en/developing-applications/building-blocks/pubsub/howto-namespace.md
> +Simply include the `"{namespace}"` consumer group construct in your component metadata. You don't need to encode the namespace in the metadata. Dapr will understand the namespace running and will fil
```suggestion
Simply include the `"{namespace}"` consumer group construct in your component metadata. You don't need to encode the namespace in the metadata. Dapr understands the namespace it is running in and completes the namespace value for you, like a dynamic metadata value injected by the runtime.
```

2022-10-06 22:04 UTC, msfussell commented on daprdocs/content/en/developing-applications/building-blocks/pubsub/howto-namespace.md
> +If you add the namespace consumer group to your metadata afterwards, Dapr will update everything for you.
```suggestion
If you add the namespace consumer group to your metadata afterwards, Dapr updates everything for you. This means that you can add namespace metadata value to existing pub/sub deployments
```

2022-10-06 22:05 UTC, msfussell commented on daprdocs/content/en/developing-applications/building-blocks/pubsub/howto-namespace.md
> +- Learn more about [pub/sub namespaces]({{< ref pubsub-namespaces >}}).
```suggestion
- Learn more about configuring Pub/Sub components with multiple namespaces [pub/sub namespaces]({{< ref pubsub-namespaces >}}).
```

2022-10-06 22:09 UTC, msfussell commented on daprdocs/content/en/developing-applications/building-blocks/pubsub/pubsub-overview.md
> +Dapr solves multi-tenancy at-scale with its [namespace consumer groups construct]({{< ref howto-namespace >}}). Simply include the `"{namespace}"` value in your component metadata to allow multiple n
```suggestion
Dapr solves multi-tenancy at-scale with [namespaces for consumer groups]({{< ref howto-namespace >}}). Simply include the `"{namespace}"` value in your component metadata for consumer groups to allow multiple namespaces with applications of the same `app-id` to publish and subscribe to the same message broker.
```

2022-10-07 15:13 UTC, msfussell commented
@hhunter-ms - The with-namespace.png file still stays "message bus"

2022-10-07 16:37 UTC, merged