quickstarts code fix
dapr/docs pull request #2877
Opened 2022-10-08 16:04 UTC by rogerogers

Signed-off-by: rogerogers <rogers@rogerogers.com>

Thank you for helping make the Dapr documentation better!

**Please follow this checklist before submitting:**
- [x] Commits are signed with Developer Certificate of Origin (DCO - [learn more](https://docs.dapr.io/contributing/contributing-overview/#developer-certificate-of-origin-signing-your-work))
- [x] [Read the contribution guide](https://docs.dapr.io/contributing/docs-contrib/contributing-docs/)
- [x] Commands include options for Linux, MacOS, and Windows within codetabs
- [x] New file and folder names are globally unique
- [x] Page references use shortcodes instead of markdown or URL links
- [x] Images use HTML style and have alternative text
- [x] Places where multiple code/command options are given have codetabs

In addition, please fill out the following to help reviewers understand this pull request:

## Description

code indentation and some command fix

## Issue reference

2022-10-10 20:15 UTC, hhunter-ms requested changes
updated commands to match [quickstart](https://github.com/dapr/quickstarts) readme files

2022-10-10 20:15 UTC, hhunter-ms commented on daprdocs/content/en/getting-started/quickstarts/pubsub-quickstart.md
> +go build app.go
```suggestion
go build .
```

2022-10-10 20:15 UTC, hhunter-ms commented on daprdocs/content/en/getting-started/quickstarts/pubsub-quickstart.md
> +dapr run --app-port 6001 --app-id order-processor --app-protocol http --dapr-http-port 3501 --components-path ../../../components -- go run app.go
```suggestion
dapr run --app-port 6002 --app-id order-processor-sdk --app-protocol http --dapr-http-port 3501 --components-path ../../../components -- go run .
```

2022-10-10 20:15 UTC, hhunter-ms commented on daprdocs/content/en/getting-started/quickstarts/secrets-quickstart.md
> +go build app.go
```suggestion
go build .
```

2022-10-10 20:15 UTC, hhunter-ms commented on daprdocs/content/en/getting-started/quickstarts/secrets-quickstart.md
> +dapr run --app-id order-processor --components-path ../../../components/ -- go run app.go
```suggestion
dapr run --app-id order-processor --components-path ../../../components/ -- go run .
```

2022-10-10 20:15 UTC, hhunter-ms commented on daprdocs/content/en/getting-started/quickstarts/statemanagement-quickstart.md
> +go build app.go
```suggestion
go build .
```

2022-10-10 20:15 UTC, hhunter-ms commented on daprdocs/content/en/getting-started/quickstarts/statemanagement-quickstart.md
> +dapr run --app-id order-processor --components-path ../../../components -- go run app.go
```suggestion
dapr run --app-id order-processor --components-path ../../../components -- go run .
```

2022-10-10 20:15 UTC, hhunter-ms commented on daprdocs/content/en/getting-started/quickstarts/bindings-quickstart.md
> +go build app.go
```suggestion
go build .
```

2022-10-10 20:15 UTC, hhunter-ms commented on daprdocs/content/en/getting-started/quickstarts/bindings-quickstart.md
> +dapr run --app-id batch-sdk --app-port 6002 --dapr-http-port 3502 --dapr-grpc-port 60002 --components-path ../../../components -- go run app.go
```suggestion
dapr run --app-id batch-sdk --app-port 6002 --dapr-http-port 3502 --dapr-grpc-port 60002 --components-path ../../../components -- go run .
```

2022-10-11 01:46 UTC, rogerogers commented
done, go build . is better.

2022-10-11 16:42 UTC, msfussell approved these changes

2022-10-11 17:04 UTC, msfussell approved these changes

2022-10-11 21:35 UTC, hhunter-ms approved these changes

2022-10-11 22:16 UTC, merged