Add Resiliency to the concepts page
dapr/docs pull request #2899
Opened 2022-10-14 23:05 UTC by greenie-msft

Signed-off-by: Nick Greenfield <nigreenf@microsoft.com>

Thank you for helping make the Dapr documentation better!

**Please follow this checklist before submitting:**
- [x] Commits are signed with Developer Certificate of Origin (DCO - [learn more](https://docs.dapr.io/contributing/contributing-overview/#developer-certificate-of-origin-signing-your-work))
- [x] [Read the contribution guide](https://docs.dapr.io/contributing/docs-contrib/contributing-docs/)
- [x] Commands include options for Linux, MacOS, and Windows within codetabs
- [x] New file and folder names are globally unique
- [x] Page references use shortcodes instead of markdown or URL links
- [x] Images use HTML style and have alternative text
- [x] Places where multiple code/command options are given have codetabs

In addition, please fill out the following to help reviewers understand this pull request:

## Description

Added Resiliency Overview to Dapr Concepts page

2022-10-15 00:36 UTC, msfussell commented
@greenie-msft Feedback
1) I would also include https://docs.dapr.io/developing-applications/building-blocks/observability/sidecar-health/ in a section of the overview (and maybe rename the title to "Dapr health checks") as another resiliency feature of Dapr (it is not really observability) 
2) Do you still want to have the overview text here https://docs.dapr.io/operations/resiliency/resiliency-overview/? Seems redundant to the concept doc.

2022-10-17 15:58 UTC, hhunter-ms requested changes

2022-10-17 15:58 UTC, hhunter-ms commented on daprdocs/content/en/concepts/resiliency-concept.md
> +Distributed applications are commonly comprised of many microservices, with dozens, sometimes hundreds of instances scaling across underlying infrastructure. As these distributed solutions grow in si
```suggestion
Distributed applications are commonly comprised of many microservices, with dozens - sometimes hundreds - of instances scaling across underlying infrastructure. As these distributed solutions grow in size and complexity, the potential for system failures inevitably increases. Service instances can fail or become unresponsive due to any number of issues, including hardware failures, unexpected throughput, or application lifecycle events, such as scaling out and application restarts. Designing and implementing a self-healing solution with the ability to detect, mitigate, and respond to failure is critical.
```

2022-10-17 15:58 UTC, hhunter-ms commented on daprdocs/content/en/concepts/resiliency-concept.md
> +These policies can be applied to any Dapr API calls and when calling components with a [resiliency spec]({{< ref resiliency-overview >}}).
```suggestion
These policies can be applied to any Dapr API calls when calling components with a [resiliency spec]({{< ref resiliency-overview >}}).
```

2022-10-17 15:58 UTC, hhunter-ms commented on daprdocs/content/en/concepts/resiliency-concept.md
> +Applications can become unresponsive for a variety of reasons, for example, they are to busy to accept new work, could have crashed, or be in a deadlock state. Sometimes the condition can be transito
```suggestion
Applications can become unresponsive for a variety of reasons. For example, they are too busy to accept new work, could have crashed, or be in a deadlock state. Sometimes the condition can be transitory or persistent.
```

2022-11-02 22:08 UTC, hhunter-ms approved these changes

2022-11-02 22:10 UTC, greenie-msft commented on daprdocs/content/en/concepts/resiliency-concept.md
> +description: "Configure retries, timeouts, circuit breakers and monitor app health"
```suggestion
description: "Configure policies and monitor app and sidecar health"
```

2022-11-02 23:47 UTC, hhunter-ms approved these changes

2022-11-03 16:53 UTC, hhunter-ms approved these changes
lgtm

2022-11-03 17:03 UTC, merged