Modified the RocketMQ document based on V1.10
dapr/docs pull request #2951
Opened 2022-11-10 09:34 UTC by jinjianfeng-chn

Signed-off-by: jinjianfeng-chn <feng081212@163.com>

Thank you for helping make the Dapr documentation better!

**Please follow this checklist before submitting:**
- [ ] Commits are signed with Developer Certificate of Origin (DCO - [learn more](https://docs.dapr.io/contributing/contributing-overview/#developer-certificate-of-origin-signing-your-work))
- [ ] [Read the contribution guide](https://docs.dapr.io/contributing/docs-contrib/contributing-docs/)
- [ ] Commands include options for Linux, MacOS, and Windows within codetabs
- [ ] New file and folder names are globally unique
- [ ] Page references use shortcodes instead of markdown or URL links
- [ ] Images use HTML style and have alternative text
- [ ] Places where multiple code/command options are given have codetabs

In addition, please fill out the following to help reviewers understand this pull request:

## Description

## Issue reference

2022-11-10 17:19 UTC, hhunter-ms requested changes
Grammar/readability pass

2022-11-10 17:19 UTC, hhunter-ms commented on daprdocs/content/en/reference/components-reference/supported-pubsub/setup-rocketmq.md
> +| consumerGroup                         |    N     | Consumer group name, it is  recommended. if producerGroup is null，groupName is used. |                                                         | d
```suggestion
| consumerGroup                         |    N     | Consumer group name. Recommend. If `producerGroup` is `null`，`groupName` is used. |                                                         | `dapr-rocketmq-test-g-c `                     |
```

2022-11-10 17:19 UTC, hhunter-ms commented on daprdocs/content/en/reference/components-reference/supported-pubsub/setup-rocketmq.md
> +| producerGroup (consumerID)            |    N     | Producer group Name, it is  recommended. if producerGroup is null，consumerID is used, if consumerID also is null, groupName is used. |
```suggestion
| producerGroup (consumerID)            |    N     | Producer group name. Recommended. If `producerGroup` is `null`，`consumerID` is used. If `consumerID` also is null, `groupName` is used. |                                                         | dapr-`rocketmq-test-g-p`                      |
```

2022-11-10 17:19 UTC, hhunter-ms commented on daprdocs/content/en/reference/components-reference/supported-pubsub/setup-rocketmq.md
> +| groupName                             |    N     | Consumer/Producer group name, it is Deprecated               |                                                         | dapr-rocketmq-test-g
```suggestion
| groupName                             |    N     | Consumer/Producer group name. **Depreciated**.               |                                                         | `dapr-rocketmq-test-g`                         |
```

2022-11-10 17:19 UTC, hhunter-ms commented on daprdocs/content/en/reference/components-reference/supported-pubsub/setup-rocketmq.md
> +| groupName                             |    N     | Consumer/Producer group name, it is Deprecated               |                                                         | dapr-rocketmq-test-g
@msfussell @greenie-msft just want to check - how do we typically handle a depreciated metadata field in the docs. Do we remove it, or ok to mention it like above?

2022-11-10 17:19 UTC, hhunter-ms commented on daprdocs/content/en/reference/components-reference/supported-pubsub/setup-rocketmq.md
> +| nameSpace                             |    N     | rocketmq namespace                                           |                                                         | dapr-rocketmq
```suggestion
| nameSpace                             |    N     | RocketMQ namespace                                           |                                                         | `dapr-rocketmq`                                |
```

2022-11-10 17:19 UTC, hhunter-ms commented on daprdocs/content/en/reference/components-reference/supported-pubsub/setup-rocketmq.md
> +| nameServerDomain                      |    N     | rocketmq name server domain                                  |                                                         | https://my-app.net:8080/n
```suggestion
| nameServerDomain                      |    N     | RocketMQ name server domain                                  |                                                         | `https://my-app.net:8080/nsaddr`               |
```

2022-11-10 17:19 UTC, hhunter-ms commented on daprdocs/content/en/reference/components-reference/supported-pubsub/setup-rocketmq.md
> +| nameServer                            |    N     | rocketmq name server, It's separated by "," or ";"           |                                                         | 127.0.0.1:9876;127.0.0.2:
```suggestion
| nameServer                            |    N     | RocketMQ name server, separated by "," or ";"           |                                                         | 127.0.0.1:9876;127.0.0.2:9877,127.0.0.3:9877 |
```

2022-11-10 17:19 UTC, hhunter-ms commented on daprdocs/content/en/reference/components-reference/supported-pubsub/setup-rocketmq.md
> +| retries                               |    N     | Retry times to send msg to broker                            | 3                                                       | 3
```suggestion
| retries                               |    N     | Number of retries to send a message to broker                            | 3                                                       | 3                                            |
```

2022-11-10 17:19 UTC, hhunter-ms commented on daprdocs/content/en/reference/components-reference/supported-pubsub/setup-rocketmq.md
> +| producerQueueSelector (queueSelector) |    N     | Producer Queue selector. There are five implementations of queue selector，hash, random, manual, roundRobin, dapr(default)，respectively. | dapr
```suggestion
| producerQueueSelector (queueSelector) |    N     | Producer Queue selector. There are five implementations of queue selector: `hash`, `random`, `manual`, `roundRobin`, `dapr`. | `dapr`                                                    | `hash`                                         |
```

2022-11-10 17:19 UTC, hhunter-ms commented on daprdocs/content/en/reference/components-reference/supported-pubsub/setup-rocketmq.md
> +| consumerModel                         |    N     | Message model defines the way how messages are delivered to each consumer clients. RocketMQ supports two message models: clustering and broadcasti
```suggestion
| consumerModel                         |    N     | Message model that defines how messages are delivered to each consumer client. RocketMQ supports two message models: `clustering` and `broadcasting`. | `clustering`                                              | `broadcasting`                                 |
```

2022-11-10 17:19 UTC, hhunter-ms commented on daprdocs/content/en/reference/components-reference/supported-pubsub/setup-rocketmq.md
> +| fromWhere (consumeFromWhere)          |    N     | Consuming point on consumer booting. There are three consuming points: CONSUME_FROM_LAST_OFFSET, CONSUME_FROM_FIRST_OFFSET, CONSUME_FROM_TIMESTAMP
```suggestion
| fromWhere (consumeFromWhere)          |    N     | Consuming point on consumer booting. There are three consuming points: `CONSUME_FROM_LAST_OFFSET`, `CONSUME_FROM_FIRST_OFFSET`, `CONSUME_FROM_TIMESTAMP` | `CONSUME_FROM_LAST_OFFSET`                                   | `CONSUME_FROM_LAST_OFFSET`                     |
```

2022-11-10 17:19 UTC, hhunter-ms commented on daprdocs/content/en/reference/components-reference/supported-pubsub/setup-rocketmq.md
> +| consumeOrderly                        |    N     | Whether it is an ordered message using FIFO order. This field defaults to false. | false                                                   | false
```suggestion
| consumeOrderly                        |    N     | Determines if it's an ordered message using FIFO order.  | `false`                                                   | `false`                                        |
```

2022-11-10 17:19 UTC, hhunter-ms commented on daprdocs/content/en/reference/components-reference/supported-pubsub/setup-rocketmq.md
> +| consumeMessageBatchMaxSize            |    N     | Batch consumption size out of range [1, 1024]                | 512                                                     | 10
```suggestion
| consumeMessageBatchMaxSize            |    N     | Batch consumption size out of range `[1, 1024]`                | `512`                                                     | `10`                                           |
```

2022-11-10 17:19 UTC, hhunter-ms commented on daprdocs/content/en/reference/components-reference/supported-pubsub/setup-rocketmq.md
> +| maxReconsumeTimes                     |    N     | Max re-consume times. -1 means 16 times. If messages are re-consumed more than {@link maxReconsumeTimes} before Success, it's be directed to a del
```suggestion
| maxReconsumeTimes                     |    N     | Max re-consume times. `-1` means 16 times. If messages are re-consumed more than {@link maxReconsumeTimes} before success, they'll be directed to a deletion queue. | Orderly message is `MaxInt32`; Concurrently message is `16` | `16`                                          |
```

2022-11-10 17:19 UTC, hhunter-ms commented on daprdocs/content/en/reference/components-reference/supported-pubsub/setup-rocketmq.md
> +| autoCommit                            |    N     | auto commit                                                  | true                                                    | false
```suggestion
| autoCommit                            |    N     | Enable auto commit                                                  | `true`                                                    | `false`                                        |
```

2022-11-10 17:19 UTC, hhunter-ms commented on daprdocs/content/en/reference/components-reference/supported-pubsub/setup-rocketmq.md
> +| pullInterval                          |    N     | Message pull Interval                                        | 100                                                     | 100
```suggestion
| pullInterval                          |    N     | Message pull interval                                        | `100`                                                     | `100`                                          |
```

2022-11-10 17:19 UTC, hhunter-ms commented on daprdocs/content/en/reference/components-reference/supported-pubsub/setup-rocketmq.md
> +| pullBatchSize                         |    N     | The number of messages pulled from the broker at a time. if pullBatchSize is null，ConsumerBatchSize is used. pullBatchSize out of range [1, 1024]
```suggestion
| pullBatchSize                         |    N     | The number of messages pulled from the broker at a time. If `pullBatchSize` is `null`, use `ConsumerBatchSize`. `pullBatchSize` out of range `[1, 1024]` | `32`                                                      | `10`                                           |
```

2022-11-10 17:19 UTC, hhunter-ms commented on daprdocs/content/en/reference/components-reference/supported-pubsub/setup-rocketmq.md
> +| content-type                          |    N     | Message content-type, e.g., `"application/cloudevents+json; charset=utf-8"`, `"application/octet-stream"`. This field defaults to "text/plain" |
```suggestion
| content-type                          |    N     | Message content type.  | `"text/plain"`                                                        | `"application/cloudevents+json; charset=utf-8"`, `"application/octet-stream"`                              |
```

2022-11-10 17:19 UTC, hhunter-ms commented on daprdocs/content/en/reference/components-reference/supported-pubsub/setup-rocketmq.md
> +| logLevel                              |    N     | Log level                                                    | warn                                                    | Info
```suggestion
| logLevel                              |    N     | Log level                                                    | `warn`                                                    | `info`                                         |
```

2022-11-10 17:19 UTC, hhunter-ms commented on daprdocs/content/en/reference/components-reference/supported-pubsub/setup-rocketmq.md
> +| sendTimeOut                           |    N     | send msg timeout to connect rocketmq's broker, nanoseconds. It is deprecated. | 3 seconds                                               | 10000000
```suggestion
| sendTimeOut                           |    N     | Send message timeout to connect RocketMQ's broker, measured in nanoseconds. **Deprecated**. | 3 seconds                                               | `10000000000`                                  |
```

For default, just checking - 3 seconds or 3 nanoseconds?

2022-11-10 17:19 UTC, hhunter-ms commented on daprdocs/content/en/reference/components-reference/supported-pubsub/setup-rocketmq.md
> +| sendTimeOutSec                        |    N     | Timeout duration for publishing a message in seconds. if sendTimeOutSec is null，sendTimeOut is used. | 3 seconds
```suggestion
| sendTimeOutSec                        |    N     | Timeout duration for publishing a message in seconds. If `sendTimeOutSec` is `null`, `sendTimeOut` is used. | 3 seconds                                               | `3`                                            |
```

2022-11-10 17:19 UTC, hhunter-ms commented on daprdocs/content/en/reference/components-reference/supported-pubsub/setup-rocketmq.md
> +| mspProperties                         |    N     | The RocketMQ message properties in this collection are passed to the APP in Data Separate multiple properties with "," |
```suggestion
| mspProperties                         |    N     | The RocketMQ message properties in this collection are passed to the APP in Data Separate multiple properties with "," |                                                         | `key,mkey`                                     |
```

2022-11-10 17:19 UTC, hhunter-ms commented on daprdocs/content/en/reference/components-reference/supported-pubsub/setup-rocketmq.md
> +| consumerBatchSize                |    N     | The number of messages pulled from the broker at a time  | 32                       |
```suggestion
| consumerBatchSize                |    N     | The number of messages pulled from the broker at a time  | `32`                       |
```

2022-11-10 17:19 UTC, hhunter-ms commented on daprdocs/content/en/reference/components-reference/supported-pubsub/setup-rocketmq.md
> +The dapr rocketmq component contains five Queue selectors. These are HashQueueSelector, RandomQueueSelector, RoundRobinQueueSelector, ManualQueueSelector, DaprQueueSelector. Four of these are provide
```suggestion
The RocketMQ component contains a total of five queue selectors. The RocketMQ client provides the following queue selectors:
- `HashQueueSelector`
- `RandomQueueSelector`
- `RoundRobinQueueSelector`
- `ManualQueueSelector`

To learn more about these RocketMQ client queue selectors, read the [RocketMQ documentation](https://rocketmq.apache.org/docs).

The Dapr RocketMQ component implements the following queue selector:
- `DaprQueueSelector`

 This article focuses on the design of `DaprQueueSelector`.
```

2022-11-10 17:19 UTC, hhunter-ms commented on daprdocs/content/en/reference/components-reference/supported-pubsub/setup-rocketmq.md
> +DaprQueueSelector integrates three Queue selectors: HashQueueSelector, RoundRobinQueueSelector, ManualQueueSelector.
```suggestion
`DaprQueueSelector` integrates three queue selectors: 
- `HashQueueSelector`
- `RoundRobinQueueSelector`
- `ManualQueueSelector`
```

2022-11-10 17:19 UTC, hhunter-ms commented on daprdocs/content/en/reference/components-reference/supported-pubsub/setup-rocketmq.md
> +First, it gets the queue id from the request parameter. You can set the queue id by doing the following.
```suggestion
`DaprQueueSelector` gets the queue id from the request parameter. You can set the queue id by running the following:
```

2022-11-10 17:19 UTC, hhunter-ms commented on daprdocs/content/en/reference/components-reference/supported-pubsub/setup-rocketmq.md
> +That's how ManualQueueSelector is implemented. The method above also works for ManualQueueSelector.
```suggestion
The `ManualQueueSelector` is implemented using the method above.
```

2022-11-10 17:19 UTC, hhunter-ms commented on daprdocs/content/en/reference/components-reference/supported-pubsub/setup-rocketmq.md
> +Second, it will try to get a ShardingKey, and hash the ShardingKey to determine the queue id if it exists.
```suggestion
Next, the `DaprQueueSelector` tries to:
- Get a `ShardingKey`
- Hash the `ShardingKey` to determine the queue id.
```

2022-11-10 17:19 UTC, hhunter-ms commented on daprdocs/content/en/reference/components-reference/supported-pubsub/setup-rocketmq.md
> +You can set the ShardingKey by doing the following.
```suggestion
You can set the `ShardingKey` by doing the following:
```

2022-11-10 17:19 UTC, hhunter-ms commented on daprdocs/content/en/reference/components-reference/supported-pubsub/setup-rocketmq.md
> +If the shardingkey does not exist, the RoundRobin algorithm is used to determine the queue id.
```suggestion
If the `ShardingKey` does not exist, the `RoundRobin` algorithm is used to determine the queue id.
```

2022-11-11 02:01 UTC, jinjianfeng-chn commented
> Grammar/readability pass

Thank you very much for helping me correct the document.  😁

2022-12-08 23:00 UTC, hhunter-ms approved these changes

2022-12-14 00:36 UTC, merged