Change Cron Binding from `input/output` to `input` binding
dapr/docs pull request #2971
Opened 2022-11-24 10:52 UTC by sarsharma

Signed-off-by: Sarthak Sharma <sartsharma@microsoft.com>

Thank you for helping make the Dapr documentation better!

**Please follow this checklist before submitting:**
- [x] Commits are signed with Developer Certificate of Origin (DCO - [learn more](https://docs.dapr.io/contributing/contributing-overview/#developer-certificate-of-origin-signing-your-work))
- [x] [Read the contribution guide](https://docs.dapr.io/contributing/docs-contrib/contributing-docs/)
- [ ] Commands include options for Linux, MacOS, and Windows within codetabs
- [ ] New file and folder names are globally unique
- [ ] Page references use shortcodes instead of markdown or URL links
- [ ] Images use HTML style and have alternative text
- [ ] Places where multiple code/command options are given have codetabs

In addition, please fill out the following to help reviewers understand this pull request:

## Description

Changing cron binding to input only binding to certify it as a stable component 
See linked issue and Certification Tests PR for reference

Also fix Kubernetes Events Binding wrongly listing having output binding support

## Issue reference

https://github.com/dapr/components-contrib/issues/2308
https://github.com/dapr/components-contrib/pull/2191/

2022-12-05 09:54 UTC, mukundansundar commented on daprdocs/data/components/bindings/generic.yaml
>    since: "1.0"
Change since and state also to Beta or stable ?? From 1.10

2022-12-07 10:15 UTC, mukundansundar approved these changes

2022-12-07 10:15 UTC, mukundansundar requested changes
Change base to 1.10

2022-12-07 10:42 UTC, sarsharma commented
Changed base to v1.10 , DCO seems to be failing due to older commits in v1.10 branch

2022-12-07 10:57 UTC, mukundansundar commented
Can you rebase with a single commit on top of v1.10....?

2022-12-07 13:14 UTC, mukundansundar approved these changes

2022-12-08 22:31 UTC, hhunter-ms approved these changes
lgtm

2022-12-08 22:34 UTC, merged