Improve Hashicorp Vault documentation on CA certificates.
dapr/docs pull request #2988
Opened 2022-12-02 23:50 UTC by tmacam

**Please follow this checklist before submitting:**
- [ ] Commits are signed with Developer Certificate of Origin (DCO - [learn more](https://docs.dapr.io/contributing/contributing-overview/#developer-certificate-of-origin-signing-your-work))
- [ ] [Read the contribution guide](https://docs.dapr.io/contributing/docs-contrib/contributing-docs/)
- [ ] Commands include options for Linux, MacOS, and Windows within codetabs
- [ ] New file and folder names are globally unique
- [ ] Page references use shortcodes instead of markdown or URL links
- [ ] Images use HTML style and have alternative text
- [ ] Places where multiple code/command options are given have codetabs

In addition, please fill out the following to help reviewers understand this pull request:

## Description

Hashicorp Vault component documentation for CA related fields (`caPem`, `caCert` and `caPath`) does not describe the precedence among those flags and a big ambiguous on what those flags mean.

This PR tries to alleviate that.

## Issue reference

2022-12-08 22:55 UTC, hhunter-ms requested changes
Quick grammar pass

2022-12-08 22:55 UTC, hhunter-ms commented on daprdocs/content/en/reference/components-reference/supported-secret-stores/hashicorp-vault.md
> +| caPem | N | The inlined contents of the CA certificate to use, in PEM format. If defined, takes precedence over `caPath` and `caCert`.  | See bellow |
```suggestion
| caPem | N | The inlined contents of the CA certificate to use, in PEM format. If defined, takes precedence over `caPath` and `caCert`.  | See below |
```

2022-12-08 22:55 UTC, hhunter-ms commented on daprdocs/content/en/reference/components-reference/supported-secret-stores/hashicorp-vault.md
> +The fields `skipVerify`, `tlsServerName`, `caCert`, `caPath` and `caPem` control if and how Dapr will verify vault server's certificate while connecting using TLS/HTTPS.
```suggestion
The fields `skipVerify`, `tlsServerName`, `caCert`, `caPath`, and `caPem` control if and how Dapr verifies the vault server's certificate while connecting using TLS/HTTPS.
```

2022-12-08 22:55 UTC, hhunter-ms commented on daprdocs/content/en/reference/components-reference/supported-secret-stores/hashicorp-vault.md
> +The value of the field `caPem` should be the contents of the PEM CA certificate you want to use. Given PEM certificates are made of multiple lines, defining that value might seem challenging at first
```suggestion
The `caPem` field value should be the contents of the PEM CA certificate you want to use. Given PEM certificates are made of multiple lines, defining that value might seem challenging at first. YAML allows for a few ways of [defining a multiline values](https://yaml-multiline.info/).
```

2022-12-08 22:55 UTC, hhunter-ms commented on daprdocs/content/en/reference/components-reference/supported-secret-stores/hashicorp-vault.md
> +Bellow, we show one way to define a `caPem` field.
```suggestion
Below is one way to define a `caPem` field.
```

2022-12-09 22:14 UTC, tmacam commented
> Quick grammar pass

Hey, @hhunter-ms. Thanks for the review.  I've accepted your suggestions and merged the HEAD of 1.9 back into this PR.

2022-12-10 02:38 UTC, hhunter-ms approved these changes
lgtm

2022-12-14 01:35 UTC, merged