[HTTP Binding]: adding metadata options for client auth during mTLS
dapr/docs pull request #3050
Opened 2023-01-11 06:21 UTC by pravinpushkar

Signed-off-by: Pravin Pushkar <ppushkar@microsoft.com>

Thank you for helping make the Dapr documentation better!

## Description

Added metadata options for client cert verification.

## Issue reference

https://github.com/dapr/components-contrib/pull/2399

2023-01-17 20:46 UTC, hhunter-ms requested changes

2023-01-17 20:46 UTC, hhunter-ms commented on daprdocs/content/en/reference/components-reference/supported-bindings/http.md
> +The HTTP binding can also be configured to use mTLS or client TLS authentication along with HTTPS by providing the `MTLSRootCA`, `MTLSClientCert` and `MTLSClientKey` metadata fields in the binding co
```suggestion
You can configure the HTTP binding to use mTLS or client TLS authentication along with HTTPS by providing the `MTLSRootCA`, `MTLSClientCert`, and `MTLSClientKey` metadata fields in the binding component.
```

2023-01-17 20:46 UTC, hhunter-ms commented on daprdocs/content/en/reference/components-reference/supported-bindings/http.md
> +These fields can be passed as a file path or as a pem encoded strings. If the file path is provided, the file will be read and the contents will be used. If the pem encoded string is provided, the st
```suggestion
These fields can be passed as a file path or as a pem encoded string. 
- If the file path is provided, the file will be read and the contents will be used. 
- If the pem encoded string is provided, the string will be used as is.
```

2023-01-17 20:46 UTC, hhunter-ms commented on daprdocs/content/en/reference/components-reference/supported-bindings/http.md
> +When these fields are configured, dapr sidecar will use the provided certificate to authenticate itself with the server during the TLS handshake process.
```suggestion
When these fields are configured, the Dapr sidecar will use the provided certificate to authenticate itself with the server during the TLS handshake process.
```

2023-01-17 20:46 UTC, hhunter-ms commented on daprdocs/content/en/reference/components-reference/supported-bindings/http.md
> +This can be used when the server with which the HTTP binding is configured to communicate with, requires mTLS or client TLS authentication.
```suggestion
You can use this when the server with which the HTTP binding is configured to communicate requires mTLS or client TLS authentication.
```

2023-01-18 17:23 UTC, hhunter-ms approved these changes

2023-01-24 02:39 UTC, msfussell commented on daprdocs/content/en/reference/components-reference/supported-bindings/http.md
> +- If the file path is provided, the file will be read and the contents will be used.
```suggestion
- If the file path is provided, the file is read and the contents are used. 
```

2023-01-24 02:39 UTC, msfussell commented on daprdocs/content/en/reference/components-reference/supported-bindings/http.md
> +- If the pem encoded string is provided, the string will be used as is.
```suggestion
- If the pem encoded string is provided, the string is used as is.
```

2023-01-24 02:40 UTC, msfussell commented on daprdocs/content/en/reference/components-reference/supported-bindings/http.md
> +When these fields are configured, the Dapr sidecar will use the provided certificate to authenticate itself with the server during the TLS handshake process.
```suggestion
When these fields are configured, the Dapr sidecar uses the provided certificate to authenticate itself with the server during the TLS handshake process.
```

2023-01-24 03:40 UTC, msfussell commented on daprdocs/content/en/reference/components-reference/supported-bindings/http.md
> +| MTLSRootCA         | N        | Output |Path to root ca certificate or pem encoded string |
Can you provide examples for the paths. Always good to clarify if this can be absolute path or relative path and if relative, relative to what.

2023-01-31 19:33 UTC, yaron2 approved these changes

2023-01-31 19:34 UTC, merged