Adds a note about the maximum version skew when upgrading dapr
dapr/docs pull request #3081
Opened 2023-01-24 14:58 UTC by JoshVanL

In addition, please fill out the following to help reviewers understand this pull request:

## Description

I didn't previously find this written down in the docs so have made it explicit in the upgrade guide.

## Issue reference

2023-01-31 22:24 UTC, hhunter-ms requested changes
Quick edit

2023-01-31 22:24 UTC, hhunter-ms commented on daprdocs/content/en/operations/hosting/kubernetes/kubernetes-upgrade.md
> +  *Note: Dapr only has a seamless guarantee when upgrading patch versions in a
```suggestion
{{% alert title="Note" color="primary" %}}
Dapr only has a seamless guarantee when upgrading patch versions in a single minor version, or upgrading from one minor version to the next. For example, upgrading from `v1.6.0` to `v1.6.4` or `v1.6.4` to `v1.7.0` is guaranteed to be seamless. Upgrading more than one minor version at a time is best effort.
{{% /alert %}}
```

Just wrapping in shortcode alert and putting note on one line.

2023-01-31 22:24 UTC, hhunter-ms commented on daprdocs/content/en/operations/hosting/kubernetes/kubernetes-upgrade.md
> +  single minor version, or upgrading from one minor version to the next. For
```suggestion
```

2023-01-31 22:24 UTC, hhunter-ms commented on daprdocs/content/en/operations/hosting/kubernetes/kubernetes-upgrade.md
> +  example, upgrading from `v1.6.0` to `v1.6.4` or `v1.6.4` to `v1.7.0` is
```suggestion
```

2023-01-31 22:24 UTC, hhunter-ms commented on daprdocs/content/en/operations/hosting/kubernetes/kubernetes-upgrade.md
> +  guaranteed to be seamless.
```suggestion
```

2023-01-31 22:24 UTC, hhunter-ms commented on daprdocs/content/en/operations/hosting/kubernetes/kubernetes-upgrade.md
> +  Upgrading more than one minor version at a time is best effort.*
```suggestion
```

2023-02-01 19:06 UTC, msfussell commented on daprdocs/content/en/operations/hosting/kubernetes/kubernetes-upgrade.md
> +{{% alert title="Note" color="primary" %}}
I like this text, however it is best to move this to this section in the docs https://docs.dapr.io/operations/support/support-release-policy/#upgrade-paths that covers upgrades and then putting a reference link to this from this Kubernetes document. 

I would also change 
"guaranteed to be seamless" to "guaranteed tested"
 and 
 "Upgrading more than one minor version at a time is best effort" to "Upgrading more than one minor version at a time is untested and treated as best effort"

2023-02-03 00:54 UTC, msfussell commented on daprdocs/content/en/operations/hosting/kubernetes/kubernetes-upgrade.md
> +Please refer to the [Dapr version policy]({{< ref "support-release-policy.md#upgrade-paths" >}}) for guidance on which versions of Dapr can be upgraded to which versions.
```suggestion
Refer to the [Dapr version policy]({{< ref "support-release-policy.md#upgrade-paths" >}}) for guidance on which versions of Dapr can be upgraded to which versions.
```

2023-02-03 01:41 UTC, hhunter-ms approved these changes

2023-02-08 23:24 UTC, merged