Docs for SQLite state store
dapr/docs pull request #3099
Opened 2023-01-30 21:44 UTC by ItalyPaleAle

Fixes #3085

2023-02-01 02:18 UTC, msfussell commented on daprdocs/content/en/reference/components-reference/supported-state-stores/setup-sqlite.md
> +- The path is interpreted by the SQLite library, so it's possible to pass additional options to the SQLite driver using "URI options". For example, `"path/to/data.db?mode=ro"` opens the database at p
```suggestion
- The path is interpreted by the SQLite library, so it's possible to pass additional options to the SQLite driver using "URI options". For example, `"path/to/data.db?mode=ro"` opens the database at path `path/to/data.db` in read-only mode. Refer to the SQLite documentation for all supported [URI options](https://www.sqlite.org/uri.html).
```

2023-02-01 02:18 UTC, msfussell commented on daprdocs/content/en/reference/components-reference/supported-state-stores/setup-sqlite.md
> +- Normally, this is the path to a file on disk, relative or absolute. For example: `"data.db"` or `"/mnt/data/mydata.db"`.
It is always good to be clear that a path is relative to what? Relative to the location of the component manifest? 

I would add an example of saying that, if you are using local development then you can place the sqllite.yaml file and the data.db file into the default components folder https://docs.dapr.io/getting-started/install-dapr-selfhost/#step-5-verify-components-directory-has-been-initialized

2023-02-01 02:18 UTC, msfussell commented on daprdocs/content/en/reference/components-reference/supported-state-stores/setup-sqlite.md
> +
Worth adding any instructions on installing SQLLite locally or using a containerized version on K8s? For example having a Setup section like this https://docs.dapr.io/reference/components-reference/supported-state-stores/setup-memcached/#setup-memcached

Maybe at least say that you can create a DB file in the local development folder, given this DB is so easy to use (especially on a Mac)

2023-02-01 04:48 UTC, ItalyPaleAle commented on daprdocs/content/en/reference/components-reference/supported-state-stores/setup-sqlite.md
> +- Normally, this is the path to a file on disk, relative or absolute. For example: `"data.db"` or `"/mnt/data/mydata.db"`.
It’s actually relative to the current working directory, that’s what we can say. Definitely not the path of the component manifest (very unlikely at least).

2023-02-01 04:50 UTC, ItalyPaleAle commented on daprdocs/content/en/reference/components-reference/supported-state-stores/setup-sqlite.md
> +
No need to install SQLite :) The great thing about SQLite (and why it’s the most widely-used DB in the world by a large margin - literally [over 1 trillion](https://sqlite.org/index.html) of them) is that it’s entirely contained within the application. No external service or process to install or start.

2023-02-01 21:54 UTC, msfussell commented on daprdocs/content/en/reference/components-reference/supported-state-stores/setup-sqlite.md
> +- Normally, this is the path to a file on disk, relative or absolute. For example: `"data.db"` or `"/mnt/data/mydata.db"`.
The working directory for the executable?

2023-02-01 22:09 UTC, ItalyPaleAle commented on daprdocs/content/en/reference/components-reference/supported-state-stores/setup-sqlite.md
> +- Normally, this is the path to a file on disk, relative or absolute. For example: `"data.db"` or `"/mnt/data/mydata.db"`.
If the component is loaded and the database is not found, a new DB is created. That's default SQLite behavior.

I'll update to specify it's the CWD.

2023-02-01 22:12 UTC, ItalyPaleAle commented on daprdocs/content/en/reference/components-reference/supported-state-stores/setup-sqlite.md
> +- Normally, this is the path to a file on disk, relative or absolute. For example: `"data.db"` or `"/mnt/data/mydata.db"`.
Updated

2023-02-02 19:57 UTC, hhunter-ms requested changes

2023-02-02 19:57 UTC, hhunter-ms commented on daprdocs/content/en/reference/components-reference/supported-state-stores/setup-sqlite.md
> +Create a file called `sqlite.yaml`, paste the following and replace the `<CONNECTION STRING>` value with your connection string, which is the path to a file on disk.
```suggestion
Create a file called `sqlite.yaml`, paste the following, and replace the `<CONNECTION STRING>` value with your connection string, which is the path to a file on disk.
```

2023-02-02 19:57 UTC, hhunter-ms commented on daprdocs/content/en/reference/components-reference/supported-state-stores/setup-sqlite.md
> +- The path is interpreted by the SQLite library, so it's possible to pass additional options to the SQLite driver using "URI options". For example, `"path/to/data.db?mode=ro"` opens the database at p
```suggestion
- The path is interpreted by the SQLite library, so it's possible to pass additional options to the SQLite driver using "URI options". For example: `"path/to/data.db?mode=ro"` opens the database at path `path/to/data.db` in read-only mode. [Refer to the SQLite documentation for all supported URI options](https://www.sqlite.org/uri.html).
```

2023-02-02 19:57 UTC, hhunter-ms commented on daprdocs/content/en/reference/components-reference/supported-state-stores/setup-sqlite.md
> +This state store supports [Time-To-Live (TTL)](https://docs.dapr.io/developing-applications/building-blocks/state-management/state-store-ttl/) for records stored with Dapr. When storing data using Da
```suggestion
This state store supports [Time-To-Live (TTL)]({{< ref state-store-ttl.md >}}) for records stored with Dapr. When storing data using Dapr, you can set the `ttlInSeconds` metadata property to indicate when the data should be considered "expired".
```

2023-02-02 19:57 UTC, hhunter-ms commented on daprdocs/content/en/reference/components-reference/supported-state-stores/setup-sqlite.md
> +The interval at which the deletion of expired records happens is set with the `cleanupIntervalInSeconds` metadata property, which defaults to 3600 seconds (that is, 1 hour).
```suggestion
The `cleanupIntervalInSeconds` metadata property sets the expired records deletion interval, which defaults to 3600 seconds (that is, 1 hour).
```

2023-02-02 19:57 UTC, hhunter-ms commented on daprdocs/content/en/reference/components-reference/supported-state-stores/setup-sqlite.md
> +The column in the state table where the expiration date for records is stored in, `expiration_time`, **does not have an index by default**, so each periodic cleanup must perform a full-table scan. If
```suggestion
The `expiration_time` column in the state table, where the expiration date for records is stored, **does not have an index by default**, so each periodic cleanup must perform a full-table scan. If you have a table with a very large number of records, and only some of them use a TTL, you may find it useful to create an index on that column. Assuming that your state table name is `state` (the default), you can use this query:
```

2023-02-02 20:29 UTC, hhunter-ms approved these changes

2023-02-03 01:33 UTC, ItalyPaleAle commented
I've made one additional change to correct information about using URI options

2023-02-08 03:48 UTC, merged