Update Event Hub components docs
dapr/docs pull request #3103
Opened 2023-01-31 01:10 UTC by ItalyPaleAle

Fixes #3083

2023-02-01 23:34 UTC, greenie-msft approved these changes

2023-02-02 19:07 UTC, hhunter-ms requested changes

2023-02-02 19:07 UTC, hhunter-ms commented on daprdocs/content/en/reference/components-reference/supported-bindings/eventhubs.md
>  The Azure Event Hubs pubsub component supports authentication using all Azure Active Directory mechanisms. For further information and the relevant component metadata fields to provide depending on t
```suggestion
The Azure Event Hubs pub/sub component supports authentication using all Azure Active Directory mechanisms. For further information and the relevant component metadata fields to provide depending on the choice of AAD authentication mechanism, see the [docs for authenticating to Azure]({{< ref authenticating-azure.md >}}).
```

2023-02-02 19:07 UTC, hhunter-ms commented on daprdocs/content/en/reference/components-reference/supported-pubsub/setup-azure-eventhubs.md
> +To setup an Azure Event Hubs pubsub, create a component of type `pubsub.azure.eventhubs`. See [this guide]({{< ref "howto-publish-subscribe.md#step-1-setup-the-pubsub-component" >}}) on how to create
```suggestion
To setup an Azure Event Hubs pub/sub, create a component of type `pubsub.azure.eventhubs`. See [this guide]({{< ref "howto-publish-subscribe.md#step-1-setup-the-pubsub-component" >}}) on how to create and apply a pub/sub configuration.
```

2023-02-02 19:07 UTC, hhunter-ms commented on daprdocs/content/en/reference/components-reference/supported-pubsub/setup-azure-eventhubs.md
>  The Azure Event Hubs pubsub component supports authentication using all Azure Active Directory mechanisms. For further information and the relevant component metadata fields to provide depending on t
```suggestion
The Azure Event Hubs pub/sub component supports authentication using all Azure Active Directory mechanisms. For further information and the relevant component metadata fields to provide depending on the choice of AAD authentication mechanism, see the [docs for authenticating to Azure]({{< ref authenticating-azure.md >}}).
```

2023-02-02 19:07 UTC, hhunter-ms commented on daprdocs/content/en/reference/components-reference/supported-pubsub/setup-azure-eventhubs.md
> +When entity management is enabled in the metadata, as long as the application has the right role and permissions to manipulate the Event Hub namespace, Dapr can create the Event Hub and consumer grou
```suggestion
When entity management is enabled in the metadata, as long as the application has the right role and permissions to manipulate the Event Hub namespace, Dapr can automatically create the Event Hub and consumer group for you.
```

2023-02-02 19:07 UTC, hhunter-ms commented on daprdocs/content/en/reference/components-reference/supported-pubsub/setup-azure-eventhubs.md
> +Note: Dapr passes the name of the consumer group to the Event Hub, so this is not supplied in the metadata.
```suggestion
> Dapr passes the name of the consumer group to the Event Hub, so this is not supplied in the metadata.
```

2023-02-02 20:25 UTC, hhunter-ms approved these changes

2023-02-02 20:25 UTC, merged