Subscribe with StatefulSet
dapr/docs pull request #3159
Opened 2023-02-10 05:22 UTC by artursouza

Thank you for helping make the Dapr documentation better!

**Please follow this checklist before submitting:**
- [ ] Commits are signed with Developer Certificate of Origin (DCO - [learn more](https://docs.dapr.io/contributing/contributing-overview/#developer-certificate-of-origin-signing-your-work))
- [ ] [Read the contribution guide](https://docs.dapr.io/contributing/docs-contrib/contributing-docs/)
- [ ] Commands include options for Linux, MacOS, and Windows within codetabs
- [ ] New file and folder names are globally unique
- [ ] Page references use shortcodes instead of markdown or URL links
- [ ] Images use HTML style and have alternative text
- [ ] Places where multiple code/command options are given have codetabs

In addition, please fill out the following to help reviewers understand this pull request:

## Description

Explains how to use StatefulSets and pubsub subscribe

## Issue reference

Closes: #2599

2023-02-13 16:05 UTC, hhunter-ms requested changes
quick pass

2023-02-13 16:05 UTC, hhunter-ms commented on daprdocs/content/en/developing-applications/building-blocks/pubsub/howto-subscribe-statefulset.md
> +[StatefulSets](https://kubernetes.io/docs/concepts/workloads/controllers/statefulset/) allows deployment of stateful applications on Kubernetes by keeping a sticky identity for each Pod, in contrast
```suggestion
Unlike Deployments, where Pods are ephemeral, [StatefulSets](https://kubernetes.io/docs/concepts/workloads/controllers/statefulset/) allows deployment of stateful applications on Kubernetes by keeping a sticky identity for each Pod.
```

2023-02-13 16:05 UTC, hhunter-ms commented on daprdocs/content/en/developing-applications/building-blocks/pubsub/howto-subscribe-statefulset.md
> +See an example of a StatefulSet with Dapr:
```suggestion
Below is an example of a StatefulSet with Dapr:
```

2023-02-13 16:05 UTC, hhunter-ms commented on daprdocs/content/en/developing-applications/building-blocks/pubsub/howto-subscribe-statefulset.md
> +When subscribing to a pub/sub topic via Dapr, the application can define the `consumerID`, which is used to determine the subscriber's position in the queue or topic. With StatefulSets, developers ca
```suggestion
When subscribing to a pub/sub topic via Dapr, the application can define the `consumerID`, which determines the subscriber's position in the queue or topic. With the StatefulSets sticky identity of Pods, you can have a unique `consumerID` per Pod, allowing each horizontal scale of the subscriber application. Dapr keeps track of the name of each Pod, which can be used when declaring components using the `{podName}` marker.
```

2023-02-13 16:05 UTC, hhunter-ms commented on daprdocs/content/en/developing-applications/building-blocks/pubsub/howto-subscribe-statefulset.md
> +On scaling the number of subscribers of a given topic, each component in Dapr has its unique settings to determine the behavior. Usually, there are two options for multiple consumers: broadcast or sh
```suggestion
On scaling the number of subscribers of a given topic, each Dapr component has unique settings that determine the behavior. Usually, there are two options for multiple consumers:

 - Broadcast: each message published to the topic will be consumed by all subscribers.
 - Shared: a message is consumed by any subscriber (but not all).
```

2023-02-13 16:05 UTC, hhunter-ms commented on daprdocs/content/en/developing-applications/building-blocks/pubsub/howto-subscribe-statefulset.md
> +Kafka isolates each subscriber by `consumerID` with its own position in the topic. When an instance restarts, it reuses the same `consumerID` and continues from its last known position, without skipp
```suggestion
Kafka isolates each subscriber by `consumerID` with its own position in the topic. When an instance restarts, it reuses the same `consumerID` and continues from its last known position, without skipping messages. The component below demonstrates how a Kafka component can be used by multiple Pods:
```

2023-02-15 17:25 UTC, hhunter-ms approved these changes

2023-02-15 17:30 UTC, merged

2023-02-15 17:51 UTC, msfussell commented on daprdocs/content/en/developing-applications/building-blocks/pubsub/howto-subscribe-statefulset.md
> +title: "How to: Subscribe to messages using StatefulSet"
```suggestion
title: "How to: Horizontally scale subscribers with StatefulSets"
```

2023-02-15 17:51 UTC, msfussell commented on daprdocs/content/en/developing-applications/building-blocks/pubsub/howto-subscribe-statefulset.md
> +linkTitle: "How to: Subscribe with StatefulSet"
```suggestion
linkTitle: "How to: Horizontally scale subscribers with StatefulSets"
```