Instructions for installing a specific CLI version (Mac/Linux only)
dapr/docs pull request #3163
Opened 2023-02-10 20:46 UTC by berndverst

Useful for installing RCs

Signed-off-by: Bernd Verst <github@bernd.dev>

2023-02-10 20:49 UTC, berndverst commented on daprdocs/content/en/getting-started/install-dapr-cli.md
> +This example shows how to install CLI version `1.9.1`. Release candidates can be installed similarly, simplify specify the version, e.g. `1.10.0-rc.3`
```suggestion
This example shows how to install CLI version `1.9.1`. Release candidates can be installed similarly, simply specify the version, e.g. `1.10.0-rc.3`
```

2023-02-10 20:49 UTC, berndverst commented on daprdocs/content/en/getting-started/install-dapr-cli.md
> +This example shows how to install CLI version `1.9.1`. Release candidates can be installed similarly, simplify specify the version, e.g. `1.10.0-rc.3`
```suggestion
This example shows how to install CLI version `1.9.1`. Release candidates can be installed similarly, simply specify the version, e.g. `1.10.0-rc.3`
```

2023-02-10 21:06 UTC, philliphoff approved these changes
I think it could use similar updates on the Mac section (as the code tabs will tend to hide it), but just having it in the docs goes a long way in making it easier to try out new versions.

2023-02-10 21:07 UTC, berndverst commented
> I think it could use similar updates on the Mac section (as the code tabs will tend to hide it), but just having it in the docs goes a long way in making it easier to try out new versions.

You are too late. This was done before you left this comment.

2023-02-10 23:46 UTC, hhunter-ms commented
@berndverst I'm pretty sure I fixed the broken link in the submodule PR I just merged, if you can pull it in

2023-02-13 15:42 UTC, hhunter-ms requested changes
quick pass

2023-02-13 15:42 UTC, hhunter-ms commented on daprdocs/content/en/getting-started/install-dapr-cli.md
> +This example shows how to install CLI version `1.9.1`. Release candidates can be installed similarly, simply specify the version, e.g. `1.10.0-rc.3`.
```suggestion
The following example shows how to install CLI version `1.9.1`. You can also install release candidates by specifying the version (for example, `1.10.0-rc.3`).
```

2023-02-13 15:42 UTC, hhunter-ms commented on daprdocs/content/en/getting-started/install-dapr-cli.md
> +This example shows how to install CLI version `1.9.1`. Release candidates can be installed similarly, simply specify the version, e.g. `1.10.0-rc.3`.
```suggestion
The following example shows how to install CLI version `1.9.1`. You can also install release candidates by specifying the version (for example, `1.10.0-rc.3`).
```

2023-02-13 15:42 UTC, hhunter-ms commented on daprdocs/content/en/getting-started/install-dapr-cli.md
> +This example shows how to install CLI version `1.9.1`. Release candidates can be installed similarly, simply specify the version, e.g. `1.10.0-rc.3`.
```suggestion
The following example shows how to install CLI version `1.9.1`. You can also install release candidates by specifying the version (for example, `1.10.0-rc.3`).
```

2023-02-13 15:42 UTC, hhunter-ms commented on daprdocs/content/en/getting-started/install-dapr-cli.md
> +This example shows how to install CLI version `1.9.1`. Release candidates can be installed similarly, simply specify the version, e.g. `1.10.0-rc.3`.
```suggestion
The following example shows how to install CLI version `1.9.1`. You can also install release candidates by specifying the version (for example, `1.10.0-rc.3`).
```

2023-02-13 15:42 UTC, hhunter-ms commented on daprdocs/content/en/getting-started/install-dapr-cli.md
> +This example shows how to install CLI version `1.9.1`. Release candidates can be installed similarly, simply specify the version, e.g. `1.10.0-rc.3`.
```suggestion
The following example shows how to install CLI version `1.9.1`. You can also install release candidates by specifying the version (for example, `1.10.0-rc.3`).
```

2023-02-13 15:42 UTC, hhunter-ms commented on daprdocs/content/en/getting-started/install-dapr-cli.md
> +This example shows how to install CLI version `1.9.1`. Release candidates can be installed similarly, simply specify the version, e.g. `1.10.0-rc.3`.
```suggestion
The following example shows how to install CLI version `1.9.1`. You can also install release candidates by specifying the version (for example, `1.10.0-rc.3`).
```

2023-02-14 16:49 UTC, hhunter-ms approved these changes

2023-02-14 18:26 UTC, hhunter-ms commented on daprdocs/content/en/getting-started/install-dapr-cli.md
> +The following example shows how to install CLI version `1.9.1`. You can also install release candidates by specifying the version (for example, `1.10.0-rc.3`).
```suggestion
The following example shows how to install CLI version `{{% dapr-latest-version cli="true" %}}`. You can also install release candidates by specifying the version (for example, `1.10.0-rc.3`).
```

2023-02-14 18:27 UTC, hhunter-ms commented on daprdocs/content/en/getting-started/install-dapr-cli.md
> +The following example shows how to install CLI version `1.9.1`. You can also install release candidates by specifying the version (for example, `1.10.0-rc.3`).
```suggestion
The following example shows how to install CLI version `{{% dapr-latest-version cli="true" %}}`. You can also install release candidates by specifying the version (for example, `1.10.0-rc.3`).
```

2023-02-14 18:27 UTC, hhunter-ms commented on daprdocs/content/en/getting-started/install-dapr-cli.md
> +The following example shows how to install CLI version `1.9.1`. You can also install release candidates by specifying the version (for example, `1.10.0-rc.3`).
```suggestion
The following example shows how to install CLI version `{{% dapr-latest-version cli="true" %}}`. You can also install release candidates by specifying the version (for example, `1.10.0-rc.3`).
```

2023-02-14 18:27 UTC, hhunter-ms commented on daprdocs/content/en/getting-started/install-dapr-cli.md
> +The following example shows how to install CLI version `1.9.1`. You can also install release candidates by specifying the version (for example, `1.10.0-rc.3`).
```suggestion
The following example shows how to install CLI version `{{% dapr-latest-version cli="true" %}}`. You can also install release candidates by specifying the version (for example, `1.10.0-rc.3`).
```

2023-02-14 18:28 UTC, hhunter-ms commented on daprdocs/content/en/getting-started/install-dapr-cli.md
> +The following example shows how to install CLI version `1.9.1`. You can also install release candidates by specifying the version (for example, `1.10.0-rc.3`).
```suggestion
The following example shows how to install CLI version `{{% dapr-latest-version cli="true" %}}`. You can also install release candidates by specifying the version (for example, `1.10.0-rc.3`).
```

2023-02-14 18:28 UTC, hhunter-ms commented on daprdocs/content/en/getting-started/install-dapr-cli.md
> +The following example shows how to install CLI version `1.9.1`. You can also install release candidates by specifying the version (for example, `1.10.0-rc.3`).
```suggestion
The following example shows how to install CLI version `{{% dapr-latest-version cli="true" %}}`. You can also install release candidates by specifying the version (for example, `1.10.0-rc.3`).
```

2023-02-14 19:25 UTC, merged