Documentation for receiving Application Properties (enriched messages…
dapr/docs pull request #3267
Opened 2023-03-16 05:35 UTC by mecoding1

…) from an Event hub

Documentation for receiving Application Properties (enriched messages) from an Event hub

Thank you for helping make the Dapr documentation better!

**Please follow this checklist before submitting:**
- [ ] Commits are signed with Developer Certificate of Origin (DCO - [learn more](https://docs.dapr.io/contributing/contributing-overview/#developer-certificate-of-origin-signing-your-work))
- [ ] [Read the contribution guide](https://docs.dapr.io/contributing/docs-contrib/contributing-docs/)
- [ ] Commands include options for Linux, MacOS, and Windows within codetabs
- [ ] New file and folder names are globally unique
- [ ] Page references use shortcodes instead of markdown or URL links
- [ ] Images use HTML style and have alternative text
- [ ] Places where multiple code/command options are given have codetabs

In addition, please fill out the following to help reviewers understand this pull request:

## Description

## Issue reference

2023-03-16 20:33 UTC, hhunter-ms commented on daprdocs/content/en/reference/components-reference/supported-pubsub/setup-azure-eventhubs.md
> +This ensures enriched messages containing additional properties are forwarded as headers. For example, the device-to-cloud events created by Azure IoT Hub devices can contain user defined additional
```suggestion
This ensures enriched messages containing additional properties are forwarded as headers. For example, the device-to-cloud events created by Azure IoT Hub devices can contain user defined additional [IoT Hub Application Properties](https://learn.microsoft.com/azure/iot-hub/iot-hub-devguide-messages-construct#application-properties-of-d2c-iot-hub-messages). The Azure Event Hubs pub/sub component for Dapr returns the following as part of the response metadata (in this example, `iothub-creation-time-utc` is application property):
```

2023-03-29 18:17 UTC, hhunter-ms requested changes

2023-03-29 18:17 UTC, hhunter-ms commented on daprdocs/content/en/reference/components-reference/supported-pubsub/setup-azure-eventhubs.md
> +It possible to get application properties (enriched messages) from an Event Hub by declaratively adding the `requireAllProperties` metadata entry to subscription specification.
```suggestion
It is possible to get application properties (enriched messages) from an Event Hub by declaratively adding the `requireAllProperties` metadata entry to the subscription specification.
```

2023-03-29 18:17 UTC, hhunter-ms commented on daprdocs/content/en/reference/components-reference/supported-pubsub/setup-azure-eventhubs.md
> +This ensures enriched messages containing additional properties are forwarded as headers. For example, the device-to-cloud events created by Azure IoT Hub devices can contain user defined additional
```suggestion
Adding this metadata entry ensures enriched messages containing additional properties are forwarded as headers. For example, the device-to-cloud events created by Azure IoT Hub devices can contain extra user-defined [IoT Hub Application Properties](https://learn.microsoft.com/azure/iot-hub/iot-hub-devguide-messages-construct#application-properties-of-d2c-iot-hub-messages). The Azure Event Hubs pub/sub component for Dapr returns the following as part of the response metadata (in this example, `iothub-creation-time-utc` is the application property):
```

2023-04-06 19:49 UTC, hhunter-ms approved these changes

2023-04-07 04:54 UTC, msfussell commented
@mecoding1 - You need to add an entry for `requireAllProperties` into the spec metadata table field https://docs.dapr.io/reference/components-reference/supported-pubsub/setup-azure-eventhubs/#spec-metadata-fields  providing a description and a link to the section you have added further down the document.

2023-04-07 06:44 UTC, mecoding1 commented
> @mecoding1 - You need to add an entry for `requireAllProperties` into the spec metadata table field https://docs.dapr.io/reference/components-reference/supported-pubsub/setup-azure-eventhubs/#spec-metadata-fields providing a description and a link to the section you have added further down the document.

@msfussell Was wondering since we need to add `"requireAllProperties": "true" ` to the subscription metadata , while the section [https://docs.dapr.io/reference/components-reference/supported-pubsub/setup-azure-eventhubs/#spec-metadata-fields](https://docs.dapr.io/reference/components-reference/supported-pubsub/setup-azure-eventhubs/#spec-metadata-fields) refers to the component spec metadata fields ?

2023-04-07 23:32 UTC, msfussell commented
> > @mecoding1 - You need to add an entry for `requireAllProperties` into the spec metadata table field https://docs.dapr.io/reference/components-reference/supported-pubsub/setup-azure-eventhubs/#spec-metadata-fields providing a description and a link to the section you have added further down the document.
> 
> @msfussell Was wondering since we need to add `"requireAllProperties": "true" ` to the subscription metadata , while the section https://docs.dapr.io/reference/components-reference/supported-pubsub/setup-azure-eventhubs/#spec-metadata-fields refers to the component spec metadata fields ?

Missed that. Yes, does not need to be added to this table. But this then raise the question that subscription spec format applies to any topic subscription, so what happens when I apply this field to any pub/sub provider, not just Event Hubs? For example, say this field was on RabbitMQ pub/sub subscription, what would happen? This *may* need to be described here https://docs.dapr.io/developing-applications/building-blocks/pubsub/subscription-methods/ is this is the case.

2023-04-12 05:29 UTC, msfussell commented
@mecoding1 - See my comment above on having this new field in the subscription topic. How does this apply to all components? Can you explain?

2023-04-12 08:26 UTC, mecoding1 commented
> How does this apply to all components?

@msfussell  It is a one off field that is being utilized in the Azure Event Hub components i.e. for that particular subscription it will provide all the properties ( application + system ) . This is non-breaking change which doesn't interfere with the functionalities of the other components . But if such a case arises where we need additional metadata , we can always reutilize this field for the same purpose.

But atm, its only useful for Azure Event Hubs ( and IoT Hub ) component , but for other components it has no effect.

2023-04-14 04:26 UTC, mecoding1 commented
@msfussell Do you think its ok to merge the PR or the details need to be added to the common subscription spec format other than in the current page ?

( since this applies to only the Event Hub subscription and not the others ? )

2023-04-27 00:08 UTC, closed without merging