Add docs for using Dev Container feature
dapr/docs pull request #3283
Opened 2023-03-22 00:17 UTC by ItalyPaleAle

Updated the documentation for using Dev Containers:

- Recommend using the new Dev Container Feature that works with every stack. https://github.com/dapr/cli/pull/1233
- Fixed some wording and branding ("Remote Containers" has been rebranded to "Dev Containers")

2023-03-23 09:37 UTC, stuartleeks commented
@ItalyPaleAle - I'm not sure why, but `https://containers.dev/features/` gives a 404. `https://containers.dev/features` (without the trailing slash) works

2023-03-23 14:52 UTC, hhunter-ms requested changes

2023-03-23 14:52 UTC, hhunter-ms commented on daprdocs/content/en/developing-applications/local-development/ides/vscode/vscode-remote-dev-containers.md
> +You can install the Dapr CLI inside any Dev Container using [Dev Container features](https://containers.dev/features/).
```suggestion
You can install the Dapr CLI inside any Dev Container using [Dev Container features](https://containers.dev/features).
```

2023-03-29 01:59 UTC, ItalyPaleAle commented
👋 bot

2023-03-29 17:55 UTC, hhunter-ms approved these changes

2023-03-29 18:47 UTC, merged