graphql output binding variable support
dapr/docs pull request #3286
Opened 2023-03-23 16:31 UTC by serpentfabric

Thank you for helping make the Dapr documentation better!

**Please follow this checklist before submitting:**
- [x] Commits are signed with Developer Certificate of Origin (DCO - [learn more](https://docs.dapr.io/contributing/contributing-overview/#developer-certificate-of-origin-signing-your-work))
- [x] [Read the contribution guide](https://docs.dapr.io/contributing/docs-contrib/contributing-docs/)
- [x] Commands include options for Linux, MacOS, and Windows within codetabs
- [x] New file and folder names are globally unique
- [x] Page references use shortcodes instead of markdown or URL links
- [x] Images use HTML style and have alternative text
- [x] Places where multiple code/command options are given have codetabs

In addition, please fill out the following to help reviewers understand this pull request:

## Description

update the graphql doc corresponding to changes proposed by the dapr/components-contrib#2701 wherein query variable support is added to the gql output binding

## Issue reference

#3165

2023-03-29 17:54 UTC, hhunter-ms requested changes

2023-03-29 17:54 UTC, hhunter-ms commented on daprdocs/content/en/reference/components-reference/supported-bindings/graghql.md
> +To use a `query` that requires [query variables](https://graphql.org/learn/queries/#variables): add a key-value pair to the `metadata` map wherein every key corresponding to a query variable is the v
```suggestion
To use a `query` that requires [query variables](https://graphql.org/learn/queries/#variables), add a key-value pair to the `metadata` map, wherein every key corresponding to a query variable is the variable name prefixed with `variable:`
```

2023-04-06 19:50 UTC, hhunter-ms approved these changes

2023-04-12 05:38 UTC, msfussell approved these changes
LGTM

2023-04-12 05:39 UTC, merged