Update javascript snippets
dapr/docs pull request #3333
Opened 2023-04-12 02:28 UTC by wralith

Thank you for helping make the Dapr documentation better!

**Please follow this checklist before submitting:**
- [x] Commits are signed with Developer Certificate of Origin (DCO - [learn more](https://docs.dapr.io/contributing/contributing-overview/#developer-certificate-of-origin-signing-your-work))
- [x] [Read the contribution guide](https://docs.dapr.io/contributing/docs-contrib/contributing-docs/)
- [ ] Commands include options for Linux, MacOS, and Windows within codetabs
- [ ] New file and folder names are globally unique
- [ ] Page references use shortcodes instead of markdown or URL links
- [ ] Images use HTML style and have alternative text
- [ ] Places where multiple code/command options are given have codetabs

In addition, please fill out the following to help reviewers understand this pull request:

## Description

Update JS-SDK snippets, using v3.0.0

## Issue reference

#3280

2023-04-12 15:25 UTC, shubham1172 requested changes
Hi @wralith, thank you for this PR! The changes LGTM, but there seem to be some missing instances like 

1. https://github.com/dapr/docs/blob/ab7a3b5b25ac54d8adead5ee76b44fe8aa812b9c/daprdocs/content/en/getting-started/quickstarts/pubsub-quickstart.md?plain=1#L276 
1. https://github.com/dapr/docs/blob/393e88fa13c00b78ef31bf1116a73ca828cc5b88/daprdocs/content/en/getting-started/quickstarts/statemanagement-quickstart.md?plain=1#L180

Can you please look at the missing ones and fix them too?

2023-04-12 16:10 UTC, shubham1172 reviewed
LGTM, small nits!

2023-04-12 16:10 UTC, shubham1172 commented on daprdocs/content/en/getting-started/quickstarts/pubsub-quickstart.md
> +const client = new DaprClient({ daprHost, daprPort });
```suggestion
const client = new DaprClient();
```

2023-04-12 16:10 UTC, shubham1172 commented on daprdocs/content/en/getting-started/quickstarts/statemanagement-quickstart.md
> +const client = new DaprClient({ daprHost, daprPort, communicationProtocol })
```suggestion
const client = new DaprClient()
```

2023-04-12 16:10 UTC, shubham1172 commented on daprdocs/content/en/getting-started/quickstarts/pubsub-quickstart.md
> +const client = new DaprClient({ daprHost, daprPort });
When we don't have any special values, we can omit these and fallback to default!

2023-04-12 16:31 UTC, shubham1172 approved these changes

2023-04-12 20:22 UTC, hhunter-ms commented
@wralith can you pull in from v1.10? I've pushed a fix for the link validation error.

2023-04-13 13:50 UTC, hhunter-ms approved these changes

2023-04-13 14:04 UTC, merged