add rocketmq consumer config item description
dapr/docs pull request #3354
Opened 2023-04-26 04:12 UTC by naah69

In addition, please fill out the following to help reviewers understand this pull request:

## Description

add rocketmq consumer config item description.

## Issue reference

https://github.com/dapr/components-contrib/issues/2756

2023-04-28 20:13 UTC, hhunter-ms requested changes
quick review - thanks!

2023-04-28 20:13 UTC, hhunter-ms commented on daprdocs/content/en/reference/components-reference/supported-pubsub/setup-rocketmq.md
> +| consumeTimestamp |    N     | Backtracking consumption time with second precision. Time format is `20131223171201`.Implying Seventeen twelve and 01 seconds on December 23, 2013 year | ` time.Now().
```suggestion
| consumeTimestamp |    N     | Backtracks consumption time with second precision. Time format is `yyyymmddhhmmss`. For example, `20131223171201` implies the time of 17:12:01 and date of December 23, 2013 | ` time.Now().Add(time.Minute * (-30)).Format("20060102150405")` | `20131223171201`                   |
```

2023-04-28 20:13 UTC, hhunter-ms commented on daprdocs/content/en/reference/components-reference/supported-pubsub/setup-rocketmq.md
> +| consumeConcurrentlyMaxSpan            |    N     | Concurrently max span offset.it has no effect on sequential consumption.Range: `[1, 65535]` | `1000`
```suggestion
| consumeConcurrentlyMaxSpan            |    N     | Concurrently max span offset. This has no effect on sequential consumption. Range: `[1, 65535]` | `1000`                                                    | `1000`                                             |
```

2023-04-28 20:13 UTC, hhunter-ms commented on daprdocs/content/en/reference/components-reference/supported-pubsub/setup-rocketmq.md
> +| consumeTimeout                            |    N     | Maximum amount of time a message may block the consuming thread.Time unit: Minute | `15`                                      | `15`
```suggestion
| consumeTimeout                            |    N     | Maximum amount of time a message may block the consuming thread. Time unit: Minute | `15`                                      | `15`                                                   |
```

2023-04-28 20:13 UTC, hhunter-ms commented on daprdocs/content/en/reference/components-reference/supported-pubsub/setup-rocketmq.md
> +| pullThresholdForQueue |    N     | Flow control threshold on queue level, each message queue will cache at most 1000 messages by default.Consider the `PullBatchSize`, the instantaneous value may ex
```suggestion
| pullThresholdForQueue |    N     | Flow control threshold on queue level. Each message queue will cache a maximum of 1000 messages by default. Consider the `PullBatchSize` - the instantaneous value may exceed the limit. Range: `[1, 65535]` | `1024`                                     | `1000`                                                       |
```

2023-04-28 20:13 UTC, hhunter-ms commented on daprdocs/content/en/reference/components-reference/supported-pubsub/setup-rocketmq.md
> +| pullThresholdForTopic    |    N     | Flow control threshold on topic level.The value of `pullThresholdForQueue` will be overwritten and calculated based on`pullThresholdForTopic` if it isn't unlim
```suggestion
| pullThresholdForTopic    |    N     | Flow control threshold on topic level. The value of `pullThresholdForQueue` will be overwritten and calculated based on `pullThresholdForTopic` if it isn't unlimited. For example, if the value of `pullThresholdForTopic` is 1000 and 10 message queues are assigned to this consumer, then `pullThresholdForQueue` will be set to 100. Range: `[1, 6553500]` | `-1(Unlimited)`                                           | `10`                                                         |
```

2023-04-28 20:13 UTC, hhunter-ms commented on daprdocs/content/en/reference/components-reference/supported-pubsub/setup-rocketmq.md
> +| pullThresholdSizeForQueue                        |    N     | Limit the cached message size on queue level.Consider the `pullBatchSize`, the instantaneous value may exceed the limit.The size of a m
```suggestion
| pullThresholdSizeForQueue                        |    N     | Limit the cached message size on queue level. Consider the `pullBatchSize` - the instantaneous value may exceed the limit. The size of a message is only measured by message body, so it's not accurate. Range: `[1, 1024]` | `100`                                                     | `100`                                                        |
```

2023-04-28 20:13 UTC, hhunter-ms commented on daprdocs/content/en/reference/components-reference/supported-pubsub/setup-rocketmq.md
> +| pullThresholdSizeForTopic                        |    N     | Limit the cached message size on topic level.The value of `pullThresholdSizeForQueue` will be overwritten and calculated based on `pull
```suggestion
| pullThresholdSizeForTopic                        |    N     | Limit the cached message size on topic level. The value of `pullThresholdSizeForQueue` will be overwritten and calculated based on `pullThresholdSizeForTopic` if it isn't unlimited. For example, if the value of `pullThresholdSizeForTopic` is 1000 MiB and 10 message queues are assigned to this consumer, then `pullThresholdSizeForQueue` will be set to 100 MiB. Range: `[1, 102400]` | `-1`                                                     | `100`                                                        |
```

2023-05-04 03:52 UTC, naah69 commented
> 

done

2023-05-09 15:04 UTC, hhunter-ms approved these changes

2023-05-09 16:56 UTC, hhunter-ms commented
@naah69 could you pull in the build fixes from v1.11?

2023-05-09 21:25 UTC, merged