wasm middleware: change path property to url
dapr/docs pull request #3359
Opened 2023-04-30 06:34 UTC by codefromthecrypt

Thank you for helping make the Dapr documentation better!

**Please follow this checklist before submitting:**
- [x] Commits are signed with Developer Certificate of Origin (DCO - [learn more](https://docs.dapr.io/contributing/contributing-overview/#developer-certificate-of-origin-signing-your-work))
- [x] [Read the contribution guide](https://docs.dapr.io/contributing/docs-contrib/contributing-docs/)
- [n/a] Commands include options for Linux, MacOS, and Windows within codetabs
- [n/a] New file and folder names are globally unique
- [n/a] Page references use shortcodes instead of markdown or URL links
- [n/a] Images use HTML style and have alternative text
- [n/a] Places where multiple code/command options are given have codetabs

In addition, please fill out the following to help reviewers understand this pull request:

## Description

This changes the configuration item for the Wasm binary from path to
url. In doing so, we ease migration from other sources including HTTP
and OCI.

## Issue reference

https://github.com/dapr/components-contrib/pull/2817 - change that results in this update
https://github.com/dapr/components-contrib/issues/2700 - the change enables this issue to complete in 1.12

2023-04-30 06:53 UTC, codefromthecrypt commented
bad link for AWS fixed here https://github.com/dapr/docs/pull/3360

2023-05-01 02:15 UTC, codefromthecrypt commented
actually real link fix that needs to go to v1.11 is [3356](https://github.com/dapr/docs/pull/3356), already in v1.10

2023-05-03 00:31 UTC, codefromthecrypt commented
rebased

2023-05-03 17:36 UTC, hhunter-ms requested changes
quick review - thanks!

2023-05-03 17:36 UTC, hhunter-ms commented on daprdocs/content/en/reference/components-reference/supported-middleware/middleware-wasm.md
> +Wasm modules are loaded from a URL. For example, a URL "file://rewrite.wasm"
```suggestion
Wasm binaries are loaded from a URL. For example, the URL `file://rewrite.wasm`
```

2023-05-03 17:36 UTC, hhunter-ms commented on daprdocs/content/en/reference/components-reference/supported-middleware/middleware-wasm.md
> +loads "rewrite.wasm" from the current directory of the process. On Kubernetes,
```suggestion
loads `rewrite.wasm` from the current directory of the process. On Kubernetes,
```

2023-05-03 17:36 UTC, hhunter-ms commented on daprdocs/content/en/reference/components-reference/supported-middleware/middleware-wasm.md
> +see [mounting volumes to the Dapr sidecar]({{< ref kubernetes-volume-mounts.md >}})
```suggestion
see [How to: Mount Pod volumes to the Dapr sidecar]({{< ref kubernetes-volume-mounts.md >}})
```

2023-05-03 17:36 UTC, hhunter-ms commented on daprdocs/content/en/reference/components-reference/supported-middleware/middleware-wasm.md
> +| url   | The URL of the resource including the Wasm binary to instantiate. The supported schemes include "file://". The path of a "file://" URL is relative to the Dapr process unless it begins with
```suggestion
| url   | The URL of the resource including the Wasm binary to instantiate. The supported schemes include `file://`. The path of a `file://` URL is relative to the Dapr process unless it begins with `/`. | true     | `file://hello.wasm` |
```

2023-05-03 17:36 UTC, hhunter-ms commented on daprdocs/content/en/reference/components-reference/supported-middleware/middleware-wasm.md
> +"url" to the location of the output (ex "file://router.wasm"):
```suggestion
"url" to the location of the output (ex "file://router.wasm"):
```
```suggestion
"url" to the location of the output (for example, `file://router.wasm`):
```

2023-05-03 17:36 UTC, hhunter-ms commented on daprdocs/content/en/reference/components-reference/supported-middleware/middleware-wasm.md
> +"url" to the location of the output (ex "file://example.wasm"):
```suggestion
"url" to the location of the output (for example, `file://example.wasm`):
```

2023-05-03 23:21 UTC, codefromthecrypt commented
Thanks again @hhunter-ms!

2023-05-09 05:22 UTC, msfussell commented
@codefromthecrypt  - You will need to perform a new pull on Dapr v1.11 branch for the build to succeed. Thx

2023-05-09 16:57 UTC, hhunter-ms approved these changes

2023-05-09 21:16 UTC, merged

2023-05-09 23:01 UTC, codefromthecrypt commented
thanks again @hhunter-ms and @msfussell!