AWS Bindings S3 Certification Tests
dapr/docs pull request #3376
Opened 2023-05-02 20:45 UTC by robertojrojas

Thank you for helping make the Dapr documentation better!

**Please follow this checklist before submitting:**
- [x] Commits are signed with Developer Certificate of Origin (DCO - [learn more](https://docs.dapr.io/contributing/contributing-overview/#developer-certificate-of-origin-signing-your-work))
- [x] [Read the contribution guide](https://docs.dapr.io/contributing/docs-contrib/contributing-docs/)
- [x] Commands include options for Linux, MacOS, and Windows within codetabs
- [ ] New file and folder names are globally unique
- [ ] Page references use shortcodes instead of markdown or URL links
- [ ] Images use HTML style and have alternative text
- [x] Places where multiple code/command options are given have codetabs

## Description
As part of the AWS Bindings S3 Certification Tests, new attributes were added that require documentation updates.
Also, changed the AWS Bindings S3 component status to **Stable**

## Issue reference

reference the issue: https://github.com/dapr/components-contrib/pull/2247

2023-05-03 17:23 UTC, hhunter-ms requested changes
quick grammar review - thanks!

2023-05-03 17:23 UTC, hhunter-ms commented on daprdocs/content/en/reference/components-reference/supported-bindings/s3.md
> +To able to use the S3 component, the bucket to be used needs to existing prior to use, so the example above uses a [LocalStack Initialization Hook](https://docs.localstack.cloud/references/init-hooks
```suggestion
To use the S3 component, you need to use an existing bucket. The example above uses a [LocalStack Initialization Hook](https://docs.localstack.cloud/references/init-hooks/) to setup the bucket.
```

2023-05-03 17:23 UTC, hhunter-ms commented on daprdocs/content/en/reference/components-reference/supported-bindings/s3.md
> +To able to use the S3 component, the bucket to be used needs to existing prior to use, [Follow](https://docs.aws.amazon.com/AmazonS3/latest/userguide/create-bucket-overview.html)
```suggestion
To use the S3 component, you need to use an existing bucket. Follow the [AWS documentation for creating a bucket](https://docs.aws.amazon.com/AmazonS3/latest/userguide/create-bucket-overview.html).
```

2023-05-03 17:23 UTC, hhunter-ms commented on daprdocs/content/en/reference/components-reference/supported-bindings/s3.md
> +{{< tabs "Minio" "Localstack" "AWS" >}}
```suggestion
{{< tabs "Minio" "LocalStack" "AWS" >}}
```

2023-05-03 17:23 UTC, hhunter-ms commented on daprdocs/content/en/reference/components-reference/supported-bindings/s3.md
> +For local development, the [localstack project](https://github.com/localstack/localstack) is used to integrate AWS S3. Follow [these instructions](https://github.com/localstack/localstack#running) to
```suggestion
For local development, the [LocalStack project](https://github.com/localstack/localstack) is used to integrate AWS S3. Follow [these instructions](https://github.com/localstack/localstack#running) to run LocalStack.
```

2023-05-03 17:23 UTC, hhunter-ms commented on daprdocs/content/en/reference/components-reference/supported-bindings/s3.md
> +To run localstack locally from the command line using Docker, use a `docker-compose.yaml` similar to the following:
```suggestion
To run LocalStack locally from the command line using Docker, use a `docker-compose.yaml` similar to the following:
```

2023-05-03 17:23 UTC, hhunter-ms commented on daprdocs/content/en/reference/components-reference/supported-bindings/s3.md
> +In order to use localstack with your S3 binding, you need to provide the `endpoint` configuration in the component metadata. The `endpoint` is unnecessary when running against production AWS.
```suggestion
To use LocalStack with your S3 binding, you need to provide the `endpoint` configuration in the component metadata. The `endpoint` is unnecessary when running against production AWS.
```

2023-05-09 04:39 UTC, msfussell approved these changes
LGTM

2023-05-09 04:39 UTC, msfussell approved these changes
LGTM

2023-05-09 04:41 UTC, msfussell commented
@robertojrojas - You will need to perform a new pull on Dapr v1.11 branch for the build to succeed. Thx

2023-05-09 14:43 UTC, hhunter-ms approved these changes

2023-05-09 15:16 UTC, merged