Add Otel env var docs
dapr/docs pull request #3388
Opened 2023-05-06 22:50 UTC by drewby

Thank you for helping make the Dapr documentation better!

**Please follow this checklist before submitting:**
- [X] Commits are signed with Developer Certificate of Origin (DCO - [learn more](https://docs.dapr.io/contributing/contributing-overview/#developer-certificate-of-origin-signing-your-work))
- [X ] [Read the contribution guide](https://docs.dapr.io/contributing/docs-contrib/contributing-docs/)
- [N/A] Commands include options for Linux, MacOS, and Windows within codetabs
- [N/A ] New file and folder names are globally unique
- [N/A ] Page references use shortcodes instead of markdown or URL links
- [N/A ] Images use HTML style and have alternative text
- [ ] Places where multiple code/command options are given have codetabs

In addition, please fill out the following to help reviewers understand this pull request:

## Description
Adds content to two pages which will describe the environment variables and how they impact the sidecar. Also, corrects a typo in both pages.

OTEL_EXPORTER_OTLP_ENDPOINT - OpenTelemetry target URL for OTLP exporter
OTEL_EXPORTER_OTLP_INSECURE - OpenTelemetry disables client transport security
OTEL_EXPORTER_OTLP_PROTOCOL - OpenTelemetry transport protocol (grpc, http/protobuf, http/json)

## Issue reference
close: #3387

2023-05-08 13:26 UTC, hhunter-ms requested changes
small edits

2023-05-08 13:26 UTC, hhunter-ms commented on daprdocs/content/en/operations/configuration/configuration-overview.md
> +| `OTEL_EXPORTER_OTLP_ENDPOINT` | Set the Open Telemetry (OTEL) server address, turns on tracing |
```suggestion
| `OTEL_EXPORTER_OTLP_ENDPOINT` | Sets the Open Telemetry (OTEL) server address, turns on tracing |
```

2023-05-08 13:26 UTC, hhunter-ms commented on daprdocs/content/en/operations/configuration/configuration-overview.md
> +| `OTEL_EXPORTER_OTLP_INSECURE` | Set the connection to the endpoint as unencrypted (true/false) |
```suggestion
| `OTEL_EXPORTER_OTLP_INSECURE` | Sets the connection to the endpoint as unencrypted (true/false) |
```

2023-05-08 13:26 UTC, hhunter-ms commented on daprdocs/content/en/operations/monitoring/tracing/setup-tracing.md
> +| `OTEL_EXPORTER_OTLP_ENDPOINT` | Set the Open Telemetry (OTEL) server address, turns on tracing |
```suggestion
| `OTEL_EXPORTER_OTLP_ENDPOINT` | Sets the Open Telemetry (OTEL) server address, turns on tracing |
```

2023-05-08 13:26 UTC, hhunter-ms commented on daprdocs/content/en/operations/monitoring/tracing/setup-tracing.md
> +| `OTEL_EXPORTER_OTLP_INSECURE` | Set the connection to the endpoint as unencrypted (true/false) |
```suggestion
| `OTEL_EXPORTER_OTLP_INSECURE` | Sets the connection to the endpoint as unencrypted (true/false) |
```

2023-05-08 16:25 UTC, msfussell commented on daprdocs/content/en/operations/configuration/configuration-overview.md
> +will turn on tracing for the sidecar.
```suggestion
turns on tracing for the sidecar.
```

2023-05-08 16:25 UTC, msfussell commented on daprdocs/content/en/operations/monitoring/tracing/setup-tracing.md
> +will turn on tracing for the sidecar.
```suggestion
turns on tracing for the sidecar.
```

2023-05-08 16:25 UTC, msfussell commented on daprdocs/content/en/operations/configuration/configuration-overview.md
> +| Environment Variable | Description |
Can you also add these environment variables into the overall Env Variable reference topic. This topic https://docs.dapr.io/reference/environment/ in the docs

2023-05-09 04:07 UTC, msfussell commented
@drewby - You need to perform a new pull on Dapr v1.11 branch for the build to succeed.

2023-05-09 07:05 UTC, drewby commented on daprdocs/content/en/operations/configuration/configuration-overview.md
> +| Environment Variable | Description |
Added

2023-05-09 16:07 UTC, hhunter-ms approved these changes

2023-05-09 18:54 UTC, merged