Adds note about using `ttlInSeconds` to actor state store reference API
dapr/docs pull request #3392
Opened 2023-05-09 12:35 UTC by JoshVanL

Part of https://github.com/dapr/dapr/issues/6301

Actor state TTL [issue](https://github.com/dapr/dapr/issues/5899), [implementation](https://github.com/dapr/dapr/pull/6125).

Updates API reference to include actor state `ttlInSeconds` metadata field. Includes reference to the dapr community call where this feature was showcased, and mechanics discussed in more detail.

Fixes https://github.com/dapr/docs/issues/3318

2023-05-10 16:41 UTC, hhunter-ms requested changes
quick review

2023-05-10 16:41 UTC, hhunter-ms commented on daprdocs/content/en/developing-applications/building-blocks/state-management/state-management-overview.md
> +Transactional state stores can be used to store actor state. To specify which state store to use for actors, specify value of property `actorStateStore` as `true` in the state store component's metad
```suggestion
Transactional state stores can be used to store actor state. To specify which state store to use for actors, specify value of property `actorStateStore` as `true` in the state store component's metadata section. Actors state is stored with a specific scheme in transactional state stores, allowing for consistent querying. Only a single state store component can be used as the state store for all actors. You should always set the TTL metadata field (`ttlInSeconds`), or the equivalent API call in your chosen SDK when saving actor state. Read the [state API reference]({{< ref state_api.md >}}) and the [actors API reference]({{< ref actors_api.md >}}) to learn more about state stores for actors.
```

2023-05-10 16:41 UTC, hhunter-ms commented on daprdocs/content/en/reference/api/actors_api.md
> +When putting state, clients should _always_ set the `ttlInSeconds` field in the
```suggestion
When putting state, _always_ set the `ttlInSeconds` field in the
```

2023-05-10 16:41 UTC, hhunter-ms commented on daprdocs/content/en/reference/api/actors_api.md
> +Please see the [Dapr Community Call 80](https://youtu.be/kVpQYkGemRc?t=28)
```suggestion
See the [Dapr Community Call 80](https://youtu.be/kVpQYkGemRc?t=28)
```

2023-05-10 16:41 UTC, hhunter-ms commented on daprdocs/content/en/reference/api/actors_api.md
> +
If you like, we can embed the call here..

```
<iframe width="560" height="315" src="https://www.youtube-nocookie.com/embed/kVpQYkGemRc?start=28" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" allowfullscreen></iframe>
```

2023-05-10 17:22 UTC, JoshVanL commented on daprdocs/content/en/reference/api/actors_api.md
> +
Thanks, this would be a lot better

2023-05-10 17:37 UTC, JoshVanL commented
Thanks @hhunter-ms, please take another look

2023-05-10 17:49 UTC, hhunter-ms approved these changes

2023-05-15 15:57 UTC, msfussell commented on daprdocs/content/en/developing-applications/building-blocks/state-management/state-management-overview.md
> +Transactional state stores can be used to store actor state. To specify which state store to use for actors, specify value of property `actorStateStore` as `true` in the state store component's metad
```suggestion
Transactional state stores can be used to store actor state. To specify which state store to use for actors, specify value of property `actorStateStore` as `true` in the state store component's metadata section. Actors state is stored with a specific scheme in transactional state stores, allowing for consistent querying. Only a single state store component can be used as the state store for all actors. 

#### Time to Live (TTL) on actor state
You should always set the TTL metadata field (`ttlInSeconds`), or the equivalent API call in your chosen SDK when saving actor state. Read the [state API reference]({{< ref state_api.md >}}) and the [actors API reference]({{< ref actors_api.md >}}) to learn more about state stores for actors.
```

2023-05-15 16:01 UTC, msfussell commented on daprdocs/content/en/developing-applications/building-blocks/state-management/state-management-overview.md
> +Transactional state stores can be used to store actor state. To specify which state store to use for actors, specify value of property `actorStateStore` as `true` in the state store component's metad
Should also include this TTL heading section in this doc https://v1-11.docs.dapr.io/developing-applications/building-blocks/actors/actors-overview/

2023-05-15 16:19 UTC, JoshVanL commented
Thanks @msfussell

Added you suggestion, and copied the state section to the overview.

2023-05-17 05:23 UTC, msfussell approved these changes
LGTM

2023-05-17 23:12 UTC, merged