add kitex binding
dapr/docs pull request #3412
Opened 2023-05-16 00:28 UTC by liu-song

Thank you for helping make the Dapr documentation better!

**Please follow this checklist before submitting:**
- [x] Commits are signed with Developer Certificate of Origin (DCO - [learn more](https://docs.dapr.io/contributing/contributing-overview/#developer-certificate-of-origin-signing-your-work))
- [x] [Read the contribution guide](https://docs.dapr.io/contributing/docs-contrib/contributing-docs/)
- [ ] Commands include options for Linux, MacOS, and Windows within codetabs
- [x] New file and folder names are globally unique
- [ ] Page references use shortcodes instead of markdown or URL links
- [ ] Images use HTML style and have alternative text
- [ ] Places where multiple code/command options are given have codetabs

In addition, please fill out the following to help reviewers understand this pull request:

## Description

add kitex binding 
## Issue reference
https://github.com/dapr/docs/issues/3266

2023-05-16 16:38 UTC, hhunter-ms requested changes
quick review

2023-05-16 16:38 UTC, hhunter-ms commented on daprdocs/content/en/reference/components-reference/supported-bindings/kitex.md
> +The binding for kitex mainly utilizes the generic-call feature in kitex. More information can be found in [kitex generic-call](https://www.cloudwego.io/docs/kitex/tutorials/advanced-feature/generic-c
```suggestion
The binding for Kitex mainly utilizes the generic-call feature in Kitex. Learn more from the official documentation around [Kitex generic-call](https://www.cloudwego.io/docs/kitex/tutorials/advanced-feature/generic-call/).
```

2023-05-16 16:38 UTC, hhunter-ms commented on daprdocs/content/en/reference/components-reference/supported-bindings/kitex.md
> +Currently, kitex only supports Thrift generic calls, and the implementation integrated into [components-contrib](https://github.com/dapr/components-contrib/tree/master/bindings/kitex) adopts binary g
```suggestion
Currently, Kitex only supports Thrift generic calls. The implementation integrated into [components-contrib](https://github.com/dapr/components-contrib/tree/master/bindings/kitex) adopts binary generic calls.
```

2023-05-16 16:38 UTC, hhunter-ms commented on daprdocs/content/en/reference/components-reference/supported-bindings/kitex.md
> +To setup an Kitex binding create a component of type `bindings.kitex`. See [this guide]({{< ref "howto-bindings.md#1-create-a-binding" >}}) on how to create and apply a binding configuration.
```suggestion
To setup an Kitex binding, create a component of type `bindings.kitex`. See the [How-to: Use output bindings to interface with external resources]({{< ref "howto-bindings.md#1-create-a-binding" >}}) guide on creating and applying a binding configuration.
```

2023-05-16 16:38 UTC, hhunter-ms commented on daprdocs/content/en/reference/components-reference/supported-bindings/kitex.md
> +The `InvokeRequest.Metadata` for `bindings.kitex` requires the client to fill in four required items: hostPorts, destService, methodName and version when making a call.
```suggestion
The `InvokeRequest.Metadata` for `bindings.kitex` requires the client to fill in four required items when making a call: 
- `hostPorts`
- `destService`
- `methodName`
- `version` 
```

2023-05-16 16:38 UTC, hhunter-ms commented on daprdocs/content/en/reference/components-reference/supported-bindings/kitex.md
> +| hostPorts   |    Y     | Output | IP address and port information of the kitex server (thrift)                                        | `"127.0.0.1:8888"` |
```suggestion
| hostPorts   |    Y     | Output | IP address and port information of the Kitex server (Thrift)                                        | `"127.0.0.1:8888"` |
```

2023-05-16 16:38 UTC, hhunter-ms commented on daprdocs/content/en/reference/components-reference/supported-bindings/kitex.md
> +| destService |    Y     | Output | Service name of the kitex server (thrift)            | `"echo"`           |
```suggestion
| destService |    Y     | Output | Service name of the Kitex server (Thrift)            | `"echo"`           |
```

2023-05-16 16:38 UTC, hhunter-ms commented on daprdocs/content/en/reference/components-reference/supported-bindings/kitex.md
> +| methodName  |    Y     | Output | Method name under a specific service name of the kitex server (thrift) | `"echo"`           |
```suggestion
| methodName  |    Y     | Output | Method name under a specific service name of the Kitex server (Thrift) | `"echo"`           |
```

2023-05-16 16:38 UTC, hhunter-ms commented on daprdocs/content/en/reference/components-reference/supported-bindings/kitex.md
> +| version     |    Y     | Output | kitex version                                                                                           | `"0.5.0"`          |
```suggestion
| version     |    Y     | Output | Kitex version                                                                                           | `"0.5.0"`          |
```

2023-05-16 16:38 UTC, hhunter-ms commented on daprdocs/content/en/reference/components-reference/supported-bindings/kitex.md
> +When using kitex binding, the client needs to pass in the correct Thrift-encoded binary, and the server needs to be a Thrift Server. The [kitex_output_test](https://github.com/dapr/components-contrib
```suggestion
When using Kitex binding:
- The client needs to pass in the correct Thrift-encoded binary
- The server needs to be a Thrift Server. 

The [kitex_output_test](https://github.com/dapr/components-contrib/blob/master/bindings/kitex/kitex_output_test.go) can be used as a reference.
```

2023-05-16 16:38 UTC, hhunter-ms commented on daprdocs/content/en/reference/components-reference/supported-bindings/kitex.md
> +For example, the variable `reqData` needs to be encoded by the Thrift protocol before sending, and the returned data needs to be decoded by the Thrift protocol.
```suggestion
For example, the variable `reqData` needs to be _encoded_ by the Thrift protocol before sending, and the returned data needs to be decoded by the Thrift protocol.
```
```suggestion
For example, the variable `reqData` needs to be _encoded_ by the Thrift protocol before sending, and the returned data needs to be then _decoded_ by the Thrift protocol.
```

2023-05-17 05:24 UTC, liu-song commented
@hhunter-ms Thanks, these modifications have made the document clearer.

2023-05-17 19:13 UTC, hhunter-ms approved these changes

2023-05-17 20:10 UTC, merged