Workflow: Rewrite intro and add new overview image
dapr/docs pull request #3472
Opened 2023-05-31 11:25 UTC by marcduiker

Thank you for helping make the Dapr documentation better!

**Please follow this checklist before submitting:**
- [X] Commits are signed with Developer Certificate of Origin (DCO - [learn more](https://docs.dapr.io/contributing/contributing-overview/#developer-certificate-of-origin-signing-your-work))
- [X] [Read the contribution guide](https://docs.dapr.io/contributing/docs-contrib/contributing-docs/)
- [X] Commands include options for Linux, MacOS, and Windows within codetabs
- [X] New file and folder names are globally unique
- [X] Page references use shortcodes instead of markdown or URL links
- [X] Images use HTML style and have alternative text
- [X] Places where multiple code/command options are given have codetabs

In addition, please fill out the following to help reviewers understand this pull request:

## Description

Make the workflow intro a bit easier to read.

Update workflow images to be more descriptive.

## Issue reference

2023-06-06 21:08 UTC, hhunter-ms requested changes

2023-06-06 21:08 UTC, hhunter-ms commented on daprdocs/content/en/developing-applications/building-blocks/workflow/workflow-overview.md
> +Dapr workflow makes it easy for developers to write business logic and integrations a reliable way. Since Dapr workflows are stateful, they support long running and fault-tolerant applications, ideal
```suggestion
Dapr workflow makes it easy for developers to write business logic and integrations in a reliable way. Since Dapr workflows are stateful, they support long-running and fault-tolerant applications, ideal for orchestrating microservices. Dapr workflow works seamlessly with other Dapr building blocks, such as service invocation, pub/sub, state management, and bindings.
```

2023-06-07 04:43 UTC, msfussell reviewed
I would add that the "workflow-monitor-pattern.png" image shows about on the implementation detail rather than the solution. Maybe we can keep both diagrams, since the current one does show more of a scenario IMO.

2023-06-07 04:43 UTC, msfussell commented on daprdocs/content/en/developing-applications/building-blocks/workflow/workflow-overview.md
> +Start a workflow using the Dapr HTTP API with the workflow name, HelloWorldWorkflow, and an instance ID of 12345:
It is out of place having this example in the middle of the overview. I would move this example to the How to Manage workflows topic https://docs.dapr.io/developing-applications/building-blocks/workflow/howto-manage-workflow/

2023-06-07 19:32 UTC, hhunter-ms approved these changes

2023-06-07 20:06 UTC, merged