Adds Etcdv2
dapr/docs pull request #3582
Opened 2023-06-27 10:50 UTC by JoshVanL

See https://github.com/dapr/components-contrib/pull/2932

2023-06-27 15:39 UTC, hhunter-ms requested changes
quick review

2023-06-27 15:39 UTC, hhunter-ms commented on daprdocs/content/en/reference/components-reference/supported-state-stores/setup-etcd.md
> +`v1` and `v2` have the same metadata fields, however `v1` will cause data inconsistencies in apps when using [Actor TTLs]({{< ref "actors_api.md#ttl" >}}) from Dapr `v1.12`.
```suggestion
While `v1` and `v2` have the same metadata fields, `v1` causes data inconsistencies in apps when using [Actor TTLs]({{< ref "actors_api.md#ttl" >}}) from Dapr v1.12.
```

2023-06-27 15:39 UTC, hhunter-ms commented on daprdocs/content/en/reference/components-reference/supported-state-stores/setup-etcd.md
> +Users should always use `v2` over `v1` as `v1` is deprecated.
```suggestion
```

Moved this up ^^

2023-06-27 15:39 UTC, hhunter-ms commented on daprdocs/content/en/reference/components-reference/supported-state-stores/setup-etcd.md
> +Dapr has 2 versions of the Etcd state store component: `v1` and `v2`.
```suggestion
Dapr has 2 versions of the Etcd state store component: `v1` and `v2`. It is recommended to use `v2`, as `v1` is deprecated.
```

2023-06-27 15:39 UTC, hhunter-ms commented on daprdocs/content/en/reference/components-reference/supported-state-stores/setup-etcd.md
> +`v1` and `v2` are incompatible and there is no data migration path for `v1` to `v2` on an existing active Etcd cluster and `keyPrefixPath`.
```suggestion
Due to this inconsistency, `v1` and `v2` are incompatible and there is no data migration path for `v1` to `v2` on an existing active Etcd cluster and `keyPrefixPath`.
```

2023-06-27 15:39 UTC, hhunter-ms commented on daprdocs/content/en/reference/components-reference/supported-state-stores/setup-etcd.md
> +If you are using `v1`, you should continue to use `v1` until you create a new Etcd cluster or use a different `keyPrefixPath`, then use `v2`.
```suggestion
If you are using `v1`, you should continue to use `v1` until you create a new Etcd cluster or use a different `keyPrefixPath`.
```

2023-06-28 08:47 UTC, JoshVanL commented
Thanks @hhunter-ms!

2023-06-28 14:47 UTC, hhunter-ms approved these changes

2023-06-28 15:27 UTC, merged