Document protected pub/sub topics
dapr/docs pull request #3624
Opened 2023-07-23 20:23 UTC by kovalromank

## Description

Added documentation for pub/sub protected topics.  Implementation PR: dapr/dapr#6714.

## Issue reference

References dapr/dapr#5843.

2023-07-24 19:16 UTC, hhunter-ms requested changes
just a quick review - thanks!

2023-07-24 19:16 UTC, hhunter-ms commented on daprdocs/content/en/developing-applications/building-blocks/pubsub/pubsub-scopes.md
> +If your topic involves sensitive data, each new application must be explicitly listed in the `publishingScopes` and `subscriptionScopes` to ensure it cannot read from or write to that topic. Alternat
```suggestion
If your topic involves sensitive data, each new application must be explicitly listed in the `publishingScopes` and `subscriptionScopes` to ensure it cannot read from or write to that topic. Alternatively, you can designate the topic as 'protected' (using `protectedTopics`) and grant access only to specific applications that genuinely require it.
```

2023-07-24 19:16 UTC, hhunter-ms commented on daprdocs/content/en/developing-applications/building-blocks/pubsub/pubsub-scopes.md
> +> Note that topics A and B are marked as protected. As a result, even though app3 is not listed under `publishingScopes` or `subscriptionScopes` it cannot interact with these topics.
```suggestion
In the example above, topics A and B are marked as protected. As a result, even though `app3` is not listed under `publishingScopes` or `subscriptionScopes`, it cannot interact with these topics.
```

2023-07-27 15:52 UTC, hhunter-ms approved these changes

2023-08-02 00:17 UTC, msfussell approved these changes
LGTM. I have raised this issue https://github.com/dapr/docs/issues/3657 to improve the referencing to this topic.

2023-08-02 14:38 UTC, merged