Add guestConfig metadata doc for wasm middleware
dapr/docs pull request #3632
Opened 2023-07-25 14:59 UTC by Taction

Thank you for helping make the Dapr documentation better!

**Please follow this checklist before submitting:**
- [x] Commits are signed with Developer Certificate of Origin (DCO - [learn more](https://docs.dapr.io/contributing/contributing-overview/#developer-certificate-of-origin-signing-your-work))
- [x] [Read the contribution guide](https://docs.dapr.io/contributing/docs-contrib/contributing-docs/)
- [ ] Commands include options for Linux, MacOS, and Windows within codetabs
- [ ] New file and folder names are globally unique
- [ ] Page references use shortcodes instead of markdown or URL links
- [ ] Images use HTML style and have alternative text
- [ ] Places where multiple code/command options are given have codetabs

In addition, please fill out the following to help reviewers understand this pull request:

## Description

Add guestConfig metadata doc for wasm middleware.

## Issue reference

Please reference the issue this PR will close: #3617

2023-07-27 15:25 UTC, hhunter-ms requested changes
quick review

2023-07-27 15:25 UTC, hhunter-ms commented on daprdocs/content/en/reference/components-reference/supported-middleware/middleware-wasm.md
> +| guestConfig   | An optional configuration passed to WASM guests. Users can pass an arbitrary string to be parsed by the guest code. | false     | `enviroment=production`,`{"environment":"production
```suggestion
| guestConfig   | An optional configuration passed to Wasm guests. Users can pass an arbitrary string to be parsed by the guest code. | false     | `enviroment=production`,`{"environment":"production"}` |
```

2023-07-27 15:25 UTC, hhunter-ms commented on daprdocs/content/en/reference/components-reference/supported-middleware/middleware-wasm.md
> +### wasm config example
```suggestion
### Wasm `guestConfig` example
```

2023-07-27 15:25 UTC, hhunter-ms commented on daprdocs/content/en/reference/components-reference/supported-middleware/middleware-wasm.md
> +Here is an example of how to use `guestConfig` to pass configurations to wasm. In wasm code, you can use the function `handler.Host.GetConfig` defined in guest sdk to get the configuration. In the fo
```suggestion
Here is an example of how to use `guestConfig` to pass configurations to Wasm. In Wasm code, you can use the function `handler.Host.GetConfig` defined in guest SDK to get the configuration. In the following example, the Wasm middleware parses the executed `environment` from JSON config defined in the component.
```

2023-08-01 23:32 UTC, msfussell commented
@Taction - Can you take a look at these few updates? Thx

2023-08-02 06:13 UTC, Taction commented
Thanks for the review and the remind. Fixed.

2023-08-07 17:35 UTC, msfussell approved these changes
LGTM

2023-08-07 17:44 UTC, hhunter-ms approved these changes

2023-08-07 17:53 UTC, merged