Update wasm.md to include some HTTP instructions
dapr/docs pull request #3649
Opened 2023-07-30 15:14 UTC by brendandburns

Thank you for helping make the Dapr documentation better!

**Please follow this checklist before submitting:**
- [ ] Commits are signed with Developer Certificate of Origin (DCO - [learn more](https://docs.dapr.io/contributing/contributing-overview/#developer-certificate-of-origin-signing-your-work))
- [ ] [Read the contribution guide](https://docs.dapr.io/contributing/docs-contrib/contributing-docs/)
- [ ] Commands include options for Linux, MacOS, and Windows within codetabs
- [ ] New file and folder names are globally unique
- [ ] Page references use shortcodes instead of markdown or URL links
- [ ] Images use HTML style and have alternative text
- [ ] Places where multiple code/command options are given have codetabs

In addition, please fill out the following to help reviewers understand this pull request:

## Description

## Issue reference

2023-08-01 23:44 UTC, msfussell reviewed
@brendandburns - Given this binding change is in the v1.12 release, can you target this PR as the v1.12 docs branch? Thx

2023-08-01 23:44 UTC, msfussell commented on daprdocs/content/en/reference/components-reference/supported-bindings/wasm.md
> +The WASM output binding supports making HTTP client calls using the [wasi-http](https://github.com/WebAssembly/wasi-http) specification.
```suggestion
The Wasm output binding supports making HTTP client calls using the [wasi-http](https://github.com/WebAssembly/wasi-http) specification.
```

2023-08-01 23:44 UTC, msfussell commented on daprdocs/content/en/reference/components-reference/supported-bindings/wasm.md
> +Note that if you just want to make an HTTP call, it is far simpler to use the [HTTP Binding](https://docs.dapr.io/reference/components-reference/supported-bindings/http/) but if you need to add your
```suggestion
Note that if you just want to make an HTTP call, it is simpler to use the [service invocation API]({{< ref howto-invoke-non-dapr-endpoints.md >}}). However if you need to add your own logic, for example filtering or calling to multiple API endpoints, then consider using WebAssembly.
```

2023-08-02 00:33 UTC, brendandburns commented
hrmph, switching bases messed up this PR. I will re-compute it...

2023-08-02 00:41 UTC, brendandburns commented
Ok, fixed.

2023-08-02 15:11 UTC, hhunter-ms requested changes

2023-08-02 15:11 UTC, hhunter-ms commented on daprdocs/content/en/reference/components-reference/supported-bindings/wasm.md
> +* [dotnet](https://github.com/dev-wasm/dev-wasm-dotnet/tree/main/http)
```suggestion
* [.NET](https://github.com/dev-wasm/dev-wasm-dotnet/tree/main/http)
```

2023-08-02 15:11 UTC, hhunter-ms commented on daprdocs/content/en/reference/components-reference/supported-bindings/wasm.md
> +Note that if you just want to make an HTTP call, it is simpler to use the [service invocation API]({{< ref howto-invoke-non-dapr-endpoints.md >}}). However if you need to add your own logic, for exam
```suggestion
{{% alert title="Note" color="primary" %}}
If you just want to make an HTTP call, it is simpler to use the [service invocation API]({{< ref howto-invoke-non-dapr-endpoints.md >}}). However, if you need to add your own logic - for example, filtering or calling to multiple API endpoints - consider using Wasm.
{{% /alert %}}
```

2023-08-02 17:03 UTC, brendandburns commented
Thanks for the suggestions, merged.

2023-08-02 23:26 UTC, hhunter-ms approved these changes

2023-08-02 23:58 UTC, msfussell approved these changes
LGTM

2023-08-04 19:08 UTC, merged