Create 'quorum' queues in RabbitMQ
dapr/docs pull request #3699
Opened 2023-08-28 06:25 UTC by aaguilartablada

It closes issue https://github.com/dapr/docs/issues/3685

2023-08-31 20:09 UTC, hhunter-ms requested changes
small edit

2023-08-31 20:09 UTC, hhunter-ms commented on daprdocs/content/en/reference/components-reference/supported-pubsub/setup-rabbitmq.md
> +By default Dapr creates 'classic' queues. To create 'quorum' queues:
```suggestion
By default, Dapr creates `classic` queues. To create `quorum` queues, add the following metadata to your subscription:
```

2023-09-01 09:08 UTC, aaguilartablada commented
changes applied. thanks @hhunter-ms !

2023-09-01 15:22 UTC, hhunter-ms approved these changes

2023-09-12 16:32 UTC, msfussell commented
@aaguilartablada - The `queuetype` property needs to added to the Component format Metadata https://docs.dapr.io/reference/components-reference/supported-bindings/rabbitmq/#component-format and also into the table below https://docs.dapr.io/reference/components-reference/supported-bindings/rabbitmq/#spec-metadata-fields to describe what the field does. The section you added is a howto example, but need the overall reference in the table

2023-09-14 11:12 UTC, aaguilartablada commented
> @aaguilartablada - The `queuetype` property needs to added to the Component format Metadata. The section you added is a Wow to example, but we need the overall reference in the table. Actually I now see this old PR. #3193. Can you pull the information from #3193 into this PR?

The PR https://github.com/dapr/docs/pull/3193 is bad documentation, as my PR https://github.com/dapr/components-contrib/pull/2816 only allows classic and quorum queues. It does not include support for stream. 

I think my documentation is OK as queue type is indicated at subscription level, not at component level.

2023-09-14 16:57 UTC, hhunter-ms commented
resolved conflicts

2023-09-14 19:33 UTC, msfussell commented
@aaguilartablada - Look at my comment here https://github.com/dapr/docs/pull/3193/files#r1326422581
We do need to include all the metadata options and you have added `queuetype`in this PR. So can we merge #3193 along with this PR? It is unfortunate there are two docs PRs for this one code update.

2023-09-14 19:54 UTC, aaguilartablada commented
@msfussell let me insist, please. 

My PR https://github.com/dapr/components-contrib/pull/2816 does not include metadata for RabbitMQ pubsub component. It includes metadata for subscription the same way subscription contains metadata for routing key without including it in component. The comment you just mentioned is to document a pull request that was closed without merging. You can go to the issue associated https://github.com/dapr/components-contrib/issues/2544 and then you will see that the PR https://github.com/dapr/components-contrib/pull/2556 is closed. This PR tried to add metadata to pubsub component, right. But my solution, that was already merged, has another approach: configuring the queue type through subscription.

2023-09-15 22:22 UTC, msfussell commented on daprdocs/content/en/reference/components-reference/supported-pubsub/setup-rabbitmq.md
> +By default, Dapr creates `classic` queues. To create `quorum` queues, add the following metadata to your subscription:
```suggestion
By default, Dapr creates `classic` queues. To create `quorum` queues, add the following metadata to your pub/sub [subscription]({{< ref subscription-schema.md >}})
```

2023-09-15 22:25 UTC, msfussell commented on daprdocs/content/en/reference/components-reference/supported-pubsub/setup-rabbitmq.md
> +By default, Dapr creates `classic` queues. To create `quorum` queues, add the following metadata to your subscription:
@aaguilartablada - Got it. Thanks for the clarification. I closed the other PR (https://github.com/dapr/docs/pull/3193_ and looked at the code in yours to see this change. Suggest adding this link to the subscription format

2023-09-25 03:52 UTC, merged