add clientName and heartBeat metadata for pubsub rabbitmq
dapr/docs pull request #3718
Opened 2023-09-10 09:17 UTC by Taction

Thank you for helping make the Dapr documentation better!

**Please follow this checklist before submitting:**
- [ ] Commits are signed with Developer Certificate of Origin (DCO - [learn more](https://docs.dapr.io/contributing/contributing-overview/#developer-certificate-of-origin-signing-your-work))
- [ ] [Read the contribution guide](https://docs.dapr.io/contributing/docs-contrib/contributing-docs/)
- [ ] Commands include options for Linux, MacOS, and Windows within codetabs
- [ ] New file and folder names are globally unique
- [ ] Page references use shortcodes instead of markdown or URL links
- [ ] Images use HTML style and have alternative text
- [ ] Places where multiple code/command options are given have codetabs

In addition, please fill out the following to help reviewers understand this pull request:

## Description

Add missing content.

## Issue reference

Please reference the issue this PR will close: #3710

2023-09-12 13:46 UTC, hhunter-ms requested changes
quick review - thanks for this PR!

2023-09-12 13:46 UTC, hhunter-ms commented on daprdocs/content/en/reference/components-reference/supported-pubsub/setup-rabbitmq.md
> +| clientName | N | RabbitMQ [client-provided connection name](https://www.rabbitmq.com/connections.html#client-provided-names), this a custom identifier. If set, the identifier will be mentioned in R
```suggestion
| clientName | N | This RabbitMQ [client-provided connection name](https://www.rabbitmq.com/connections.html#client-provided-names) is a custom identifier. If set, the identifier will be mentioned in RabbitMQ server log entries and management UI. Can be set to {uuid}, {podName}, or {appID}, which will be replaced by Dapr runtime to the real value. | `"app1"`, `{uuid}`, `{podName}`, `{appID}`
```

2023-09-13 04:18 UTC, msfussell commented
@Taction please look at the comment and resolve conflicts

2023-09-14 16:52 UTC, hhunter-ms commented
resolved conflicts

2023-09-15 05:36 UTC, Taction commented
@hhunter-ms Thanks for your review and for resolving conflicts!

2023-09-15 22:27 UTC, msfussell commented
@Taction - This PR is in the v1.11 docs, but the code is in v1.12. Can you move this PR to target the v1.12 docs? Thanks

2023-09-17 03:56 UTC, Taction commented
@msfussell Thanks for pointing out that. I opened another pr #3740 to target the v1.12 doc.

2023-09-17 03:56 UTC, closed without merging