Add Outbox docs
dapr/docs pull request #3763
Opened 2023-09-25 16:00 UTC by yaron2

Add documentation for the outbox feature.

Closes https://github.com/dapr/docs/issues/3733.

2023-09-26 04:00 UTC, msfussell reviewed
Here is my review and provided updates

2023-09-26 04:00 UTC, msfussell commented on daprdocs/content/en/developing-applications/building-blocks/state-management/howto-outbox.md
> +The transactional outbox pattern is a well known powerful design pattern for sending notifications about a change in a system's state using a single transaction that spans across the database and mes
```suggestion
The transactional outbox pattern is a well known design pattern for sending notifications about a change in an application's state using a single transaction that spans across the database and the message broker used to deliver the notification. Developers are faced with many difficult technical challenges when trying to implement this pattern on their own, which often involves writing error-prone central coordination managers that end up supporting a combination of one or two databases and message brokers at most.

An example scenario for using the outbox pattern is writing a new user record to an account database and then sending a notification message that the account was successfully created. The user only wants to receive a message if this was successful.
```

2023-09-26 04:00 UTC, msfussell commented on daprdocs/content/en/developing-applications/building-blocks/state-management/howto-outbox.md
> +With Dapr's outbox support, developers can notify subscribers when a system's state is created or updated when calling Dapr's [transactions API]({{< ref "state_api.md#state-transactions" >}}).
```suggestion
With Dapr's outbox support, you can notify subscribers when an application's state is created, updated or deleted when calling Dapr's [transactions API]({{< ref "state_api.md#state-transactions" >}}).
```

2023-09-26 04:00 UTC, msfussell commented on daprdocs/content/en/developing-applications/building-blocks/state-management/howto-outbox.md
> +| outboxPublishPubsub | Yes         | N/A           | Sets the name of the pub/sub to use when publishing state changes
```suggestion
| outboxPublishPubsub | Yes         | N/A           | Sets the name of the pub/sub component to  deliver the notifications when publishing state changes
```

2023-09-26 04:00 UTC, msfussell commented on daprdocs/content/en/developing-applications/building-blocks/state-management/howto-outbox.md
> +| outboxPublishTopic  | Yes         | N/A           | Sets the topic to send the state changes to on the pub/sub configured with `outboxPublishPubsub`
```suggestion
| outboxPublishTopic  | Yes         | N/A           | Sets the topic to send the state changes to on the pub/sub component configured with `outboxPublishPubsub`
```

2023-09-26 04:00 UTC, msfussell commented on daprdocs/content/en/developing-applications/building-blocks/state-management/howto-outbox.md
> +| outboxPubsub        | No          | `outboxPublishPubsub`           | Sets the pub/sub to use for Dapr to coordinate the state and pub/sub transactions. If not set, the pub/sub configured with `out
```suggestion
| outboxPubsub        | No          | `outboxPublishPubsub`           | Sets the pub/sub component to use by Dapr to coordinate the state and pub/sub transactions. If not set, the pub/sub component configured with `outboxPublishPubsub` is used. This is useful if you want to separate the pub/sub component used to send the notification state changes from the one used to coordinate the transaction.
```

2023-09-26 04:00 UTC, msfussell commented on daprdocs/content/en/developing-applications/building-blocks/state-management/howto-outbox.md
> +| outboxDiscardWhenMissingState  | No         | `false`           | By setting `outboxDiscardWhenMissingState` to `true`, Dapr will discard the transaction if it cannot find the state in the database
```suggestion
| outboxDiscardWhenMissingState  | No         | `false`           | By setting `outboxDiscardWhenMissingState` to `true`, Dapr will discard the transaction if it cannot find the state in the database and does not retry again.
```

2023-09-26 04:00 UTC, msfussell commented on daprdocs/content/en/developing-applications/building-blocks/state-management/howto-outbox.md
> +| outboxDiscardWhenMissingState  | No         | `false`           | By setting `outboxDiscardWhenMissingState` to `true`, Dapr will discard the transaction if it cannot find the state in the database
When should this be used? This explains what is does, but also describing why you would set this is needed.

2023-09-26 04:00 UTC, msfussell commented on daprdocs/content/en/developing-applications/building-blocks/state-management/howto-outbox.md
> +The outbox feature can be used with using any [transactional state store]({{< ref supported-state-stores >}}) supported by Dapr. All [Dapr pub/sub brokers]({{< ref supported-pubsub >}}) are supported
```suggestion
The outbox feature can be used with using any [transactional state store]({{< ref supported-state-stores >}}) supported by Dapr. All [pub/sub brokers]({{< ref supported-pubsub >}}) are supported with the outbox feature.
```

2023-09-26 04:00 UTC, msfussell commented on daprdocs/content/en/developing-applications/building-blocks/state-management/howto-outbox.md
> +*Note: Message brokers that work with the competing consumer pattern are encouraged to reduce the chances of duplicate events*
```suggestion
{{% alert title="Note" color="primary" %}} 
Message brokers that work with the competing consumer pattern (for example [Apache Kafka]({{< ref setup-apache-kafka>}}) are encouraged to reduce the chances of duplicate events.
{{% /alert %}}
```

2023-09-26 04:00 UTC, msfussell commented on daprdocs/content/en/developing-applications/building-blocks/state-management/howto-outbox.md
> +The outbox feature can be used with using any [transactional state store]({{< ref supported-state-stores >}}) supported by Dapr. All [Dapr pub/sub brokers]({{< ref supported-pubsub >}}) are supported
If these properties are set on a non-transactional state store, does the Dapr runtime throw an error on loading? If not can it to indicate these are are invalid?

2023-09-26 04:00 UTC, msfussell commented on daprdocs/content/en/developing-applications/building-blocks/state-management/howto-outbox.md
> +If you want to use the same state store for sending both outbox and non-outbox messages, simply define two state store components, where one has the outbox feature and the other does not.
```suggestion
If you want to use the same state store for sending both outbox and non-outbox messages, simply define two state store components that connect to the same state store, where one has the outbox feature and the other does not.
```

2023-09-26 04:00 UTC, msfussell commented on daprdocs/content/en/developing-applications/building-blocks/state-management/howto-outbox.md
> +The outbox feature can be used with using any [transactional state store]({{< ref supported-state-stores >}}) supported by Dapr. All [Dapr pub/sub brokers]({{< ref supported-pubsub >}}) are supported
Is there any metadata setting that is **required** to be set on the pub/sub component? Conversely Is there anything that I should not set that may break the outbox?

2023-09-26 04:00 UTC, msfussell commented on daprdocs/content/en/developing-applications/building-blocks/state-management/howto-outbox.md
> +The outbox feature can be used with using any [transactional state store]({{< ref supported-state-stores >}}) supported by Dapr. All [Dapr pub/sub brokers]({{< ref supported-pubsub >}}) are supported
Can the In-memory message broker be used?

2023-09-26 04:00 UTC, msfussell commented on daprdocs/content/en/developing-applications/building-blocks/state-management/howto-outbox.md
> +If you want to use the same state store for sending both outbox and non-outbox messages, simply define two state store components, where one has the outbox feature and the other does not.
Two questions
1) Is it better to use MySQL as an example here than Redis, given that Redis is not a "True" transactional state store
2) If I do use Redis, could I use the same Redis instance for both the state store and the message broker? Is so, then I would mention this.

2023-09-26 04:00 UTC, msfussell commented on daprdocs/content/en/developing-applications/building-blocks/state-management/howto-outbox.md
> +| outboxPublishTopic  | Yes         | N/A           | Sets the topic to send the state changes to on the pub/sub configured with `outboxPublishPubsub`
Can I configure what is sent in the message body? If not, what is sent in the message body for the topic?

2023-09-26 04:00 UTC, msfussell commented on daprdocs/content/en/developing-applications/building-blocks/state-management/howto-outbox.md
> +With Dapr's outbox support, developers can notify subscribers when a system's state is created or updated when calling Dapr's [transactions API]({{< ref "state_api.md#state-transactions" >}}).
Add the text below....

*****
```
The diagram below is an overview of how the outbox pattern works:
1) Service A saves/updates state to the state store using a transaction.
2) A message is written to the broker under the same transaction. When the message is successfully delivered to the message broker the transaction completes ensuring the state and message are transacted together.
3) The message broker delivers the message topic to any subscribers, in this case Service B.

<img src="/images/state-management-outbox.png" width=800 alt="Diagram showing the steps of the outbox pattern">
```

****

2023-09-26 04:00 UTC, msfussell commented on daprdocs/content/en/developing-applications/building-blocks/state-management/howto-outbox.md
> +With Dapr's outbox support, developers can notify subscribers when a system's state is created or updated when calling Dapr's [transactions API]({{< ref "state_api.md#state-transactions" >}}).
I will send you a PNG file to include into this PR and check into the static/images folder

2023-09-26 04:00 UTC, msfussell commented on daprdocs/content/en/developing-applications/building-blocks/state-management/howto-outbox.md
> +```
Add this at the end

```
## Demo

Watch [this video for an overview of the outbox pattern](https://youtu.be/rTovKpG0rhY?t=1338):

<div class="embed-responsive embed-responsive-16by9">
<iframe width="360" height="315" src="https://youtu.be/rTovKpG0rhY?t=1338" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>
```

2023-09-26 05:02 UTC, yaron2 commented on daprdocs/content/en/developing-applications/building-blocks/state-management/howto-outbox.md
> +With Dapr's outbox support, developers can notify subscribers when a system's state is created or updated when calling Dapr's [transactions API]({{< ref "state_api.md#state-transactions" >}}).
The suggested change is incorrect, outbox is about notifying when data has been created or inserted, not deleted.

2023-09-26 05:05 UTC, yaron2 commented on daprdocs/content/en/developing-applications/building-blocks/state-management/howto-outbox.md
> +| outboxPublishTopic  | Yes         | N/A           | Sets the topic to send the state changes to on the pub/sub configured with `outboxPublishPubsub`
No, you can't and shouldn't be able to configure what's in the message body. The message body is what is saved to the state store. I added language to make that clear, even though it's likely an overkill.

2023-09-26 05:09 UTC, yaron2 commented on daprdocs/content/en/developing-applications/building-blocks/state-management/howto-outbox.md
> +```
Done

2023-09-26 05:13 UTC, yaron2 commented on daprdocs/content/en/developing-applications/building-blocks/state-management/howto-outbox.md
> +If you want to use the same state store for sending both outbox and non-outbox messages, simply define two state store components, where one has the outbox feature and the other does not.
Yes, I switched to MySQL as its a better example.

2023-09-26 05:15 UTC, yaron2 commented on daprdocs/content/en/developing-applications/building-blocks/state-management/howto-outbox.md
> +The outbox feature can be used with using any [transactional state store]({{< ref supported-state-stores >}}) supported by Dapr. All [Dapr pub/sub brokers]({{< ref supported-pubsub >}}) are supported
> If these properties are set on a non-transactional state store, does the Dapr runtime throw an error on loading? If not can it to indicate these are are invalid?

The user will get an error when trying to use the transactions API on a non-transactional state store.

2023-09-26 05:15 UTC, yaron2 commented on daprdocs/content/en/developing-applications/building-blocks/state-management/howto-outbox.md
> +The outbox feature can be used with using any [transactional state store]({{< ref supported-state-stores >}}) supported by Dapr. All [Dapr pub/sub brokers]({{< ref supported-pubsub >}}) are supported
> Is there any metadata setting that is required to be set on the pub/sub component? Conversely Is there anything that I should not set that may break the outbox?

No, nothing is required on the pub/sub component and there's no way to break it.

2023-09-26 05:16 UTC, yaron2 commented on daprdocs/content/en/developing-applications/building-blocks/state-management/howto-outbox.md
> +The outbox feature can be used with using any [transactional state store]({{< ref supported-state-stores >}}) supported by Dapr. All [Dapr pub/sub brokers]({{< ref supported-pubsub >}}) are supported
> Can the In-memory message broker be used?

Yes

2023-09-26 05:26 UTC, yaron2 commented
@msfussell all feedback has been addressed

2023-09-27 21:48 UTC, msfussell commented
@hhunter-ms - LGTM. Any feedback on this?

2023-10-03 15:51 UTC, hhunter-ms requested changes, later dismissed
quick grammar review

2023-10-03 15:51 UTC, hhunter-ms commented on daprdocs/content/en/developing-applications/building-blocks/state-management/howto-outbox.md
> +The transactional outbox pattern is a well known design pattern for sending notifications about a change in an application's state using a single transaction that spans across the database and the me
```suggestion
The transactional outbox pattern is a well known design pattern for sending notifications regarding changes in an application's state. The transactional outbox pattern uses a single transaction that spans across the database and the message broker delivering the notification. 

Developers are faced with many difficult technical challenges when trying to implement this pattern on their own, which often involves writing error-prone central coordination managers that, at most, support a combination of one or two databases and message brokers.
```

2023-10-03 15:51 UTC, hhunter-ms commented on daprdocs/content/en/developing-applications/building-blocks/state-management/howto-outbox.md
> +An example scenario for using the outbox pattern is writing a new user record to an account database and then sending a notification message that the account was successfully created. The user only w
```suggestion
For example, you can use the outbox pattern to:  
1. Write a new user record to an account database. 
1. Send a notification message that the account was successfully created. 
```

I feel like the example scenario might help the doc flow better if moved under line 13...

2023-10-03 15:51 UTC, hhunter-ms commented on daprdocs/content/en/developing-applications/building-blocks/state-management/howto-outbox.md
> +2) A message is written to the broker under the same transaction. When the message is successfully delivered to the message broker the transaction completes ensuring the state and message are transac
```suggestion
2) A message is written to the broker under the same transaction. When the message is successfully delivered to the message broker, the transaction completes, ensuring the state and message are transacted together.
```

2023-10-03 15:51 UTC, hhunter-ms commented on daprdocs/content/en/developing-applications/building-blocks/state-management/howto-outbox.md
> +3) The message broker delivers the message topic to any subscribers, in this case Service B.
```suggestion
3) The message broker delivers the message topic to any subscribers - in this case, Service B.
```

2023-10-03 15:51 UTC, hhunter-ms commented on daprdocs/content/en/developing-applications/building-blocks/state-management/howto-outbox.md
> +Message brokers that work with the competing consumer pattern (for example [Apache Kafka]({{< ref setup-apache-kafka>}}) are encouraged to reduce the chances of duplicate events.
```suggestion
Message brokers that work with the competing consumer pattern (for example, [Apache Kafka]({{< ref setup-apache-kafka>}}) are encouraged to reduce the chances of duplicate events.
```

2023-10-03 15:51 UTC, hhunter-ms commented on daprdocs/content/en/developing-applications/building-blocks/state-management/howto-outbox.md
> +| outboxPublishTopic  | Yes         | N/A           | Sets the topic to send the state changes to on the pub/sub configured with `outboxPublishPubsub`. The message body will be a state transaction it
```suggestion
| outboxPublishTopic  | Yes         | N/A           | Sets the topic that receives the state changes on the pub/sub configured with `outboxPublishPubsub`. The message body will be a state transaction item for an `insert` or `update` operation
```

2023-10-03 15:51 UTC, hhunter-ms commented on daprdocs/content/en/developing-applications/building-blocks/state-management/howto-outbox.md
> +| outboxPubsub        | No          | `outboxPublishPubsub`           | Sets the pub/sub component to use by Dapr to coordinate the state and pub/sub transactions. If not set, the pub/sub component c
```suggestion
| outboxPubsub        | No          | `outboxPublishPubsub`           | Sets the pub/sub component used by Dapr to coordinate the state and pub/sub transactions. If not set, the pub/sub component configured with `outboxPublishPubsub` is used. This is useful if you want to separate the pub/sub component used to send the notification state changes from the one used to coordinate the transaction
```

2023-10-03 15:51 UTC, hhunter-ms commented on daprdocs/content/en/developing-applications/building-blocks/state-management/howto-outbox.md
> +| outboxDiscardWhenMissingState  | No         | `false`           | By setting `outboxDiscardWhenMissingState` to `true`, Dapr will discard the transaction if it cannot find the state in the database
```suggestion
| outboxDiscardWhenMissingState  | No         | `false`           | By setting `outboxDiscardWhenMissingState` to `true`, Dapr discards the transaction if it cannot find the state in the database and does not retry. This setting can be useful if the state store data has been deleted for any reason before Dapr was able to deliver the message and you would like Dapr to drop the items from the pub/sub and stop retrying to fetch the state
```

2023-10-03 16:41 UTC, yaron2 commented
> quick grammar review

@hhunter-ms changes made.

2023-10-03 17:01 UTC, msfussell approved these changes
LGTM

2023-10-03 17:02 UTC, merged