Component Hot Reloading
dapr/docs pull request #3910
Opened 2023-12-19 16:42 UTC by JoshVanL

Adds documentation for the preview feature `Component Hot Reloading`

Part of https://github.com/dapr/dapr/issues/1172

2024-01-04 20:52 UTC, hhunter-ms commented
@JoshVanL could you also update this doc for hot reloading as well? https://docs.dapr.io/operations/components/component-updates/
 
- Add a section above 'Kubernetes' to briefly explain
- Reword anywhere that implies components can't be updated automatically
- Clarify if this applies to every component, including middleware?

2024-01-06 02:37 UTC, msfussell commented on daprdocs/content/en/concepts/components-concept.md
> +With the [`HotReload` feature enabled]({{< ref "support-preview-features.md" >}}), Components are able to be "hot reloaded" at runtime.
```suggestion
With the [`HotReload` feature enabled]({{< ref "support-preview-features.md" >}}), components are able to be "hot reloaded" at runtime.
```

2024-01-06 02:37 UTC, msfussell commented on daprdocs/content/en/concepts/components-concept.md
> +Component reloading happens when a Component resource is created, updated, or deleted, either in the Kubernetes API or in Self Hosted mode when a file is changed in the `resources` directory.
```suggestion
Component reloading happens when a component resource is created, updated, or deleted, either in the Kubernetes API or in Self Hosted mode when a file is changed in the `resources` directory.
```

2024-01-06 02:37 UTC, msfussell commented on daprdocs/content/en/concepts/components-concept.md
> +When a component is updated, the Component is first closed, and then reinitialized using the new configuration.
```suggestion
When a component is updated, the component is first closed, and then reinitialized using the new configuration.
```

2024-01-06 02:37 UTC, msfussell commented on daprdocs/content/en/concepts/components-concept.md
> +There will be a short period of time where the component is unavailable during the duration of the reload until the component is reinitialized.
```suggestion
There is a short period of time where the component is unavailable during the duration of the reload until the component is reinitialized.
```

2024-01-09 14:15 UTC, JoshVanL commented
Thanks @hhunter-ms @msfussell, I have added your suggestions.

> Will hot reloading be a default when not in preview?

@hhunter-ms indeed, the plan to have this be the default and only option once HotReloading comes out of preview.

2024-01-10 16:04 UTC, hhunter-ms requested changes
quick review

2024-01-10 16:04 UTC, hhunter-ms commented on daprdocs/content/en/operations/components/component-updates.md
> +How this done depends on the hosting environment.
```suggestion
How this is done depends on the hosting environment.
```

2024-01-10 16:04 UTC, hhunter-ms commented on daprdocs/content/en/operations/components/component-updates.md
> +2. (Unless the [`HotReload` feature gate is enabled]({{< ref "support-preview-features.md" >}})), perform a [rollout restart operation](https://kubernetes.io/docs/reference/kubectl/cheatsheet/#updati
```suggestion
1. Unless the [`HotReload` feature gate is enabled]({{< ref "support-preview-features.md" >}}), perform a [rollout restart operation](https://kubernetes.io/docs/reference/kubectl/cheatsheet/#updating-resources) on your deployments to pick up the latest component
```

2024-01-10 16:04 UTC, hhunter-ms commented on daprdocs/content/en/operations/components/component-updates.md
>  1. Applying the new component YAML to the desired namespace
```suggestion
1. Apply the new component YAML to the desired namespace
```

2024-01-10 16:04 UTC, hhunter-ms commented on daprdocs/content/en/operations/components/component-updates.md
> +Unless the [`HotReload` feature gate is enabled]({{< ref "support-preview-features.md" >}}), the process of updating a component involves a single step of stopping the `daprd` process and starting it
```suggestion
Unless the [`HotReload` feature gate is enabled]({{< ref "support-preview-features.md" >}}), the process of updating a component involves a single step of stopping and restarting the `daprd` process to pick up the latest component.
```

2024-01-10 16:04 UTC, hhunter-ms commented on daprdocs/content/en/operations/support/support-preview-features.md
> +| **Component Hot Reloading** | Allows for dapr loaded Components to be "hot reloaded". A Component spec will be reloaded when it is created/updated/deleted in Kubernetes or on file when running in S
```suggestion
| **Component Hot Reloading** | Allows for Dapr-loaded components to be "hot reloaded". A component spec is reloaded when it is created/updated/deleted in Kubernetes or on file when running in self-hosted mode.| `HotReload`| [Hot Reloading]({{< ref components-concept.md >}}) | v1.13  |
```

2024-01-10 16:04 UTC, hhunter-ms commented on daprdocs/content/en/concepts/components-concept.md
> +Component reloading happens when a component resource is created, updated, or deleted, either in the Kubernetes API or in Self Hosted mode when a file is changed in the `resources` directory.
```suggestion
Component reloading occurs when a component resource is created, updated, or deleted, either in the Kubernetes API or in self-hosted mode when a file is changed in the `resources` directory.
```

2024-01-10 16:04 UTC, hhunter-ms commented on daprdocs/content/en/concepts/components-concept.md
> +There is a short period of time where the component is unavailable during the duration of the reload until the component is reinitialized.
```suggestion
The component is unavailable for a short period of time during reload and reinitialization.
```

2024-01-10 16:04 UTC, hhunter-ms commented on daprdocs/content/en/operations/components/component-updates.md
> +Dapr can be made to "hot reload" components where updates will be picked up automatically without needing a restart.
```suggestion
Dapr can be made to "hot reload" components, where updates are picked up automatically without needing a restart.
```

2024-01-11 22:32 UTC, hhunter-ms approved these changes

2024-01-11 22:34 UTC, merged