Adding recursive terminate/purge in workflow API
dapr/docs pull request #3969
Opened 2024-01-25 09:42 UTC by shivamkm07

Thank you for helping make the Dapr documentation better!

**Please follow this checklist before submitting:**
- [ ] Commits are signed with Developer Certificate of Origin (DCO - [learn more](https://docs.dapr.io/contributing/contributing-overview/#developer-certificate-of-origin-signing-your-work))
- [ ] [Read the contribution guide](https://docs.dapr.io/contributing/docs-contrib/contributing-docs/)
- [ ] Commands include options for Linux, MacOS, and Windows within codetabs
- [ ] New file and folder names are globally unique
- [ ] Page references use shortcodes instead of markdown or URL links
- [ ] Images use HTML style and have alternative text
- [ ] Places where multiple code/command options are given have codetabs

In addition, please fill out the following to help reviewers understand this pull request:

## Description

This PR adds details about recursive termination/purge of child workflows in workflow api documentation.

## Issue reference

<!--Please reference the issue this PR will close: #3949

2024-01-25 20:53 UTC, hhunter-ms requested changes
quick review

2024-01-25 20:53 UTC, hhunter-ms commented on daprdocs/content/en/reference/api/workflow_api.md
> +`non_recursive` | (Optional) Boolean to determine if Dapr should not recursively purge child workflows created by the workflow instance, default value is false.
```suggestion
`non_recursive` | (Optional) Boolean to determine if Dapr should not recursively purge child workflows created by the workflow instance. Default value is `false`.
```

2024-01-25 20:53 UTC, hhunter-ms commented on daprdocs/content/en/reference/api/workflow_api.md
> + Purging a workflow will purge all of the child workflows created by the workflow instance. This can be disabled by setting the query parameter `non_recursive` to `true`.
```suggestion
 Purging a workflow purges all of the child workflows created by the workflow instance. You can disable this by setting the query parameter `non_recursive` to `true`.
```

2024-01-25 20:53 UTC, hhunter-ms commented on daprdocs/content/en/reference/api/workflow_api.md
> +`non_recursive` | (Optional) Boolean to determine if Dapr should not recursively terminate child workflows created by the workflow instance, default value is false.
```suggestion
`non_recursive` | (Optional) Boolean to determine if Dapr should not recursively terminate child workflows created by the workflow instance. Default value is `false`.
```

2024-01-25 20:53 UTC, hhunter-ms commented on daprdocs/content/en/reference/api/workflow_api.md
> + Terminating a workflow will terminate all of the child workflows created by the workflow instance. This can be disabled by setting the query parameter `non_recursive` to `true`.
```suggestion
 Terminating a workflow terminates all of the child workflows created by the workflow instance. You can disable this by setting the query parameter `non_recursive` to `true`. 
```

2024-01-25 20:53 UTC, hhunter-ms commented on daprdocs/content/en/reference/api/workflow_api.md
> + Terminating a workflow will have no effect on any in-flight activity executions that were started by the terminated instance.
```suggestion
Terminating a workflow has no effect on any in-flight activity executions that were started by the terminated instance. 
```

2024-01-29 15:52 UTC, hhunter-ms approved these changes

2024-01-29 17:34 UTC, msfussell commented
@shivamkm07 - This needs more updates in the docs. Specifically we should cover this in the Child workflows section
1) Add a paragraph here https://docs.dapr.io/developing-applications/building-blocks/workflow/workflow-overview/#child-workflows and remove the Note since this is no longer true
2) Mention here https://docs.dapr.io/developing-applications/building-blocks/workflow/workflow-overview/#child-workflows that child workflows can be terminated from the parent workflow. 
3) Nit: I think it is very strange that we called the property non-recursive and set this to false. Calling this "recursive" and true is more intuitive. Can we change this?
4) @hhunter-ms - There are no feature docs on purge capability. We should add these into the feature and concepts doc https://docs.dapr.io/developing-applications/building-blocks/workflow/workflow-features-concepts/

2024-01-31 15:59 UTC, shivamkm07 commented
> @shivamkm07 - This needs more updates in the docs. Specifically we should cover this in the Child workflows section
> 
> 1. Add a paragraph here https://docs.dapr.io/developing-applications/building-blocks/workflow/workflow-overview/#child-workflows and remove the Note since this is no longer true
> 2. Mention here https://docs.dapr.io/developing-applications/building-blocks/workflow/workflow-overview/#child-workflows that child workflows can be terminated from the parent workflow.
> 3. Nit: I think it is very strange that we called the property non-recursive and set this to false. Calling this "recursive" and true is more intuitive. Can we change this?
> 4. @hhunter-ms - There are no feature docs on purge capability. We should add these into the feature and concepts doc https://docs.dapr.io/developing-applications/building-blocks/workflow/workflow-features-concepts/

Thanks for the review. Will add sections accordingly.
>Nit: I think it is very strange that we called the property non-recursive and set this to false. Calling this "recursive" and true is more intuitive. Can we change this?

This was actually decided to kept as `non_recursive` so that the default value of flag is false. The default behavior intended is to be recursive, and keeping the `recursive` flag would make us to set the default value be true: https://github.com/dapr/dapr/pull/7340#discussion_r1453865073

2024-01-31 16:28 UTC, hhunter-ms commented
> 4. There are no feature docs on purge capability. We should add these into the feature and concepts doc https://docs.dapr.io/developing-applications/building-blocks/workflow/workflow-features-concepts/

@shivamkm07 @msfussell I can do this in a separate PR, unless Shivam you'd rather take this?

2024-01-31 17:20 UTC, shivamkm07 commented
> > 4. There are no feature docs on purge capability. We should add these into the feature and concepts doc https://docs.dapr.io/developing-applications/building-blocks/workflow/workflow-features-concepts/
> 
> @shivamkm07 @msfussell I can do this in a separate PR, unless Shivam you'd rather take this?

Sure, feel free to create separate PR for this. I will include 1 and 2 above in this PR.

2024-02-01 10:27 UTC, shivamkm07 commented
> @shivamkm07 - This needs more updates in the docs. Specifically we should cover this in the Child workflows section
> 
> 1. Add a paragraph here https://docs.dapr.io/developing-applications/building-blocks/workflow/workflow-overview/#child-workflows and remove the Note since this is no longer true
> 2. Mention here https://docs.dapr.io/developing-applications/building-blocks/workflow/workflow-overview/#child-workflows that child workflows can be terminated from the parent workflow.
> 3. Nit: I think it is very strange that we called the property non-recursive and set this to false. Calling this "recursive" and true is more intuitive. Can we change this?
> 4. @hhunter-ms - There are no feature docs on purge capability. We should add these into the feature and concepts doc https://docs.dapr.io/developing-applications/building-blocks/workflow/workflow-features-concepts/

@msfussell @hhunter-ms Added requested changes 1 and 2. Please review.

2024-02-01 20:26 UTC, merged