Update limitation for js
dapr/docs pull request #3982
Opened 2024-01-27 13:40 UTC by kaibocai

Update limitation for js

Thank you for helping make the Dapr documentation better!

**Please follow this checklist before submitting:**
- [ ] Commits are signed with Developer Certificate of Origin (DCO - [learn more](https://docs.dapr.io/contributing/contributing-overview/#developer-certificate-of-origin-signing-your-work))
- [ ] [Read the contribution guide](https://docs.dapr.io/contributing/docs-contrib/contributing-docs/)
- [ ] Commands include options for Linux, MacOS, and Windows within codetabs
- [ ] New file and folder names are globally unique
- [ ] Page references use shortcodes instead of markdown or URL links
- [ ] Images use HTML style and have alternative text
- [ ] Places where multiple code/command options are given have codetabs

In addition, please fill out the following to help reviewers understand this pull request:

## Description

## Issue reference

2024-01-29 15:15 UTC, hhunter-ms requested changes
Could you also change this PR to point to branch `v1.13`?

2024-01-29 15:15 UTC, hhunter-ms commented on daprdocs/content/en/developing-applications/building-blocks/workflow/workflow-features-concepts.md
> +```javascript
```suggestion
{{% codetab %}}

```javascript
```

2024-01-29 15:15 UTC, hhunter-ms commented on daprdocs/content/en/developing-applications/building-blocks/workflow/workflow-features-concepts.md
> +```javascript
this should fix the build error in the PR

2024-01-30 22:51 UTC, msfussell commented
@kaibocai - Ping on the above request.

2024-01-31 19:48 UTC, hhunter-ms approved these changes

2024-01-31 19:59 UTC, merged