Sentry Token Validator spec
dapr/docs pull request #4017
Opened 2024-02-06 14:06 UTC by JoshVanL

Adds documentation about sentry token validator spec, and control plane trust domain.

Closes https://github.com/dapr/docs/issues/4001

2024-02-07 05:23 UTC, msfussell reviewed
@JoshVanL Left some early comments. As always, if there is more you can add on the scenarios of when this would be useful, that helps tremendously. So add more of the why if possible.

2024-02-07 05:23 UTC, msfussell commented on daprdocs/content/en/operations/security/mtls.md
> +### Sentry Token Validators
```suggestion
## Sentry service token validators
```

2024-02-07 05:23 UTC, msfussell commented on daprdocs/content/en/operations/security/mtls.md
> +
Tokens are often used for authentication and authorization purposes. Token validators are components responsible for verifying the validity and authenticity of these tokens. For example in Kubernetes environments, a common approach to token validation is through the Kubernetes service account mechanism. This validator checks tokens against Kubernetes service accounts to ensure their legitimacy.

2024-02-07 05:23 UTC, msfussell commented on daprdocs/content/en/operations/security/mtls.md
> +Sentry can be configured to enable extra token validators beyond the Kubernetes bound Service Account validator, or replace the `insecure` validator enabled by default in self hosted mode.
```suggestion
Sentry service can be configured to enable extra token validators beyond the Kubernetes bound Service Account validator, or replace the `insecure` validator enabled by default in self hosted mode.
```

2024-02-07 05:23 UTC, msfussell commented on daprdocs/content/en/operations/security/mtls.md
> +The `jwks` validator enables Sentry to validate JWT tokens using a JWKS endpoint.
```suggestion
The `jwks` validator enables Sentry service to validate JWT tokens using a JWKS endpoint.
```

2024-02-07 05:23 UTC, msfussell commented on daprdocs/content/en/operations/security/mtls.md
> +The audience of the token must by the SPIFFE ID of the Sentry identity, e.g. `spiffe://cluster.local/ns/dapr-system/dapr-sentry`.
```suggestion
The audience of the token must by the SPIFFE ID of the Sentry identity. For example, `spiffe://cluster.local/ns/dapr-system/dapr-sentry`.
```

2024-02-07 05:23 UTC, msfussell commented on daprdocs/content/en/operations/security/mtls.md
> +
Can you add a description for the example. Something like
"The configuration example below shows..."

2024-02-07 05:23 UTC, msfussell commented on daprdocs/content/en/operations/security/mtls.md
> +
Same here for a description of this example.

2024-02-07 14:23 UTC, hhunter-ms requested changes
small review on my part

2024-02-07 14:23 UTC, hhunter-ms commented on daprdocs/content/en/operations/security/mtls.md
> +Sentry can be configured to enable extra token validators beyond the Kubernetes bound Service Account validator, or replace the `insecure` validator enabled by default in self hosted mode.
```suggestion
Sentry can be configured to:
- Enable extra token validators beyond the Kubernetes-bound Service Account validator, or
- Replace the `insecure` validator enabled by default in self-hosted mode
```

2024-02-07 14:23 UTC, hhunter-ms commented on daprdocs/content/en/operations/security/mtls.md
> +These are useful for joining extra non-Kubernetes clients to the Dapr cluster running in Kubernetes mode, or replacing the insecure "allow all" validator in self hosted mode to enable proper identity
```suggestion
You can join extra non-Kubernetes clients to the Dapr cluster running in Kubernetes mode, or replace the insecure "allow all" validator in self-hosted mode to enable proper identity validation.
```

2024-02-07 14:23 UTC, hhunter-ms commented on daprdocs/content/en/operations/security/mtls.md
> +The only token validator currently supported is the `jwks` validator.
```suggestion
> The only token validator currently supported is the `jwks` validator.
```

2024-02-09 16:47 UTC, msfussell approved these changes
LGTM

2024-02-09 16:50 UTC, hhunter-ms approved these changes

2024-02-09 16:55 UTC, merged