Hot reloading: add notes about the behaviour and exceptions
dapr/docs pull request #4027
Opened 2024-02-08 22:59 UTC by JoshVanL

Moves hot reloading to a separate section in `component-updates.md`.

Adds notes about the behaviour of hot reloading regarding downtime and respecting init errors.

Adds exceptions to the component types ignored by hot reloading.

2024-02-09 17:19 UTC, hhunter-ms requested changes
initial review

2024-02-09 17:19 UTC, hhunter-ms commented on daprdocs/content/en/operations/components/component-updates.md
> +> This feature is currently in [preview]({{< ref "preview-features.md" >}}).
```suggestion
{{% alert title="Note" color="primary" %}}
This feature is currently in [preview]({{< ref "preview-features.md" >}}).
```

2024-02-09 17:19 UTC, hhunter-ms commented on daprdocs/content/en/operations/components/component-updates.md
> +> Hot reloading is enabled by via the [`HotReload` feature gate]({{< ref "support-preview-features.md" >}}).
```suggestion
Hot reloading is enabled by via the [`HotReload` feature gate]({{< ref "support-preview-features.md" >}}).
{{% /alert %}}
```

2024-02-09 17:19 UTC, hhunter-ms commented on daprdocs/content/en/operations/components/component-updates.md
> +Dapr can be made to "hot reload" components whereby component updates are picked up automatically without the need to restart the Dapr sidecar process or Kubernetes pod.
```suggestion
Dapr can be made to "hot reload" components, whereby component updates are picked up automatically without needing to restart the Dapr sidecar process or Kubernetes pod.
```

2024-02-09 17:19 UTC, hhunter-ms commented on daprdocs/content/en/operations/components/component-updates.md
> +This means creating, updating, or deleting a component manifest will be reflected in the Dapr sidecar during runtime.
```suggestion
This means creating, updating, or deleting a component manifest is reflected in the Dapr sidecar during runtime.
```

2024-02-09 17:19 UTC, hhunter-ms commented on daprdocs/content/en/operations/components/component-updates.md
> +When a component is updated it will be first closed, then re-initialized using the new configuration.
```suggestion
When a component is updated, it's first closed, then re-initialized using the new configuration.
```

2024-02-09 17:19 UTC, hhunter-ms commented on daprdocs/content/en/operations/components/component-updates.md
> +This will cause the component to be unavailable for a short period of time during this process.
```suggestion
This causes the component to be unavailable for a short period of time during this process.
```

2024-02-09 17:19 UTC, hhunter-ms commented on daprdocs/content/en/operations/components/component-updates.md
> +If the initialization processes errors when a component is created or updated through hot reloading, the Dapr sidecar will respect the component field [`spec.ignoreErrors`]({{< ref component-schema.m
```suggestion
If the initialization processes errors when a component is created or updated through hot reloading, the Dapr sidecar respects the component field [`spec.ignoreErrors`]({{< ref component-schema.md>}}).
```

2024-02-09 17:19 UTC, hhunter-ms commented on daprdocs/content/en/operations/components/component-updates.md
> +- `spec.ignoreErrors=false` (*default*): the sidecar will gracefully shutdown.
```suggestion
- `spec.ignoreErrors=false` (*default*): the sidecar gracefully shuts down.
```

2024-02-09 17:19 UTC, hhunter-ms commented on daprdocs/content/en/operations/components/component-updates.md
> +- `spec.ignoreErrors=true`: the sidecar will continue to run with neither the old or new component configuration registered.
```suggestion
- `spec.ignoreErrors=true`: the sidecar will continue to run with neither the old or new component configuration registered.
```
```suggestion
- `spec.ignoreErrors=true`: the sidecar continues to run with neither the old or new component configuration registered.
```

2024-02-09 17:19 UTC, hhunter-ms commented on daprdocs/content/en/operations/components/component-updates.md
> +All components are supported for hot reloading except for the following types.
```suggestion
The following component types are _not supported_ for hot reloading. Any create, update, or deletion of these component types are ignored by the sidecar with a restart required to pick up changes:
```

2024-02-09 17:19 UTC, hhunter-ms commented on daprdocs/content/en/operations/components/component-updates.md
> +Any create, update, or deletion of these component types will be ignored by the sidecar with a restart required to pick up changes.
```suggestion
```

2024-02-09 17:19 UTC, hhunter-ms commented on daprdocs/content/en/operations/components/component-updates.md
> +- [Actor State Stores]({{< ref "state_api.md#configuring-state-store-for-actors" >}})
```suggestion
- [Actor state stores]({{< ref "state_api.md#configuring-state-store-for-actors" >}})
```

2024-02-09 17:19 UTC, hhunter-ms commented on daprdocs/content/en/operations/components/component-updates.md
> +- Workflow Backends - TODO: @joshvanl waiting on https://github.com/dapr/docs/issues/3924
```suggestion
- Workflow backends - TODO: @joshvanl waiting on https://github.com/dapr/docs/issues/3924
```

2024-02-09 17:21 UTC, hhunter-ms commented
a bit of this is waiting on dapr/docs#4028

2024-02-15 23:31 UTC, JoshVanL commented
Thanks @hhunter-ms, done!

2024-02-16 23:17 UTC, hhunter-ms approved these changes

2024-02-16 23:27 UTC, msfussell approved these changes

2024-02-17 00:35 UTC, merged