add go limitions
dapr/docs pull request #4052
Opened 2024-02-29 00:12 UTC by mikeee

Thank you for helping make the Dapr documentation better!

**Please follow this checklist before submitting:**
- [x] Commits are signed with Developer Certificate of Origin (DCO - [learn more](https://docs.dapr.io/contributing/contributing-overview/#developer-certificate-of-origin-signing-your-work))
- [ ] [Read the contribution guide](https://docs.dapr.io/contributing/docs-contrib/contributing-docs/)
- [ ] Commands include options for Linux, MacOS, and Windows within codetabs
- [ ] New file and folder names are globally unique
- [ ] Page references use shortcodes instead of markdown or URL links
- [ ] Images use HTML style and have alternative text
- [ ] Places where multiple code/command options are given have codetabs

In addition, please fill out the following to help reviewers understand this pull request:

## Description

Add limitations as requested for the go-sdk workflow implementation

## Issue reference

This PR will close: ##4040

2024-02-29 04:18 UTC, msfussell approved these changes, later dismissed
LGTM

2024-03-01 14:44 UTC, hhunter-ms requested changes

2024-03-01 14:44 UTC, hhunter-ms commented on daprdocs/content/en/developing-applications/building-blocks/workflow/workflow-features-concepts.md
> +
@mikeee does this section and the 'do this' section on L373 need examples/content? or does it not apply for Go?

2024-03-01 23:32 UTC, msfussell approved these changes
LGTM

2024-03-04 15:07 UTC, hhunter-ms approved these changes

2024-03-04 15:07 UTC, merged