Updates docs for 1.13.3
dapr/docs pull request #4156
Opened 2024-05-21 21:02 UTC by elena-kolevska

## Description
Updates for Dapr v1.13.3

2024-05-21 21:09 UTC, JoshVanL requested changes

2024-05-21 21:09 UTC, JoshVanL commented on daprdocs/content/en/operations/support/support-release-policy.md
Please also update: 

https://github.com/dapr/docs/blob/cc6e95de50641b26e68c8466f940b41ab251898e/daprdocs/content/en/reference/cli/dapr-init.md?plain=1#L77

https://github.com/dapr/docs/blob/v1.13/daprdocs/layouts/shortcodes/dapr-latest-version.html

2024-05-21 22:49 UTC, elena-kolevska commented on daprdocs/content/en/operations/support/support-release-policy.md
Done. Thanks.

2024-05-22 13:09 UTC, hhunter-ms approved these changes

2024-05-22 13:10 UTC, merged

2024-06-17 14:43 UTC, marcduiker commented
@holopin-bot @elena-kolevska Enjoy your Dapr docs badge!