Update Reporting security issues
dapr/docs pull request #4210
Opened 2024-06-17 22:06 UTC by artursouza

Thank you for helping make the Dapr documentation better!

**Please follow this checklist before submitting:**
- [ ] Commits are signed with Developer Certificate of Origin (DCO - [learn more](https://docs.dapr.io/contributing/contributing-overview/#developer-certificate-of-origin-signing-your-work))
- [ ] [Read the contribution guide](https://docs.dapr.io/contributing/docs-contrib/contributing-docs/)
- [ ] Commands include options for Linux, MacOS, and Windows within codetabs
- [ ] New file and folder names are globally unique
- [ ] Page references use shortcodes instead of markdown or URL links
- [ ] Images use HTML style and have alternative text
- [ ] Places where multiple code/command options are given have codetabs

In addition, please fill out the following to help reviewers understand this pull request:

## Description

## Issue reference

2024-06-18 17:36 UTC, hhunter-ms requested changes
nits

2024-06-18 17:36 UTC, hhunter-ms commented on daprdocs/content/en/operations/support/support-security-issues.md
> +repositories above, then it recommended to create a GitHub issue in the appropriate repo or a question in Discord.
```suggestion
repositories above, then it's recommended to create a GitHub issue in the appropriate repo or raise a question in Discord.
```

2024-06-18 17:36 UTC, hhunter-ms commented on daprdocs/content/en/operations/support/support-security-issues.md
> +All that said, **if you're unsure** please reach out using this process before
```suggestion
**If you're unsure,** err on the side of caution and reach out using the reporting process before
```

2024-06-18 17:36 UTC, hhunter-ms commented on daprdocs/content/en/operations/support/support-security-issues.md
> +raising your issue through another channel. We'd rather err on the side of
```suggestion
raising your issue through GitHub, Discord, or another channel. 
```

2024-06-18 17:36 UTC, hhunter-ms commented on daprdocs/content/en/operations/support/support-security-issues.md
> +caution!
```suggestion
```

2024-06-18 17:36 UTC, hhunter-ms commented on daprdocs/content/en/operations/support/support-security-issues.md
> +reported by the tool _actually exists_ in Dapr, including CLI, SDKs, components-contrib
```suggestion
reported by the tool _actually exists_ in Dapr, including the CLI, Dapr SDKs, the components-contrib repo,
```

2024-06-18 17:36 UTC, hhunter-ms commented on daprdocs/content/en/operations/support/support-security-issues.md
> +If we receive a report which seems to simply be a vulnerability list from a scanner we
```suggestion
If we receive a report which seems to simply be a vulnerability list from a scanner, we
```

2024-06-18 17:36 UTC, hhunter-ms commented on daprdocs/content/en/operations/support/support-security-issues.md
> +differences. That said, the maintainers team will endeavour to reply as
```suggestion
differences. That said, the maintainers team endeavours to reply as
```

2024-06-18 17:36 UTC, hhunter-ms commented on daprdocs/content/en/operations/support/support-security-issues.md
> +team will discuss the next steps together as soon as possible, ideally
```suggestion
team discuss the next steps together as soon as possible, ideally
```

2024-06-18 17:36 UTC, hhunter-ms commented on daprdocs/content/en/operations/support/support-security-issues.md
> +one of the team will respond to the reporter acknowledging the issue and
```suggestion
one of the team responds to the reporter acknowledging the issue and
```

2024-06-19 18:52 UTC, msfussell commented on daprdocs/content/en/operations/support/support-security-issues.md
> +The Dapr project and maintainers make security a central focus of how we operate and design our software. From the Dapr binaries to the GitHub release processes, we take numerous steps to ensure user
```suggestion
The Dapr project and maintainers make security a central focus of how we operate and design our software. From the Dapr binaries to the GitHub release processes, we take numerous steps to ensure user applications and data is secure. For more information on Dapr security features, visit the [security page]({{< ref security-concept.md >}}).
```

2024-06-19 18:52 UTC, msfussell commented on daprdocs/content/en/operations/support/support-security-issues.md
> +## Covered Repositories and Issues
```suggestion
## Repositories and issues covered
```

2024-06-19 18:52 UTC, msfussell commented on daprdocs/content/en/operations/support/support-security-issues.md
> +When we say "a security vulnerability in Dapr" we mean a security issue
```suggestion
When we say "a security vulnerability in Dapr", this means a security issue
```

2024-06-19 18:52 UTC, msfussell commented on daprdocs/content/en/operations/support/support-security-issues.md
> +repositories above, then it recommended to create a GitHub issue in the appropriate repo or a question in Discord.
```suggestion
repositories above, then it recommended to create a GitHub issue in the appropriate repo or ask a question on Discord server.
```

2024-06-19 18:52 UTC, msfussell commented on daprdocs/content/en/operations/support/support-security-issues.md
> +We make use of these tools ourselves and try to act on the output they produce; they
```suggestion
We make use of these tools ourselves and try to act on the output they produce.
```

2024-06-19 18:52 UTC, msfussell commented on daprdocs/content/en/operations/support/support-security-issues.md
> +The people who should have access to read your security report are listed in [`maintainers.csv`](/maintainers.csv).
```suggestion
The people who should have access to read your security report are listed in [`maintainers.md`](https://github.com/dapr/community/blob/master/MAINTAINERS.md).
```

2024-06-19 18:52 UTC, msfussell commented on daprdocs/content/en/operations/support/support-security-issues.md
> +   to be a security issue in Dapr, if that's not obvious.
```suggestion
   to be a security issue in Dapr.
```

2024-06-22 04:03 UTC, msfussell commented on daprdocs/content/en/operations/support/support-security-issues.md
> +can be useful! We tend to find, however, that when these reports are sent to our security
```suggestion
We tend to find, however, that when these reports are sent to our security
```

2024-06-22 04:06 UTC, msfussell approved these changes
LGTM

2024-06-25 15:25 UTC, hhunter-ms approved these changes

2024-06-25 15:33 UTC, merged

2024-08-15 12:15 UTC, marcduiker commented
@holopin-bot @artursouza Thanks Artur! :)