Updates API ref for jobs. Adds doc on Kubernetes Scheduler persistent
dapr/docs pull request #4256
Opened 2024-07-10 15:23 UTC by JoshVanL

2024-07-10 16:56 UTC, hhunter-ms reviewed
just removing localized links to clear error

2024-07-10 16:56 UTC, hhunter-ms commented on daprdocs/content/en/operations/hosting/kubernetes/kubernetes-persisting-scheduler.md
> +- [Azure AKS Storage Options](https://learn.microsoft.com/en-us/azure/aks/concepts-storage)
```suggestion
- [Azure AKS Storage Options](https://learn.microsoft.com/azure/aks/concepts-storage)
```

2024-07-10 16:56 UTC, hhunter-ms commented on daprdocs/content/en/operations/hosting/kubernetes/kubernetes-persisting-scheduler.md
> +- [VMWare vSphere Storage](https://docs.vmware.com/en/VMware-vSphere/7.0/vmware-vsphere-with-tanzu/GUID-A19F6480-40DC-4343-A5A9-A5D3BFC0742E.html)
```suggestion
- [VMWare vSphere Storage](https://docs.vmware.com/VMware-vSphere/7.0/vmware-vsphere-with-tanzu/GUID-A19F6480-40DC-4343-A5A9-A5D3BFC0742E.html)
```

2024-07-10 16:56 UTC, hhunter-ms commented on daprdocs/content/en/operations/hosting/kubernetes/kubernetes-persisting-scheduler.md
> +- [Alibaba Cloud Disk Storage](https://www.alibabacloud.com/help/en/ack/ack-managed-and-ack-dedicated/user-guide/create-a-pvc)
```suggestion
- [Alibaba Cloud Disk Storage](https://www.alibabacloud.com/help/ack/ack-managed-and-ack-dedicated/user-guide/create-a-pvc)
```

2024-07-15 15:23 UTC, hhunter-ms requested changes
Initial review

2024-07-15 15:23 UTC, hhunter-ms commented on daprdocs/content/en/developing-applications/building-blocks/jobs/howto-schedule-jobs.md
> +By default, Job data is not resilient to [Scheduler]({{< ref scheduler.md >}}) service restarts.
```suggestion
By default, job data is not resilient to [Scheduler]({{< ref scheduler.md >}}) service restarts.
```

2024-07-15 15:23 UTC, hhunter-ms commented on daprdocs/content/en/developing-applications/building-blocks/jobs/jobs-overview.md
> +By default, Job data is not resilient to [Scheduler]({{< ref scheduler.md >}}) service restarts.
```suggestion
By default, job data is not resilient to [Scheduler]({{< ref scheduler.md >}}) service restarts.
```

2024-07-15 15:23 UTC, hhunter-ms commented on daprdocs/content/en/operations/hosting/kubernetes/kubernetes-persisting-scheduler.md
> +The [Scheduler]({{< ref scheduler.md >}}) service is responsible for writing Jobs to its embedded database and scheduling them for execution.
```suggestion
The [Scheduler]({{< ref scheduler.md >}}) service is responsible for writing jobs to its embedded database and scheduling them for execution.
```

2024-07-15 15:23 UTC, hhunter-ms commented on daprdocs/content/en/operations/hosting/kubernetes/kubernetes-persisting-scheduler.md
> +**Job data will be lost during these events**.
```suggestion
```

2024-07-15 15:23 UTC, hhunter-ms commented on daprdocs/content/en/operations/hosting/kubernetes/kubernetes-persisting-scheduler.md
> +By default, the Scheduler service database writes this data to an in-memory ephemeral tempfs volume, meaning that this **data is not persisted across restarts**.
```suggestion
By default, the Scheduler service database writes this data to an in-memory ephemeral tempfs volume, meaning that **this data is not persisted across restarts**. Job data will be lost during these events.
```

2024-07-15 15:23 UTC, hhunter-ms commented on daprdocs/content/en/operations/hosting/kubernetes/kubernetes-persisting-scheduler.md
> +The size this disk should be is determined by how many jobs are expected to be persisted at once however, 64Gb should be more than sufficient for most use cases.
```suggestion
Disk size is determined by how many jobs are expected to be persisted at once; however, 64Gb should be more than sufficient for most use cases.
```

2024-07-15 15:23 UTC, hhunter-ms commented on daprdocs/content/en/operations/hosting/kubernetes/kubernetes-persisting-scheduler.md
> +To make the Scheduler data resilient to restarts, a persistent volume must be mounted to the Scheduler StatefulSet.
```suggestion
To make the Scheduler data resilient to restarts, a persistent volume must be mounted to the Scheduler `StatefulSet`.
```

2024-07-15 15:23 UTC, hhunter-ms commented on daprdocs/content/en/operations/hosting/kubernetes/kubernetes-persisting-scheduler.md
> +Once the persistent volume class has been made available, Dapr can be installed with the following command with Scheduler configured to use the persistent volume class (replace `my-storage-class` wit
```suggestion
Once the persistent volume class is available, you can install Dapr using the following command, with Scheduler configured to use the persistent volume class (replace `my-storage-class` with the name of the storage class):
```

2024-07-15 15:23 UTC, hhunter-ms commented on daprdocs/content/en/operations/hosting/kubernetes/kubernetes-persisting-scheduler.md
> +> If Dapr is already installed, the control plane will need to be completely [uninstalled]({{< ref dapr-uninstall.md >}}) in order for the Scheduler StatefulSet to be recreated with the new persisten
```suggestion
{{% alert title="Note" color="primary" %}}
If Dapr is already installed, the control plane needs to be completely [uninstalled]({{< ref dapr-uninstall.md >}}) in order for the Scheduler `StatefulSet` to be recreated with the new persistent volume.
{{% /alert %}}
```

2024-07-15 15:23 UTC, hhunter-ms commented on daprdocs/content/en/operations/hosting/kubernetes/kubernetes-persisting-scheduler.md
> +    dapr init -k --set dapr_scheduler.cluster.storageClassName=my-storage-class
```suggestion
dapr init -k --set dapr_scheduler.cluster.storageClassName=my-storage-class
```

2024-07-15 15:23 UTC, hhunter-ms commented on daprdocs/content/en/operations/hosting/kubernetes/kubernetes-persisting-scheduler.md
> +    helm upgrade --install dapr dapr/dapr \
```suggestion
helm upgrade --install dapr dapr/dapr \
```

2024-07-15 15:23 UTC, hhunter-ms commented on daprdocs/content/en/operations/hosting/kubernetes/kubernetes-persisting-scheduler.md
> +    --version={{% dapr-latest-version short="true" %}} \
```suggestion
--version={{% dapr-latest-version short="true" %}} \
```

2024-07-15 15:23 UTC, hhunter-ms commented on daprdocs/content/en/operations/hosting/kubernetes/kubernetes-persisting-scheduler.md
> +    --namespace dapr-system \
```suggestion
--namespace dapr-system \
```

2024-07-15 15:23 UTC, hhunter-ms commented on daprdocs/content/en/operations/hosting/kubernetes/kubernetes-persisting-scheduler.md
> +    --create-namespace \
```suggestion
--create-namespace \
```

2024-07-15 15:23 UTC, hhunter-ms commented on daprdocs/content/en/operations/hosting/kubernetes/kubernetes-persisting-scheduler.md
> +    --set dapr_scheduler.cluster.storageClassName=my-storage-class \
```suggestion
--set dapr_scheduler.cluster.storageClassName=my-storage-class \
```

2024-07-15 15:23 UTC, hhunter-ms commented on daprdocs/content/en/operations/hosting/kubernetes/kubernetes-persisting-scheduler.md
> +    --wait
```suggestion
--wait
```

2024-07-15 15:23 UTC, hhunter-ms commented on daprdocs/content/en/operations/hosting/self-hosted/self-hosted-persisting-scheduler.md
> +The [Scheduler]({{< ref scheduler.md >}}) service is responsible for writing Jobs to its embedded database and scheduling them for execution.
```suggestion
The [Scheduler]({{< ref scheduler.md >}}) service is responsible for writing jobs to its embedded database and scheduling them for execution.
```

2024-07-15 15:23 UTC, hhunter-ms commented on daprdocs/content/en/operations/hosting/self-hosted/self-hosted-persisting-scheduler.md
> +By default, the Scheduler service database writes this data to the local volume `dapr_scheduler`, meaning that this **data is persisted across restarts**.
```suggestion
By default, the Scheduler service database writes this data to the local volume `dapr_scheduler`, meaning that **this data is persisted across restarts**.
```

2024-07-15 15:23 UTC, hhunter-ms commented on daprdocs/content/en/operations/hosting/self-hosted/self-hosted-persisting-scheduler.md
> +> If Dapr is already installed, the control plane will need to be completely [uninstalled]({{< ref dapr-uninstall.md >}}) in order for the Scheduler container to be recreated with the new persistent
```suggestion
{{% alert title="Note" color="primary" %}}
If Dapr is already installed, the control plane needs to be completely [uninstalled]({{< ref dapr-uninstall.md >}}) in order for the Scheduler container to be recreated with the new persistent volume.
{{% /alert %}}
```

2024-07-15 15:23 UTC, hhunter-ms commented on daprdocs/content/en/operations/hosting/self-hosted/self-hosted-persisting-scheduler.md
> +    dapr init --scheduler-volume my-scheduler-volume
```suggestion
dapr init --scheduler-volume my-scheduler-volume
```

2024-07-15 15:23 UTC, hhunter-ms commented on daprdocs/content/en/reference/api/jobs_api.md
> +By default, Job data is not resilient to [Scheduler]({{< ref scheduler.md >}}) service restarts.
```suggestion
By default, job data is not resilient to [Scheduler]({{< ref scheduler.md >}}) service restarts.
```

2024-07-15 15:23 UTC, hhunter-ms commented on daprdocs/content/en/reference/api/jobs_api.md
> +> **At least one of `schedule` or `dueTime` must be provided, but they can also be provided together**.
```suggestion
{{% alert title="Note" color="primary" %}}
At least one of `schedule` or `dueTime` must be provided, but they can also be provided together.
{{% /alert %}}
```

2024-07-15 15:23 UTC, hhunter-ms commented on daprdocs/content/en/reference/api/jobs_api.md
> +`data` | A protobuf message `@type` `value` pair. `@type` must be of a [well-known type](https://protobuf.dev/reference/protobuf/google.protobuf). Value is the serialized data.
```suggestion
`data` | A protobuf message `@type`/`value` pair. `@type` must be of a [well-known type](https://protobuf.dev/reference/protobuf/google.protobuf). `value` is the serialized data.
```

2024-07-15 15:23 UTC, hhunter-ms commented on daprdocs/content/en/reference/api/jobs_api.md
> +`schedule` | schedule is an optional schedule at which the job is to be run. Details of the format are below.
```suggestion
`schedule` | An optional schedule at which the job is to be run. Details of the format are below.
```

2024-07-15 15:23 UTC, hhunter-ms commented on daprdocs/content/en/reference/api/jobs_api.md
> +`dueTime` | dueTime is the optional time at which the job should be active, or the "one shot" time if other scheduling type fields are not provided. Accepts a "point in time" string in the format of
```suggestion
`dueTime` | An optional time at which the job should be active, or the "one shot" time, if other scheduling type fields are not provided. Accepts a "point in time" string in the format of RFC3339, Go duration string (calculated from creation time), or non-repeating ISO8601.
```

2024-07-15 15:23 UTC, hhunter-ms commented on daprdocs/content/en/reference/api/jobs_api.md
> +`repeats` | repeats is the optional number of times in which the job should be triggered. If not set, the job will run indefinitely or until expiration.
```suggestion
`repeats` | An optional number of times in which the job should be triggered. If not set, the job runs indefinitely or until expiration.
```

2024-07-15 15:23 UTC, hhunter-ms commented on daprdocs/content/en/reference/api/jobs_api.md
> +`ttl` | ttl is the optional time to live or expiration of the job. Accepts a "point in time" string in the format of RFC3339, Go duration string (calculated from job creation time), or non-repeating
```suggestion
`ttl` | An optional time to live or expiration of the job. Accepts a "point in time" string in the format of RFC3339, Go duration string (calculated from job creation time), or non-repeating ISO8601.
```

2024-07-15 15:23 UTC, hhunter-ms commented on daprdocs/content/en/reference/api/jobs_api.md
> +`schedule` accepts both systemd timer style cron expressions, as well as human readable '@' prefixed period strings as defined below.
```suggestion
`schedule` accepts both systemd timer-style cron expressions, as well as human readable '@' prefixed period strings, as defined below.
```

2024-07-15 15:23 UTC, hhunter-ms commented on daprdocs/content/en/reference/cli/dapr-init.md
> +|  `--scheduler-volume`  |              |          | Self-hosted only. Optionally specify a volume for the scheduler service data directory. By default, scheduler data is not persisted and not resili
```suggestion
|  `--scheduler-volume`  |              |          | Self-hosted only. Optionally, you can specify a volume for the scheduler service data directory. By default, without this flag, scheduler data is not persisted and not resilient to restarts. |
```

2024-07-17 13:27 UTC, cicoyle commented on daprdocs/content/en/reference/api/jobs_api.md
> +            "scheudle": "@every 1m",
```suggestion
            "schedule": "@every 1m",
```

2024-07-17 13:28 UTC, cicoyle approved these changes
one spelling nit, but otherwise looks great 🎉

2024-07-19 23:31 UTC, msfussell commented on daprdocs/content/en/operations/hosting/self-hosted/self-hosted-persisting-scheduler.md
> +The Scheduler persistent volume can be modified with a custom volume that is pre-existing, or will be created by Dapr.
```suggestion
The Scheduler persistent volume can be modified with a custom volume that is pre-existing, or is created by Dapr.
```

2024-07-19 23:33 UTC, msfussell commented on daprdocs/content/en/operations/hosting/self-hosted/self-hosted-persisting-scheduler.md
> +dapr init --scheduler-volume my-scheduler-volume
What is not clear is whether `--scheduler-volume my-scheduler-volume` is the default if all I do is `dapr init`. If not it should be IMO.

2024-07-19 23:56 UTC, msfussell reviewed
A few comments, mostly on the default for dapr init command

2024-07-19 23:56 UTC, msfussell commented on daprdocs/content/en/operations/hosting/self-hosted/self-hosted-persisting-scheduler.md
> +If Dapr is already installed, the control plane needs to be completely [uninstalled]({{< ref dapr-uninstall.md >}}) in order for the Scheduler container to be recreated with the new persistent volume
```suggestion
By default `dapr init` creates a local persistent volume on your drive. If Dapr is already installed, the control plane needs to be completely [uninstalled]({{< ref dapr-uninstall.md >}}) in order for the Scheduler container to be recreated with the new persistent volume.
```

2024-07-19 23:56 UTC, msfussell commented on daprdocs/content/en/reference/cli/dapr-init.md
> +> By default, a `dapr_scheduler` local volume will be created for Scheduler to be used as the data base directory. The host file location for this volume is likely located at `/var/lib/docker/volumes
```suggestion
> By default, a `dapr_scheduler` local volume is created for Scheduler service to be used as the database directory. The host file location for this volume is likely located at `/var/lib/docker/volumes/dapr_scheduler/_data` or `~/.local/share/containers/storage/volumes/dapr_scheduler/_data`, depending on your container runtime.
```

2024-07-19 23:56 UTC, msfussell commented on daprdocs/content/en/operations/hosting/self-hosted/self-hosted-persisting-scheduler.md
> +The host file location for this local volume will typically be located at either `/var/lib/docker/volumes/dapr_scheduler/_data` or `~/.local/share/containers/storage/volumes/dapr_scheduler/_data`, de
```suggestion
The host file location for this local volume is typically located at either `/var/lib/docker/volumes/dapr_scheduler/_data` or `~/.local/share/containers/storage/volumes/dapr_scheduler/_data`, depending on your container runtime.
```

2024-07-20 01:09 UTC, rochabr commented on daprdocs/content/en/reference/api/jobs_api.md
>  ```
new request body should be:

```
curl -X POST \
  http://localhost:6280/v1.0-alpha1/jobs/jobforjabba \
  -H "Content-Type: application/json" \
  -d '{
        "data": {
            "@type": "type.googleapis.com/google.protobuf.StringValue",
            "value": "Running spice"
        },
        "schedule": "@every 1m",
        "repeats": 5
    }'
```

2024-07-24 16:33 UTC, msfussell approved these changes
LGTM.

2024-07-24 18:16 UTC, hhunter-ms approved these changes

2024-07-24 18:17 UTC, msfussell commented
DO not merge this yet. @JoshVanL will add one more update.

2024-07-24 18:25 UTC, JoshVanL commented
@msfussell updated- please take a look!

2024-07-26 20:54 UTC, msfussell commented on daprdocs/content/en/operations/hosting/self-hosted/self-hosted-persisting-scheduler.md
> +Note that if using Docker Desktop, this volume will be located in the Docker Desktop VM's filesystem, which can be accessed using:
```suggestion
Note that if you are using Docker Desktop, this volume is located in the Docker Desktop VM's filesystem, which can be accessed using:
```

2024-07-26 21:14 UTC, merged