Update install-dapr-cli.md
dapr/docs pull request #4273
Opened 2024-07-23 08:58 UTC by gralin

Add a note that Docker Desktop's advanced options section is not visible when WSL integration is enabled.

Thank you for helping make the Dapr documentation better!

**Please follow this checklist before submitting:**
- [x] Commits are signed with Developer Certificate of Origin (DCO - [learn more](https://docs.dapr.io/contributing/contributing-overview/#developer-certificate-of-origin-signing-your-work))
- [x] [Read the contribution guide](https://docs.dapr.io/contributing/docs-contrib/contributing-docs/)
- [ ] Commands include options for Linux, MacOS, and Windows within codetabs
- [ ] New file and folder names are globally unique
- [ ] Page references use shortcodes instead of markdown or URL links
- [ ] Images use HTML style and have alternative text
- [ ] Places where multiple code/command options are given have codetabs

In addition, please fill out the following to help reviewers understand this pull request:

## Description

Add a note that Docker Desktop's advanced options section is not visible when WSL integration is enabled.

## Issue reference

2024-07-23 12:57 UTC, hhunter-ms commented on daprdocs/content/en/getting-started/install-dapr-cli.md
> +In Docker Desktop's advanced options, verify you've allowed the default Docker socket to be used. This option is not available if your are using WSL integration on Windows.
```suggestion
In Docker Desktop's advanced options, verify you've allowed the default Docker socket to be used. This option is not available if you are using WSL integration on Windows.
```

2024-07-23 12:58 UTC, hhunter-ms requested changes
quick typo fix, otherwise lgtm - thank you!

2024-07-23 13:22 UTC, hhunter-ms approved these changes

2024-07-23 14:24 UTC, merged

2024-08-15 12:25 UTC, marcduiker commented
@holopin-bot @gralin Thank you!