Add subscribe.v1alpha1 to the API allow list docs
dapr/docs pull request #4297
Opened 2024-08-05 17:32 UTC by jjcollinge

- **update config.toml**
- **workflow**
- **Fix link**
- **docs: add some of the kafka enhancement new metadata fields (#4099)**
- **docs: showcase aws iam authentication for pg components (#4100)**
- **remove breaking file**
- **start building block skeleton**
- **add more areas for docs**
- **alpha api doc and create reference api**
- **update content in overview**
- **update to just scheduler; add to preview features**
- **fix links**
- **IaC for Static Web App for Docs site**
- **Adding readme to IaC folder**
- **Updating Readme for IaC with PowerShell tab**
- **Fixes check for "pinning localized MSFT doc" by removing en-us from URL**
- **Adding recommendation to export AZURE_STATICWEBSITE_NAME every time.  leaving empty creates a default with a unique hash (but ugly for prod)**
- **Enable manual trigger**
- **HotReload: Subscription feature preview (#4116)**
- **add rust submodule**
- **add diagram to overview**
- **add high priority class name recommendation for production**
- **add resourcequota info for older dapr**
- **fix doc**
- **minor refactor, try to avoid collission with chart resource name**
- **add mount for rust**
- **docs: migrate rust github link to docs**
- **Update daprdocs/content/en/operations/hosting/kubernetes/kubernetes-production.md**
- **Update daprdocs/content/en/operations/hosting/kubernetes/kubernetes-production.md**
- **Update daprdocs/content/en/operations/hosting/kubernetes/kubernetes-production.md**
- **Update daprdocs/content/en/operations/hosting/kubernetes/kubernetes-production.md**
- **Update daprdocs/content/en/operations/hosting/kubernetes/kubernetes-production.md**
- **Update daprdocs/content/en/operations/hosting/kubernetes/kubernetes-production.md**
- **Update daprdocs/content/en/operations/hosting/kubernetes/kubernetes-production.md**
- **Update daprdocs/content/en/operations/hosting/kubernetes/kubernetes-production.md**
- **Update daprdocs/content/en/operations/hosting/kubernetes/kubernetes-production.md**
- **Update daprdocs/content/en/operations/hosting/kubernetes/kubernetes-production.md**
- **Update daprdocs/content/en/operations/hosting/kubernetes/kubernetes-production.md**
- **small updates**
- **add cli doc**
- **add template for scheduler service doc**
- **add table row for schedule**
- **docs: add endpoint field to aws sns (#4189)**
- **update kubernetes architecture image with scheduler service**
- **update vms architecture image with scheduler service**
- **add scheduler to standalone overview diagram**
- **update image for overview**
- **namespaced actors - start documentation**
- **elena review**
- **forgot to save**
- **update json example in api doc**
- **remove dapr-jobs cli doc**
- **remove examples section**
- **add to api doc**
- **update the scheduler service doc**
- **update OTEL version**
- **updates per Mark**
- **fix link**
- **add to dapr run and args doc**
- **remove apiLevel for now**
- **remove images**
- **update images with scheduler icon**
- **Update daprdocs/content/en/concepts/overview.md**
- **Update daprdocs/content/en/reference/api/scheduler_api.md**
- **updates per cassie**
- **Update daprdocs/content/en/reference/api/scheduler_api.md**
- **Update daprdocs/content/en/reference/api/scheduler_api.md**
- **Update daprdocs/content/en/reference/api/scheduler_api.md**
- **updates per cassie pt2**
- **Update daprdocs/content/en/developing-applications/building-blocks/actors/namespaced-actors.md**
- **Update daprdocs/content/en/developing-applications/building-blocks/actors/namespaced-actors.md**
- **updates from Mark**
- **Update daprdocs/content/en/operations/hosting/kubernetes/kubernetes-production.md**
- **Update daprdocs/content/en/operations/hosting/kubernetes/kubernetes-production.md**
- **Update daprdocs/content/en/operations/hosting/kubernetes/kubernetes-production.md**
- **Update Reporting security issues**
- **elena update**
- **add isolation concept and move service meshes**
- **add faq**
- **rearrange toc order and update titles**
- **update API doc with response content**
- **Update daprdocs/content/en/concepts/isolation-concept.md**
- **updates per Mark**
- **update pubsub link**
- **add namespaced actors link**
- **Update daprdocs/content/en/operations/hosting/kubernetes/kubernetes-production.md**
- **Update daprdocs/content/en/operations/hosting/kubernetes/kubernetes-production.md**
- **updates per mark; change name**
- **fix link errors**
- **api reference**
- **Adds initial streaming subscriptions docs**
- **update jobs api in diagrams**
- **Apply suggestions from code review**
- **Update daprdocs/content/en/operations/support/support-security-issues.md**
- **Update daprdocs/content/en/operations/support/support-security-issues.md**
- **Update daprdocs/content/en/operations/support/support-security-issues.md**
- **Update daprdocs/content/en/operations/support/support-security-issues.md**
- **Update daprdocs/content/en/operations/support/support-security-issues.md**
- **Update daprdocs/content/en/operations/support/support-security-issues.md**
- **Update daprdocs/content/en/operations/support/support-security-issues.md**
- **Update daprdocs/content/en/operations/support/support-security-issues.md**
- **Update daprdocs/content/en/operations/support/support-security-issues.md**
- **Update daprdocs/content/en/operations/support/support-security-issues.md**
- **Update daprdocs/content/en/operations/support/support-security-issues.md**
- **Update daprdocs/content/en/operations/support/support-security-issues.md**
- **Update daprdocs/content/en/operations/support/support-security-issues.md**
- **Update daprdocs/content/en/operations/support/support-security-issues.md**
- **Update daprdocs/content/en/operations/support/support-security-issues.md**
- **Update daprdocs/content/en/operations/support/support-security-issues.md**
- **Update GCP PubSub Docs for MaxOutstanding* & MaxConcurrentConnections settings (#4233)**
- **Apply suggestions from code review**
- **Adds notes about streaming subscription not supported by bulk or routes**
- **Update daprdocs/content/en/developing-applications/building-blocks/pubsub/pubsub-overview.md**
- **Apply suggestions from code review**
- **Adds Subscription type to Subscription metadata output**
- **Update daprdocs/content/en/concepts/building-blocks-concept.md**
- **Update daprdocs/content/en/concepts/dapr-services/scheduler.md**
- **Update daprdocs/content/en/concepts/dapr-services/scheduler.md**
- **Update daprdocs/content/en/concepts/dapr-services/scheduler.md**
- **Update daprdocs/content/en/concepts/overview.md**
- **Update daprdocs/content/en/developing-applications/building-blocks/jobs/howto-schedule-jobs.md**
- **Update daprdocs/content/en/developing-applications/building-blocks/jobs/jobs-overview.md**
- **Update daprdocs/content/en/developing-applications/building-blocks/jobs/jobs-overview.md**
- **Update daprdocs/content/en/developing-applications/building-blocks/jobs/jobs-overview.md**
- **Update daprdocs/content/en/operations/support/support-preview-features.md**
- **Update daprdocs/content/en/reference/api/jobs_api.md**
- **Update daprdocs/content/en/reference/api/jobs_api.md**
- **Update daprdocs/content/en/reference/api/jobs_api.md**
- **Update daprdocs/content/en/reference/api/jobs_api.md**
- **Update daprdocs/content/en/reference/api/jobs_api.md**
- **Update daprdocs/content/en/reference/api/jobs_api.md**
- **Update daprdocs/content/en/reference/api/jobs_api.md**
- **Update daprdocs/content/en/reference/api/jobs_api.md**
- **Update daprdocs/content/en/reference/api/jobs_api.md**
- **Update daprdocs/content/en/reference/api/jobs_api.md**
- **mark review**
- **remove app id from job api doc**
- **Add Kafka heartbeat interval and session timeout to component reference (#4074)**
- **Update daprdocs/content/en/reference/api/metadata_api.md**
- **Update daprdocs/content/en/developing-applications/building-blocks/jobs/jobs-overview.md**
- **Update daprdocs/content/en/developing-applications/building-blocks/jobs/jobs-o [...]

2024-08-05 17:38 UTC, yaron2 approved these changes

2024-08-07 14:43 UTC, hhunter-ms requested changes
@jjcollinge on line 117, could you try changing the link from:

> https://github.com/dapr/dapr/blob/master/pkg/grpc/endpoints.go 

to:

> https://github.com/dapr/dapr/tree/master/pkg/api/grpc

That might be holding up the PR build job.

2024-08-07 18:56 UTC, msfussell approved these changes
LGTM

2024-08-07 19:00 UTC, hhunter-ms approved these changes

2024-08-07 19:00 UTC, merged

2024-08-15 12:30 UTC, marcduiker commented
@holopin-bot @jjcollinge Thanks Joni! 😁