Prometheus auto service discovery
dapr/docs pull request #4321
Opened 2024-08-17 10:12 UTC by maulindesai

Thank you for helping make the Dapr documentation better!

**Please follow this checklist before submitting:**
- [X] Commits are signed with Developer Certificate of Origin (DCO - [learn more](https://docs.dapr.io/contributing/contributing-overview/#developer-certificate-of-origin-signing-your-work))
- [X] [Read the contribution guide](https://docs.dapr.io/contributing/docs-contrib/contributing-docs/)
- [X] Commands include options for Linux, MacOS, and Windows within codetabs
- [X] New file and folder names are globally unique
- [X] Page references use shortcodes instead of markdown or URL links
- [X] Images use HTML style and have alternative text
- [X] Places where multiple code/command options are given have codetabs

In addition, please fill out the following to help reviewers understand this pull request:

## Description

- Updated prometheus.md with instructions for setting up Prometheus auto service discovery for Dapr and sidecar targets.

## Issue reference
#4234

2024-08-19 18:43 UTC, hhunter-ms requested changes
quick formatting fix to keep consistent w other docs. otherwise lgtm!

2024-08-19 18:43 UTC, hhunter-ms commented on daprdocs/content/en/operations/observability/metrics/prometheus.md
> +Open a browser and visit `http://localhost:9090`. Navigate to `Status -> Service Discovery` to verify that the Dapr targets are discovered correctly.
```suggestion
Open a browser and visit `http://localhost:9090`. Navigate to **Status** > **Service Discovery** to verify that the Dapr targets are discovered correctly.
```

2024-08-20 12:17 UTC, hhunter-ms approved these changes

2024-08-23 16:54 UTC, msfussell approved these changes
LGTM

2024-08-23 17:29 UTC, merged

2024-10-04 10:22 UTC, marcduiker commented
@holopin-bot @maulindesai Thank you for your contribution!