Add Kafka escapeHeaders documentation
dapr/docs pull request #4332
Opened 2024-08-31 01:12 UTC by antontroshin

Thank you for helping make the Dapr documentation better!

**Please follow this checklist before submitting:**
- [ ] Commits are signed with Developer Certificate of Origin (DCO - [learn more](https://docs.dapr.io/contributing/contributing-overview/#developer-certificate-of-origin-signing-your-work))
- [ ] [Read the contribution guide](https://docs.dapr.io/contributing/docs-contrib/contributing-docs/)
- [ ] Commands include options for Linux, MacOS, and Windows within codetabs
- [ ] New file and folder names are globally unique
- [ ] Page references use shortcodes instead of markdown or URL links
- [ ] Images use HTML style and have alternative text
- [ ] Places where multiple code/command options are given have codetabs

In addition, please fill out the following to help reviewers understand this pull request:

## Description

Add documentation for a new field for Kafka bindings and Pub/Sub

## Issue reference

https://github.com/dapr/components-contrib/issues/3503

2024-09-04 16:04 UTC, hhunter-ms requested changes, later dismissed
quick review

2024-09-04 16:04 UTC, hhunter-ms commented on daprdocs/content/en/reference/components-reference/supported-bindings/kafka.md
> +| `escapeHeaders` | N | Input | Enables URL escaping of the message header values received by the consumer. It allows receiving content with special characters that are usually not allowed in HTTP he
```suggestion
| `escapeHeaders` | N | Input | Enables URL escaping of the message header values received by the consumer. Allows receiving content with special characters that are usually not allowed in HTTP headers. Default is `false`. | `true` |
```

2024-09-04 16:04 UTC, hhunter-ms commented on daprdocs/content/en/reference/components-reference/supported-pubsub/setup-apache-kafka.md
> +| escapeHeaders | N | Enables URL escaping of the message header values received by the consumer. It allows receiving content with special characters that are usually not allowed in HTTP headers. Def
```suggestion
| escapeHeaders | N | Enables URL escaping of the message header values received by the consumer. Allows receiving content with special characters that are usually not allowed in HTTP headers. Default is `false`. | `true` |
```

2024-09-04 16:04 UTC, hhunter-ms commented on daprdocs/content/en/reference/components-reference/supported-pubsub/setup-apache-kafka.md
> +HTTP header values must follow specifications and some characters are not allowed, see [here](https://www.w3.org/Protocols/rfc2616/rfc2616-sec4.html#sec4.2).
```suggestion
HTTP header values must follow specifications, making some characters not allowed. [Learn more about the protocols](https://www.w3.org/Protocols/rfc2616/rfc2616-sec4.html#sec4.2).
```

2024-09-04 16:04 UTC, hhunter-ms commented on daprdocs/content/en/reference/components-reference/supported-pubsub/setup-apache-kafka.md
> +In this case, you can enable `escapeHeaders` configuration setting which will use URL escaping to encode header values on the consumer side.
```suggestion
In this case, you can enable `escapeHeaders` configuration setting, which uses URL escaping to encode header values on the consumer side.
```

2024-09-04 16:04 UTC, hhunter-ms commented on daprdocs/content/en/reference/components-reference/supported-pubsub/setup-apache-kafka.md
> +**Note**: When using this setting, the received message headers will be URL escaped, and you will need to URL unescape it to get the original value.
```suggestion
{{% alert title="Note" color="primary" %}}
When using this setting, the received message headers are URL escaped, and you need to URL "un-escape" it to get the original value.
{{% /alert %}}
```

2024-09-04 16:04 UTC, hhunter-ms commented on daprdocs/content/en/reference/components-reference/supported-pubsub/setup-apache-kafka.md
> +Setting `escapeHeaders` to `true`
```suggestion
Set `escapeHeaders` to `true` to URL escape. 

```

2024-09-06 18:16 UTC, yaron2 approved these changes

2024-09-06 18:26 UTC, merged