Add HTTP and gRPC error codes retries to the resiliency policies documentation
dapr/docs pull request #4363
Opened 2024-09-19 22:56 UTC by antontroshin

Thank you for helping make the Dapr documentation better!

**Please follow this checklist before submitting:**
- [ ] Commits are signed with Developer Certificate of Origin (DCO - [learn more](https://docs.dapr.io/contributing/contributing-overview/#developer-certificate-of-origin-signing-your-work))
- [ ] [Read the contribution guide](https://docs.dapr.io/contributing/docs-contrib/contributing-docs/)
- [ ] Commands include options for Linux, MacOS, and Windows within codetabs
- [ ] New file and folder names are globally unique
- [ ] Page references use shortcodes instead of markdown or URL links
- [ ] Images use HTML style and have alternative text
- [ ] Places where multiple code/command options are given have codetabs

In addition, please fill out the following to help reviewers understand this pull request:

## Description

## Issue reference

2024-10-03 12:39 UTC, msfussell commented on daprdocs/content/en/operations/resiliency/policies.md
> +| `matching.httpStatusCodes` | Optional: a comma-separated string of HTTP status codes or code ranges to retry. Status codes not listed are not retried.<br/>Valid values: 100-599, [Reference](https:/
```suggestion
| `matching.httpStatusCodes` | Optional: a comma-separated string of HTTP status codes or code ranges to retry. Status codes not listed are not retried.<br/>Valid values: 100-599, [Reference](https://developer.mozilla.org/en-US/docs/Web/HTTP/Status)<br/>Format: `<code>` or range `<start>-<end>`<br/>Example: "429,501-503"<br/>Default, the empty string `""` or field not set, retries on all HTTP errors. |
```

2024-10-03 12:39 UTC, msfussell commented on daprdocs/content/en/operations/resiliency/policies.md
> +| `matching.gRPCStatusCodes` | Optional: a comma-separated string of gRPC status codes or code ranges to retry. Status codes not listed are not retried.<br/>Valid values: 0-16, [Reference](https://gr
```suggestion
| `matching.gRPCStatusCodes` | Optional: a comma-separated string of gRPC status codes or code ranges to retry. Status codes not listed are not retried.<br/>Valid values: 0-16, [Reference](https://grpc.io/docs/guides/status-codes/)<br/>Format: `<code>` or range `<start>-<end>`<br/>Example: "1,501-503"<br/>Default, the empty string `""` or field not set, retries on all gRPC errors. |
```

2024-10-03 12:42 UTC, msfussell commented on daprdocs/content/en/operations/resiliency/policies.md
> +          httpStatusCodes: "429,500-599" # retry HTTP status codes in range, the rest will not be retried
```suggestion
          httpStatusCodes: "429,500-599" # retry the HTTP status codes in this range. All others are not retried. 
```

2024-10-03 12:43 UTC, hhunter-ms requested changes
quick review - thanks for your contribution!

2024-10-03 12:43 UTC, hhunter-ms commented on daprdocs/content/en/operations/resiliency/policies.md
> +| `matching.httpStatusCodes` | Optional: a comma-separated string of HTTP status codes or code ranges to retry. Status codes not listed are not retried.<br/>Valid values: 100-599, [Reference](https:/
```suggestion
| `matching.httpStatusCodes` | Optional: a comma-separated string of HTTP status codes or code ranges to retry. Status codes not listed are not retried.<br/>Valid values: 100-599, [Reference](https://developer.mozilla.org/en-US/docs/Web/HTTP/Status)<br/>Format: `<code>` or range `<start>-<end>`<br/>Example: "429,501-503"<br/>Default: empty string `""` or field is not set. Retries on all HTTP errors. |
```

2024-10-03 12:43 UTC, hhunter-ms commented on daprdocs/content/en/operations/resiliency/policies.md
> +| `matching.gRPCStatusCodes` | Optional: a comma-separated string of gRPC status codes or code ranges to retry. Status codes not listed are not retried.<br/>Valid values: 0-16, [Reference](https://gr
```suggestion
| `matching.gRPCStatusCodes` | Optional: a comma-separated string of gRPC status codes or code ranges to retry. Status codes not listed are not retried.<br/>Valid values: 0-16, [Reference](https://grpc.io/docs/guides/status-codes/)<br/>Format: `<code>` or range `<start>-<end>`<br/>Example: "1,501-503"<br/>Default: empty string `""` or field is not set. Retries on all gRPC errors. |
```

2024-10-03 12:43 UTC, hhunter-ms commented on daprdocs/content/en/operations/resiliency/policies.md
> +Incorrectly formatted field value will cause the failure to load the policy and intentional failure to start `daprd`.
```suggestion
Incorrectly formatted field values cause the failure to load the policy and intentional failure to start `daprd`.
```

2024-10-03 12:43 UTC, msfussell commented on daprdocs/content/en/operations/resiliency/policies.md
> +          gRPCStatusCodes: "1-4,8-11,13,14" # retry specific gRPC status codes, in ranges and separate single code.
```suggestion
          gRPCStatusCodes: "1-4,8-11,13,14" # retry gRPC status codes in these ranges and separate single codes.
```

2024-10-03 12:43 UTC, msfussell reviewed
@hhunter-ms - PTAL.

2024-10-03 12:44 UTC, hhunter-ms commented on daprdocs/content/en/operations/resiliency/policies.md
> +Incorrectly formatted field value will cause the failure to load the policy and intentional failure to start `daprd`.
just saw @msfussell review - use his edit for this instead of mine!

2024-10-03 12:47 UTC, msfussell commented on daprdocs/content/en/operations/resiliency/policies.md
> +Incorrectly formatted field values cause the failure to load the policy and intentional failure to start `daprd`.
```suggestion
An incorrectly formatted value fails to load the policy and fails to start `daprd`.
```

2024-10-03 12:47 UTC, msfussell approved these changes
LGTM

2024-12-02 17:28 UTC, hhunter-ms approved these changes

2024-12-02 17:38 UTC, merged