docs: update fields as they are optional
dapr/docs pull request #4371
Opened 2024-10-07 16:52 UTC by sicoyle

Thank you for helping make the Dapr documentation better!

**Please follow this checklist before submitting:**
- [ ] Commits are signed with Developer Certificate of Origin (DCO - [learn more](https://docs.dapr.io/contributing/contributing-overview/#developer-certificate-of-origin-signing-your-work))
- [ ] [Read the contribution guide](https://docs.dapr.io/contributing/docs-contrib/contributing-docs/)
- [ ] Commands include options for Linux, MacOS, and Windows within codetabs
- [ ] New file and folder names are globally unique
- [ ] Page references use shortcodes instead of markdown or URL links
- [ ] Images use HTML style and have alternative text
- [ ] Places where multiple code/command options are given have codetabs

In addition, please fill out the following to help reviewers understand this pull request:

## Description

Docs updates given these changes
https://github.com/dapr/components-contrib/pull/3562/files

## Issue reference

2024-10-08 10:28 UTC, JoshVanL requested changes

2024-10-08 10:28 UTC, JoshVanL commented on daprdocs/content/en/reference/components-reference/supported-bindings/postgresql.md
> +| `awsAccessKey` | N | AWS access key associated with an IAM account | `"AKIAIOSFODNN7EXAMPLE"` |
Please target the v1.15 branch

2024-10-23 20:23 UTC, hhunter-ms commented
@sicoyle does this PR need to point to 1.15?

2024-10-31 19:11 UTC, msfussell commented
@sicoyle - You will need to create a new PR for this

2024-12-03 21:17 UTC, sicoyle commented
closing as i am fixing in a diff pr

2024-12-03 21:17 UTC, closed without merging