Update workflow-quickstart.md regarding using Redis in production
dapr/docs pull request #4404
Opened 2024-10-28 10:54 UTC by sclarke81

Thank you for helping make the Dapr documentation better!

**Please follow this checklist before submitting:**
- [x ] Commits are signed with Developer Certificate of Origin (DCO - [learn more](https://docs.dapr.io/contributing/contributing-overview/#developer-certificate-of-origin-signing-your-work))
- [x ] [Read the contribution guide](https://docs.dapr.io/contributing/docs-contrib/contributing-docs/)
- [ ] Commands include options for Linux, MacOS, and Windows within codetabs
- [ ] New file and folder names are globally unique
- [ ] Page references use shortcodes instead of markdown or URL links
- [ ] Images use HTML style and have alternative text
- [ ] Places where multiple code/command options are given have codetabs

In addition, please fill out the following to help reviewers understand this pull request:

## Description

Redis is used in the Workflows Quickstarts, but Redis isn't recommended for use in production (for Workflows). Added a note to the Quickstarts page to highlight this.

2024-10-28 17:50 UTC, hhunter-ms commented on daprdocs/content/en/getting-started/quickstarts/workflow-quickstart.md
> +Redis is currently used as the state store component for Workflows in out Quickstarts. However, Redis does not support transaction rollbacks and should not be used in production as an actor state sto
```suggestion
Redis is currently used as the state store component for Workflows in the Quickstarts. However, Redis does not support transaction rollbacks and should not be used in production as an actor state store.
```

2024-10-28 17:51 UTC, hhunter-ms requested changes
quick typo fix - thank you!

2024-10-29 09:35 UTC, sclarke81 commented
> quick typo fix - thank you!

Good spot, thank you!

2024-10-31 14:26 UTC, hhunter-ms approved these changes

2024-10-31 18:54 UTC, msfussell approved these changes
LGTM

2024-10-31 18:59 UTC, merged

2024-12-03 08:28 UTC, marcduiker commented
@holopin-bot @sclarke81 Thank you Stephen!