Sftp Binding Component Docs
dapr/docs pull request #4418
Opened 2024-11-02 13:56 UTC by arslanmusta

Thank you for helping make the Dapr documentation better!

**Please follow this checklist before submitting:**
- [ ] Commits are signed with Developer Certificate of Origin (DCO - [learn more](https://docs.dapr.io/contributing/contributing-overview/#developer-certificate-of-origin-signing-your-work))
- [ ] [Read the contribution guide](https://docs.dapr.io/contributing/docs-contrib/contributing-docs/)
- [ ] Commands include options for Linux, MacOS, and Windows within codetabs
- [ ] New file and folder names are globally unique
- [ ] Page references use shortcodes instead of markdown or URL links
- [ ] Images use HTML style and have alternative text
- [ ] Places where multiple code/command options are given have codetabs

In addition, please fill out the following to help reviewers understand this pull request:

## Description

Adding Sftp Binding component documentation.

## Issue reference

Related PR: dapr/components-contrib#3505

2024-11-04 15:21 UTC, hhunter-ms approved these changes

2024-11-04 16:17 UTC, msfussell reviewed
@arslanmusta Looks great. Thanks for creating this. Generally keeping acronym to caps at the start of the doc with a full name description of the binding (similar to SMTP binding)

2024-11-04 16:17 UTC, msfussell commented on daprdocs/content/en/reference/components-reference/supported-bindings/sftp.md
> +title: "Sftp binding spec"
```suggestion
title: "SFTP binding spec"
```

2024-11-04 16:17 UTC, msfussell commented on daprdocs/content/en/reference/components-reference/supported-bindings/sftp.md
> +description: "Detailed documentation on the Sftp binding component"
```suggestion
description: "Detailed documentation on the Secure File Transfer Protocol (SFTP) binding component"
```

2024-11-04 16:17 UTC, msfussell commented on daprdocs/content/en/reference/components-reference/supported-bindings/sftp.md
> +The response body will contain the following JSON:
```suggestion
The response body contains the following JSON:
```

2024-11-04 16:17 UTC, msfussell commented on daprdocs/content/en/reference/components-reference/supported-bindings/sftp.md
> +An HTTP 204 (No Content) and empty body will be returned if successful.
```suggestion
An HTTP 204 (No Content) and empty body is returned if successful.
```

2024-11-04 16:17 UTC, msfussell commented on daprdocs/data/components/bindings/generic.yaml
> +- component: Sftp
```suggestion
- component: SFTP
```

2024-11-04 16:17 UTC, msfussell commented on daprdocs/content/en/reference/components-reference/supported-bindings/sftp.md
> +To set up the Sftp binding, create a component of type `bindings.sftp`. See this guide on how to create and apply a binding configuration.
```suggestion
To set up the SMTP binding, create a component of type `bindings.sftp`. See this guide on how to create and apply a binding configuration.
```

2024-11-14 17:12 UTC, hhunter-ms requested changes
quick consistency check

2024-11-14 17:12 UTC, hhunter-ms commented on daprdocs/content/en/reference/components-reference/supported-bindings/sftp.md
> +linkTitle: "Sftp"
```suggestion
linkTitle: "SFTP"
```

for consistency

2024-11-14 17:12 UTC, hhunter-ms commented on daprdocs/content/en/reference/components-reference/supported-bindings/sftp.md
> +To set up the SMTP binding, create a component of type `bindings.sftp`. See this guide on how to create and apply a binding configuration.
```suggestion
To set up the SFTP binding, create a component of type `bindings.sftp`. See [this guide]({{ ref bindings-overview.md }}) on how to create and apply a binding configuration.
```

2024-11-14 17:12 UTC, hhunter-ms commented on daprdocs/content/en/reference/components-reference/supported-bindings/sftp.md
> +| `address`             | Y        | Output |  Address of Sftp server | `"localhost:22"` |
```suggestion
| `address`             | Y        | Output |  Address of SFTP server | `"localhost:22"` |
```

2024-11-14 17:12 UTC, hhunter-ms commented on daprdocs/content/en/reference/components-reference/supported-bindings/sftp.md
> +To perform a create file operation, invoke the Sftp binding with a `POST` method and the following JSON body:
```suggestion
To perform a create file operation, invoke the SFTP binding with a `POST` method and the following JSON body:
```

2024-11-14 17:12 UTC, hhunter-ms commented on daprdocs/content/en/reference/components-reference/supported-bindings/sftp.md
> +To perform a get file operation, invoke the Sftp binding with a `POST` method and the following JSON body:
```suggestion
To perform a get file operation, invoke the SFTP binding with a `POST` method and the following JSON body:
```

2024-11-14 17:12 UTC, hhunter-ms commented on daprdocs/content/en/reference/components-reference/supported-bindings/sftp.md
> +To perform a list files operation, invoke the Sftp binding with a `POST` method and the following JSON body:
```suggestion
To perform a list files operation, invoke the SFTP binding with a `POST` method and the following JSON body:
```

2024-11-14 17:12 UTC, hhunter-ms commented on daprdocs/content/en/reference/components-reference/supported-bindings/sftp.md
> +To perform a delete file operation, invoke the Sftp binding with a `POST` method and the following JSON body:
```suggestion
To perform a delete file operation, invoke the SFTP binding with a `POST` method and the following JSON body:
```

2024-11-20 18:25 UTC, hhunter-ms approved these changes
lgtm, thanks!

2024-11-25 20:31 UTC, msfussell approved these changes
LGTM

2024-11-25 20:32 UTC, merged

2024-12-03 08:27 UTC, marcduiker commented
@holopin-bot @arslanmusta Thank you!