Postgres aws auth
dapr/docs pull request #4429
Opened 2024-11-14 12:40 UTC by famarting

Docs update for this components contrib PR https://github.com/dapr/components-contrib/pull/3597

**Please follow this checklist before submitting:**
- [ ] Commits are signed with Developer Certificate of Origin (DCO - [learn more](https://docs.dapr.io/contributing/contributing-overview/#developer-certificate-of-origin-signing-your-work))
- [ ] [Read the contribution guide](https://docs.dapr.io/contributing/docs-contrib/contributing-docs/)
- [ ] Commands include options for Linux, MacOS, and Windows within codetabs
- [ ] New file and folder names are globally unique
- [ ] Page references use shortcodes instead of markdown or URL links
- [ ] Images use HTML style and have alternative text
- [ ] Places where multiple code/command options are given have codetabs

In addition, please fill out the following to help reviewers understand this pull request:

## Description

## Issue reference

2024-11-14 12:42 UTC, famarting commented
I think the DCO has failed not because of my commit but by some other commit already in the v1.15 branch

2024-11-14 13:14 UTC, JoshVanL requested changes

2024-11-14 13:14 UTC, JoshVanL commented on daprdocs/content/en/reference/components-reference/supported-bindings/postgresql.md
> +| `awsIamRoleArn` | N  | IAM role that has access to AWS Relational Database Service. This is another option to authenticate with AWS aside from the AWS Credentials. | `"arn:aws:iam::123456789:role/r
```suggestion
| `awsIamRoleArn` | N  | IAM role that has access to AWS Relational Database Service. This is another option to authenticate with AWS aside from the AWS Credentials. | `"arn:aws:iam::123456789:role/rdsRole"` |
```
```suggestion
| `awsIamRoleArn` | N  | IAM role to assume that has access to AWS Relational Database Service. This is another option to authenticate with AWS aside from the AWS Credentials. | `"arn:aws:iam::123456789:role/rdsRole"` |
```

2024-11-14 13:14 UTC, JoshVanL commented on daprdocs/content/en/reference/components-reference/supported-configuration-stores/postgresql-configuration-store.md
> +| `awsIamRoleArn` | N  | IAM role that has access to AWS Relational Database Service. This is another option to authenticate with AWS aside from the AWS Credentials. | `"arn:aws:iam::123456789:role/r
```suggestion
| `awsIamRoleArn` | N  | IAM role to assume that has access to AWS Relational Database Service. This is another option to authenticate with AWS aside from the AWS Credentials. | `"arn:aws:iam::123456789:role/rdsRole"` |
```

2024-11-14 13:14 UTC, JoshVanL commented on daprdocs/content/en/reference/components-reference/supported-state-stores/setup-postgresql-v1.md
> +| `awsIamRoleArn` | N  | IAM role that has access to AWS Relational Database Service. This is another option to authenticate with AWS aside from the AWS Credentials. | `"arn:aws:iam::123456789:role/r
```suggestion
| `awsIamRoleArn` | N  | IAM role to assume that has access to AWS Relational Database Service. This is another option to authenticate with AWS aside from the AWS Credentials. | `"arn:aws:iam::123456789:role/rdsRole"` |
```

2024-11-14 13:14 UTC, JoshVanL commented on daprdocs/content/en/reference/components-reference/supported-state-stores/setup-postgresql-v2.md
> +| `awsIamRoleArn` | N  | IAM role that has access to AWS Relational Database Service. This is another option to authenticate with AWS aside from the AWS Credentials. | `"arn:aws:iam::123456789:role/r
```suggestion
| `awsIamRoleArn` | N  | IAM role to assume that has access to AWS Relational Database Service. This is another option to authenticate with AWS aside from the AWS Credentials. | `"arn:aws:iam::123456789:role/rdsRole"` |
```

2024-11-18 16:33 UTC, hhunter-ms approved these changes

2024-11-19 14:01 UTC, closed without merging