Update setup-aws-snssqs.md
dapr/docs pull request #4437
Opened 2024-11-26 11:00 UTC by qustavo

Add `concurrencyLimit` parameter description.

2024-11-26 11:01 UTC, qustavo commented
As per https://github.com/dapr/components-contrib/pull/3478#issuecomment-2499581233 request.

2024-12-02 10:36 UTC, qustavo commented
cc: @yaron2

2024-12-02 17:16 UTC, hhunter-ms requested changes
quick review

2024-12-02 17:16 UTC, hhunter-ms commented on daprdocs/content/en/reference/components-reference/supported-pubsub/setup-aws-snssqs.md
> +| concurrencyLimit | N | Defines the maximum number of concurrent workers handling messages. This value is ignored when concurrentMode is set to `"single"`. To avoid limiting the number of concurrent
```suggestion
| concurrencyLimit | N | Defines the maximum number of concurrent workers handling messages. This value is ignored when concurrencyMode is set to `"single"`. To avoid limiting the number of concurrent workers, set this to `0`. Default: `0` | `100`
```

2024-12-04 14:56 UTC, hhunter-ms approved these changes

2024-12-10 03:10 UTC, msfussell approved these changes
LGTM

2024-12-12 22:38 UTC, merged

2025-01-10 15:56 UTC, marcduiker commented
@holopin-bot @qustavo Thanks Gustavo!