Update docs for scheduler ephemeral storage
dapr/docs pull request #4438
Opened 2024-11-26 17:18 UTC by elena-kolevska

Thank you for helping make the Dapr documentation better!

**Please follow this checklist before submitting:**
- [ ] Commits are signed with Developer Certificate of Origin (DCO - [learn more](https://docs.dapr.io/contributing/contributing-overview/#developer-certificate-of-origin-signing-your-work))
- [ ] [Read the contribution guide](https://docs.dapr.io/contributing/docs-contrib/contributing-docs/)
- [ ] Commands include options for Linux, MacOS, and Windows within codetabs
- [ ] New file and folder names are globally unique
- [ ] Page references use shortcodes instead of markdown or URL links
- [ ] Images use HTML style and have alternative text
- [ ] Places where multiple code/command options are given have codetabs

In addition, please fill out the following to help reviewers understand this pull request:

## Description

## Issue reference

2024-12-02 17:18 UTC, hhunter-ms requested changes
tiny review

2024-12-02 17:18 UTC, hhunter-ms commented on daprdocs/content/en/operations/hosting/kubernetes/kubernetes-persisting-scheduler.md
> +When running in non-HA mode, Scheduler can be optionally made to use Ephemeral storage, which is in-memory storage that is **not** resilient to restarts, i.e. all Job data will be lost after a Schedu
```suggestion
When running in non-HA mode, Scheduler can be optionally made to use Ephemeral storage, which is in-memory storage that is **not** resilient to restarts. For example, all Job data will be lost after a Scheduler restart.
```

2024-12-04 14:59 UTC, hhunter-ms approved these changes

2024-12-10 03:21 UTC, msfussell reviewed
Also see comment here https://github.com/dapr/docs/pull/4452 in that we need to describe how to set up HA mode. If this is Kubernetes specific, then can be added to this article. Please coordinate with @cicoyle 

Also @hhunter-ms - All the headings in this article are upper case and need to be lower case. Maybe include this in another update or Elena if you can do this.

2024-12-10 03:21 UTC, msfussell commented on daprdocs/content/en/operations/hosting/kubernetes/kubernetes-persisting-scheduler.md
> +When running in non-HA mode, Scheduler can be optionally made to use Ephemeral storage, which is in-memory storage that is **not** resilient to restarts. For example, all Job data will be lost after
```suggestion
When running in non-HA mode, the Scheduler can be optionally made to use ephemeral storage, which is in-memory storage that is **not** resilient to restarts. For example, all jobs data is lost after a Scheduler restart.
```

2024-12-10 03:21 UTC, msfussell commented on daprdocs/content/en/operations/hosting/kubernetes/kubernetes-persisting-scheduler.md
> +This is useful for non-production deployments where storage is not available or required, or for testing purposes.
```suggestion
This is useful for non-production deployments where storage is not available or required, or for testing purposes.
```
```suggestion
This is useful in non-production deployments or for testing where storage is not available or required.
```

2024-12-12 22:37 UTC, msfussell approved these changes
LGTM

2024-12-12 22:37 UTC, merged