Changes to State Management and Pub/Sub articles and improving Redis docs.
dapr/docs pull request #831
Opened 2020-09-26 04:29 UTC by msfussell

Started doing this issue https://github.com/dapr/docs/issues/801 and then found lots of other issues

2020-09-27 09:22 UTC, mukundansundar commented on concepts/service-invocation/README.md
> +* Authentication errors due to a renewing certificate on the calling/callee Dapr sidecars
```suggestion
* Authentication errors due to a renewing certificate on the caller/callee Dapr sidecars
```

2020-09-27 09:22 UTC, mukundansundar commented on howto/README.md
Add scoping secrets https://github.com/dapr/docs/pull/831/files#diff-16351cf6b4b3e0afe110f59a5bbf6e47R79 ?

2020-09-27 09:22 UTC, mukundansundar commented on howto/configure-redis/README.md
>  Dapr can use Redis in two ways:
three ways. As a binding with CreateOperation support. https://github.com/dapr/components-contrib/blob/master/bindings/redis/redis.go

2020-09-27 09:22 UTC, mukundansundar commented on howto/configure-redis/README.md
> +4. Next, we'll get our Redis password using a `secretKeyRef` to a Kubernetes secret that has been configured into your cluster when Redis was installed. You can see the name of the secret key with `k
4.1 and 4.2?

2020-09-27 09:22 UTC, mukundansundar commented on howto/publish-topic/README.md
> +Dapr wraps the user payload in a Cloud Events v1.0 compliant envelope.
if it is not in Cloud Events 1.0 format, otherwise it passes along an already formatted message.

2020-09-28 15:13 UTC, yaron2 requested changes
one nit, otherwise lgtm

2020-09-28 15:13 UTC, yaron2 commented on howto/configure-redis/README.md
> +4. b Its **not recommended**, however you can use a hard coded password instead. First we'll get our Redis password, which is slightly different depending on the OS we're using:
Redundant `b` in beginning of sentence?

2020-09-28 17:04 UTC, mchmarny approved these changes
/lgtm

2020-09-28 17:07 UTC, yaron2 approved these changes

2020-09-28 17:07 UTC, merged