Update Homebrew command
dapr/docs pull request #850
Opened 2020-10-08 08:53 UTC by jdubois

The current command fails, here is the updated version

Thank you for helping make the Dapr documentation better!

If you are a new contributor, please see the [this contribution guidance](https://github.com/dapr/docs/blob/master/contributing/README.md) which helps keep the Dapr documentation readable, consistent and useful for Dapr users.

If you are contributing a new authored "How To" article, [this template](https://github.com/dapr/docs/blob/master/contributing/howto-template.md) was created to assist you.

In addition, please fill out the following to help reviewers understand this pull request:

## Description

Update the Homebrew command

## Issue reference

I didn't create an issue for something this simple

2020-10-09 17:39 UTC, yaron2 commented
/cc @artursouza can you please review this?

2020-10-13 23:55 UTC, artursouza requested changes
This command does not work for first time installs because dapr-cli is not in Homebrew's main repo.

2020-10-13 23:57 UTC, artursouza commented
This works on my desktop. Which version of Homebrew are you running with?

```sh
$ brew install dapr/tap/dapr-cli
Updating Homebrew...
==> Auto-updated Homebrew!
Updated 2 taps (homebrew/core and homebrew/cask).
==> New Formulae
box2d                              dotnet                             envoy                              fleet-cli                          git-hound                          libpciaccess                       matplotplusplus                    protoc-gen-go-grpc                 python@3.9                         tfsec
==> Updated Formulae
Updated 572 formulae.
==> New Casks
mtgaprotracker                                             niftyman                                                   recaf                                                      ripme                                                      time-to-leave                                              waterfox-classic
==> Updated Casks
postman ✔                          backblaze                          datovka                            gisto                              karabiner-elements                 metabase                           obyte                              qobuz                              steermouse                         visual-paradigm
4k-video-downloader                badlion-client                     deepl                              gitfinder                          keep-it                            metasploit                         openaudible                        qownnotes                          stella                             visual-paradigm-ce
4k-youtube-to-mp3                  banking-4                          deezer                             gns3                               kext-updater                       microblog                          opensesame                         qt-creator                         streamlabs-obs                     visual-studio-code
a-better-finder-attributes         bettertouchtool                    disk-drill                         gobdokumente                       keysmith                           microsoft-edge                     openwebstart                       qtum                               stremio                            vscodium
a-better-finder-rename             bob                                djay-pro                           google-chrome                      kitty                              middle                             opera                              r                                  sunloginclient                     webcatalog
ableton-live                       bookmacster                        downie                             gpxsee                             klokki                             miktex-console                     origami-studio                     rambox                             superproductivity                  webstorm
ableton-live-intro                 boom                               drawio                             graphicconverter                   knotes                             milanote                           osmc                               raven-reader                       teamdrive                          whatsapp
ableton-live-lite                  bootstrap-studio                   drivethrurpg                       home-assistant                     kui                                minitube                           osxfuse                            razorsql                           telegram-desktop                   whichspace
ableton-live-standard              box-drive                          electrumsv                         houdahspot                         lastpass                           minizincide                        outline-manager                    rectangle                          tempo                              wingpersonal
ableton-live-suite                 brave-browser                      element                            icab                               lazpaint                           monero-wallet                      parallels                          refined-github-safari              tg-pro                             wire
activedock                         browserosaurus                     emby-server                        icollections                       lehreroffice                       mps                                paw                                ridibooks                          thebrain                           wondershare-filmora
adguard                            calibre                            emclient                           iconjar                            lens                               multitouch                         pd-l2ork                           ringcentral                        thorium                            workflowy
agenda                             camo-studio                        epic-games                         icq                                libreoffice                        mumu                               pdfpen                             ringcentral-meetings               thunderbird                        wormhole
airflow                            camunda-modeler                    evernote                           iina                               libreoffice-language-pack          musescore                          pdfpenpro                          rocks-n-diamonds                   tibco-jaspersoft-studio            ximalaya
airtame                            catlight                           exodus                             iina-plus                          linear-linear                      naver-whale                        permute                            rotki                              timecamp                           xmplify
airy                               ccleaner                           expandrive                         ilok-license-manager               linphone                           navicat-for-mariadb                photosweeper-x                     rubymine                           timeular                           yinxiangbiji
ajour                              chirp                              fastrawviewer                      imazing                            local                              navicat-for-mysql                  plex-media-server                  sauce-connect                      tinderbox                          youku
alfaview                           chromedriver                       flipper                            insync                             loom                               navicat-for-oracle                 plotdigitizer                      scilab                             tinymediamanager                   zenmap
alt-tab                            chromium                           flutter                            intel-haxm                         lrtimelapse                        navicat-for-postgresql             popo                               scrutiny                           tortoisehg                         zeplin
altserver                          chronycontrol                      folx                               intellij-idea                      ltspice                            navicat-for-sql-server             porting-kit                        securityspy                        transmission                       zoolz
amadine                            clamxav                            foxitreader                        intellij-idea-ce                   macupdater                         navicat-for-sqlite                 postbox                            simply-fortran                     trilium-notes                      zoom-for-it-admins
android-studio                     clash-for-windows                  freac                              invisor-lite                       mailbutler                         navicat-premium-essentials         pra [...]

2020-10-14 11:49 UTC, jdubois commented
I'm using Homebrew 2.5.6, which is the latest version at the moment

2020-10-16 21:36 UTC, artursouza commented
Here is how it works on my desktop:

```sh
$ brew --version
Homebrew 2.5.6
$ brew uninstall dapr-cli
Uninstalling /usr/local/Cellar/dapr-cli/0.11.0... (5 files, 57.3MB)
$ brew untap dapr/tap
Untapping dapr/tap...
Untapped 1 formula (120 files, 18.9MB).
$ brew tap
golangci/tap
homebrew/cask
homebrew/core
k14s/tap
$ brew install dapr/tap/dapr-cli
Updating Homebrew...
==> Tapping dapr/tap
Cloning into '/usr/local/Homebrew/Library/Taps/dapr/homebrew-tap'...
remote: Enumerating objects: 44, done.
remote: Counting objects: 100% (44/44), done.
remote: Compressing objects: 100% (27/27), done.
remote: Total 90 (delta 19), reused 33 (delta 13), pack-reused 46
Unpacking objects: 100% (90/90), done.
Tapped 1 formula (120 files, 18.9MB).
==> Installing dapr-cli from dapr/tap
==> Downloading https://github.com/dapr/homebrew-tap/releases/download/v0.11.0/dapr-cli-0.11.0.catalina.bottle.tar.gz
Already downloaded: /Users/asouza/Library/Caches/Homebrew/downloads/cbbc38683646d71a416d85868fb16384bafe7632a4f804d38a550ef6484d7f74--dapr-cli-0.11.0.catalina.bottle.tar.gz
==> Pouring dapr-cli-0.11.0.catalina.bottle.tar.gz
🍺  /usr/local/Cellar/dapr-cli/0.11.0: 5 files, 57.3MB
$ 
```

Please, share the error you get when doing the same.

2020-10-19 08:47 UTC, jdubois commented
I just tested again, and both work now. Maybe it was updated on your side?
So you can definitely use both at the moment, then `brew install dapr-cli` is simpler.

2020-10-19 23:38 UTC, artursouza commented
@jdubois We have not changed anything. For a first time user, `brew install dapr-cli` will not work because `dapr-cli` is not in Homebrew's main repo.

First time users have two options: `brew install dapr/tap/dapr-cli` OR `brew tap dapr/tap && brew install dapr-cli`
After the first install, users can use one of the following options: `brew install dapr/tap/dapr-cli` OR `brew install dapr-cli`

Closing this issue. Thanks for reporting and working with us on this.

2020-10-19 23:38 UTC, closed without merging